DKD.engines.platformer=session=>{
 const state={};const variant=session.game.variant||0;const difficulty=DKD.state.settings.difficulty==='Easy'?.7:DKD.state.settings.difficulty==='Hard'?1.3:1;
 function level(number){state.level=number;state.player={x:95,y:530,vx:0,vy:0,jumps:0,facing:1};state.camera=0;state.checkpoint={x:95,y:530};state.invincible=2;state.platforms=[{x:0,y:720,w:550},{x:470,y:570,w:210},{x:780,y:660,w:290},{x:1140,y:570,w:260},{x:1440,y:680,w:400},{x:1700,y:500,w:210},{x:2010,y:590,w:250},{x:2330,y:700,w:420},{x:2580,y:520,w:240},{x:2880,y:420,w:210},{x:3200,y:580,w:350},{x:3550,y:680,w:330},{x:3860,y:500,w:250},{x:4190,y:610,w:340},{x:4510,y:470,w:240},{x:4810,y:650,w:470}].map((platform,index)=>({...platform,y:platform.y-(number>1&&index%3===1?35:0)}));state.shards=[];state.enemies=[];state.platforms.forEach((platform,index)=>{if(index){for(let coin=0;coin<3;coin++)state.shards.push({x:platform.x+45+coin*55,y:platform.y-48,collected:false});}if(index>2&&index%2===(number%2)){state.enemies.push({platform:platform,x:platform.x+platform.w/2,y:platform.y-25,phase:index});}});state.portal={x:5130,y:650};session.message(['THE FLOATING GARDENS','ECHOES IN THE MIST','THE MOON GATE'][number-1],3);}
 function reset(){Object.assign(state,{time:0,score:0,lives:3,shardsCount:0,particles:[]});level(1);}
 function hurt(){if(state.invincible>0)return;state.lives--;DKD.audio.hit();state.invincible=2.5;if(state.lives<=0){session.finish();return;}Object.assign(state.player,{x:state.checkpoint.x,y:state.checkpoint.y,vx:0,vy:0,jumps:0});}
 function update(dt,input){state.time+=dt;state.invincible=Math.max(0,state.invincible-dt);const player=state.player;const move=(input.down('KeyD','ArrowRight')?1:0)-(input.down('KeyA','ArrowLeft')?1:0)+input.pad.x;player.vx=move*315;if(Math.abs(move)>.1)player.facing=Math.sign(move);if((input.hit('Space','KeyW','ArrowUp')||input.pad.jump)&&player.jumps<2){player.vy=player.jumps===0?-605:-555;player.jumps++;DKD.audio.tone(player.jumps===1?420:580,.11,'sine',.025);}const prevBottom=player.y+28;player.x=DKD.clamp(player.x+player.vx*dt,18,5250);player.vy+=1450*dt;player.y+=player.vy*dt;
 for(const platform of state.platforms){if(player.x+17>platform.x&&player.x-17<platform.x+platform.w&&prevBottom<=platform.y+4&&player.y+28>=platform.y&&player.vy>=0){player.y=platform.y-28;player.vy=0;player.jumps=0;if(platform.x>state.checkpoint.x+650)state.checkpoint={x:platform.x+30,y:platform.y-80};}}
 if(player.y>1050){state.invincible=0;hurt();}for(const shard of state.shards){if(!shard.collected&&Math.hypot(player.x-shard.x,player.y-shard.y)<38){shard.collected=true;state.score+=100;state.shardsCount++;DKD.audio.collect();for(let spark=0;spark<9;spark++)state.particles.push({x:shard.x,y:shard.y,vx:(Math.random()-.5)*160,vy:(Math.random()-.5)*160,life:.7});if(state.shardsCount===15)DKD.award(session.game.id+'-light','Keeper of the light');}}
 for(const enemy of state.enemies){enemy.x=enemy.platform.x+enemy.platform.w/2+Math.sin(state.time*(1+variant*.15+state.level*.1)*difficulty+enemy.phase)*(enemy.platform.w/2-28);if(Math.abs(player.x-enemy.x)<33&&Math.abs(player.y-enemy.y)<40){if(player.vy>180&&player.y<enemy.y-14){enemy.defeated=true;player.vy=-430;state.score+=200;DKD.audio.collect();}else hurt();}}state.enemies=state.enemies.filter(enemy=>!enemy.defeated);state.particles.forEach(particle=>{particle.x+=particle.vx*dt;particle.y+=particle.vy*dt;particle.life-=dt;});state.particles=state.particles.filter(particle=>particle.life>0);state.camera+=(DKD.clamp(player.x-570,0,3680)-state.camera)*Math.min(1,dt*6);
 if(player.x>5090&&player.y>500){state.score+=1000+state.lives*250;if(state.level===3)session.finish(true);else level(state.level+1);}
 }
 function render(ctx){const gradient=ctx.createLinearGradient(0,0,0,900);gradient.addColorStop(0,'#071526');gradient.addColorStop(1,'#173c52');ctx.fillStyle=gradient;ctx.fillRect(0,0,1600,900);if(session.background.complete){ctx.globalAlpha=.48;ctx.drawImage(session.background,-state.camera*.06,-15,1820,1030);ctx.globalAlpha=1;}ctx.fillStyle='#09182766';ctx.fillRect(0,0,1600,900);
 ctx.save();ctx.translate(-state.camera,0);for(const platform of state.platforms){if(platform.x+platform.w<state.camera-40||platform.x>state.camera+1660)continue;const rock=ctx.createLinearGradient(0,platform.y,0,platform.y+200);rock.addColorStop(0,'#31546b');rock.addColorStop(1,'#10253500');ctx.fillStyle=rock;ctx.beginPath();ctx.moveTo(platform.x,platform.y);ctx.lineTo(platform.x+platform.w,platform.y);ctx.lineTo(platform.x+platform.w-25,platform.y+80);ctx.lineTo(platform.x+platform.w*.55,platform.y+190);ctx.lineTo(platform.x+25,platform.y+110);ctx.closePath();ctx.fill();ctx.strokeStyle='#91deddaa';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(platform.x,platform.y);ctx.lineTo(platform.x+platform.w,platform.y);ctx.stroke();ctx.strokeStyle='#406c7466';ctx.lineWidth=2;for(let detail=0;detail<5;detail++){const x=platform.x+30+detail*platform.w/5;ctx.beginPath();ctx.moveTo(x,platform.y+14);ctx.lineTo(x+15,platform.y+55);ctx.stroke();}}
 for(const shard of state.shards){if(shard.collected)continue;ctx.save();ctx.translate(shard.x,shard.y+Math.sin(state.time*3+shard.x)*7);ctx.rotate(Math.PI/4+Math.sin(state.time)*.15);ctx.fillStyle='#bffaff';ctx.shadowColor='#57ddff';ctx.shadowBlur=20;ctx.fillRect(-8,-8,16,16);ctx.restore();}
 for(const enemy of state.enemies){ctx.save();ctx.translate(enemy.x,enemy.y);ctx.fillStyle='#27203f';ctx.shadowColor='#eb7495';ctx.shadowBlur=14;ctx.beginPath();ctx.moveTo(-20,14);ctx.lineTo(-16,-17);ctx.lineTo(0,-28);ctx.lineTo(16,-17);ctx.lineTo(20,14);ctx.fill();ctx.fillStyle='#ff8bb1';ctx.fillRect(-11,-11,8,4);ctx.fillRect(4,-11,8,4);ctx.restore();}
 const portal=state.portal;ctx.save();ctx.translate(portal.x,portal.y-82);ctx.strokeStyle='#adf4ff';ctx.lineWidth=7;ctx.shadowColor='#86efff';ctx.shadowBlur=30;ctx.beginPath();ctx.ellipse(0,0,47+Math.sin(state.time*2)*3,77,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#62c4e022';ctx.fill();ctx.restore();
 const player=state.player;if(state.invincible<=0||Math.floor(state.time*9)%2===0){ctx.save();ctx.translate(player.x,player.y);ctx.scale(player.facing,1);ctx.fillStyle='#e4e8dc';ctx.beginPath();ctx.moveTo(-10,-6);ctx.lineTo(-25,30);ctx.quadraticCurveTo(0,15,22,27);ctx.lineTo(9,-6);ctx.fill();ctx.fillStyle='#7cf4ff';ctx.shadowColor='#5be8ff';ctx.shadowBlur=25;ctx.beginPath();ctx.arc(0,-12,13,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#d6fcff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-8,-21);ctx.lineTo(-12,-31);ctx.moveTo(8,-21);ctx.lineTo(11,-31);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#214d63';ctx.fillRect(1,-14,9,3);ctx.strokeStyle='#c7dde5';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-6,15);ctx.lineTo(-9,28);ctx.moveTo(5,15);ctx.lineTo(9,28);ctx.stroke();ctx.restore();}
 for(const particle of state.particles){ctx.globalAlpha=particle.life;ctx.fillStyle='#b4f7ff';ctx.fillRect(particle.x,particle.y,4,4);}ctx.globalAlpha=1;ctx.restore();
 const fog=ctx.createLinearGradient(0,780,0,900);fog.addColorStop(0,'#18465900');fog.addColorStop(1,'#89c7d388');ctx.fillStyle=fog;ctx.fillRect(0,780,1600,120);
 }
 return {reset,update,render,stats:()=>({score:state.score,lives:state.lives,label:'THE JOURNEY',stage:`WORLD ${state.level} / 3`,progress:state.player.x/52,extra:`${state.shardsCount} LIGHT SHARDS`})};
};
