DKD.engines.racer=session=>{
 const state={};const difficulty=DKD.state.settings.difficulty==='Easy'?.75:DKD.state.settings.difficulty==='Hard'?1.25:1;const variant=session.game.variant||0;
 function reset(){Object.assign(state,{time:0,distance:0,speed:0,position:0,score:0,lives:3,boost:100,stage:1,invincible:0,spawn:1,traffic:[],pickups:[],passed:0,flash:0});}
 function update(dt,input){state.time+=dt;const accelerate=input.down('KeyW','ArrowUp')||input.pad.y<-.25,brake=input.down('KeyS','ArrowDown')||input.pad.y>.25,boost=(input.down('ShiftLeft','ShiftRight')||input.pad.boost)&&state.boost>0;const target=brake?70:boost?335:accelerate?255:170;state.speed+=(target-state.speed)*dt*1.2;state.boost=DKD.clamp(state.boost+(boost?-28:8)*dt,0,100);const steer=(input.down('KeyD','ArrowRight')?1:0)-(input.down('KeyA','ArrowLeft')?1:0)+input.pad.x;state.position=DKD.clamp(state.position+steer*dt*(1.2+state.speed/260),-1.3,1.3);if(Math.abs(state.position)>1.06){state.speed*=1-dt;state.position-=Math.sign(state.position)*dt*.13;}state.distance+=state.speed*dt/3.6;state.score+=state.speed*dt/12;const stage=Math.min(5,1+Math.floor(state.distance/1300));if(stage!==state.stage){state.stage=stage;session.message('STAGE '+stage+' / 5');DKD.audio.collect();if(stage===3)DKD.award(session.game.id+'-half','Halfway to the horizon');}if(state.distance>=6500){session.finish(true);return;}state.invincible=Math.max(0,state.invincible-dt);state.flash=Math.max(0,state.flash-dt);state.spawn-=dt;
 if(state.spawn<=0){state.traffic.push({x:[-.73,0,.73][Math.floor(Math.random()*3)],z:.02,color:['#de585c','#79a2c3','#c5cad4','#dab55b'][Math.floor(Math.random()*4)]});if(Math.random()>.67)state.pickups.push({x:[-.73,0,.73][Math.floor(Math.random()*3)],z:.01});state.spawn=(1.8-Math.min(.75,state.stage*.13))/(difficulty+variant*.12);}
 for(const car of state.traffic){car.z+=dt*(state.speed/1000+.02);if(car.z>.89&&car.z<1.08&&Math.abs(car.x-state.position)<.28&&state.invincible<=0){state.lives--;state.invincible=2;state.flash=.35;state.speed*=.42;DKD.audio.hit();if(state.lives<=0){session.finish(false);return;}}if(car.z>1.1&&!car.passed){car.passed=true;state.passed++;state.score+=150;}}
 state.traffic=state.traffic.filter(car=>car.z<1.2);for(const pickup of state.pickups){pickup.z+=dt*state.speed/850;if(pickup.z>.87&&Math.abs(pickup.x-state.position)<.3){pickup.z=2;state.boost=Math.min(100,state.boost+25);state.score+=250;DKD.audio.collect();}}state.pickups=state.pickups.filter(item=>item.z<1.2);
 }
 const project=(position,depth)=>{const perspective=depth*depth;return {x:800+Math.sin(state.distance/900+depth*1.7)*140*(1-depth)+position*(70+perspective*610),y:360+perspective*520,scale:.12+perspective*1.35};};
 function car(ctx,x,y,scale,color,player=false){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.shadowColor=player?'#95baf566':'#000a';ctx.shadowBlur=20;ctx.fillStyle='#030712';ctx.fillRect(-46,-60,13,74);ctx.fillRect(33,-60,13,74);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(-38,18);ctx.lineTo(-42,-34);ctx.lineTo(-27,-84);ctx.lineTo(27,-84);ctx.lineTo(42,-34);ctx.lineTo(38,18);ctx.closePath();ctx.fill();ctx.fillStyle='#17344e';ctx.beginPath();ctx.moveTo(-26,-31);ctx.lineTo(-20,-65);ctx.lineTo(20,-65);ctx.lineTo(26,-31);ctx.fill();ctx.fillStyle='#f04f62';ctx.shadowColor='#f43147';ctx.shadowBlur=13;ctx.fillRect(-33,3,23,6);ctx.fillRect(10,3,23,6);ctx.shadowBlur=0;ctx.fillStyle='#232d3b';ctx.fillRect(-15,8,30,6);ctx.strokeStyle='#e3ebf866';ctx.lineWidth=2;ctx.strokeRect(-35,-16,70,14);ctx.restore();}
 function render(ctx){const gradient=ctx.createLinearGradient(0,0,0,900);gradient.addColorStop(0,'#060d21');gradient.addColorStop(.4,'#314863');gradient.addColorStop(.41,'#17263a');gradient.addColorStop(1,'#06101d');ctx.fillStyle=gradient;ctx.fillRect(0,0,1600,900);ctx.fillStyle='#d8e7ff';ctx.shadowColor='#bad5ff';ctx.shadowBlur=40;ctx.beginPath();ctx.arc(1170,155,40,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;
 for(let layer=0;layer<3;layer++){ctx.fillStyle=['#182b45','#10223b','#0c192c'][layer];ctx.beginPath();ctx.moveTo(0,410);for(let step=0;step<=20;step++)ctx.lineTo(step*85,310+layer*30-Math.sin(step*2.3+layer)*75);ctx.lineTo(1600,450);ctx.lineTo(0,450);ctx.fill();}
 for(let row=0;row<64;row++){const depth=row/64,next=(row+1)/64,left=project(-1.35,depth),right=project(1.35,depth),leftNext=project(-1.35,next),rightNext=project(1.35,next);ctx.fillStyle=Math.floor(row+state.distance/11)%2===0?'#243344':'#263646';ctx.beginPath();ctx.moveTo(left.x,left.y);ctx.lineTo(right.x,right.y);ctx.lineTo(rightNext.x,rightNext.y);ctx.lineTo(leftNext.x,leftNext.y);ctx.fill();for(const edge of [-1.24,1.24]){const start=project(edge,depth),end=project(edge,next);ctx.strokeStyle='#87c8e7';ctx.lineWidth=1+depth*5;ctx.beginPath();ctx.moveTo(start.x,start.y);ctx.lineTo(end.x,end.y);ctx.stroke();}if(Math.floor(row/4+state.distance/35)%2===0){for(const lane of [-.37,.37]){const start=project(lane,depth),end=project(lane,next);ctx.strokeStyle='#d5e2ed72';ctx.lineWidth=1+depth*4;ctx.beginPath();ctx.moveTo(start.x,start.y);ctx.lineTo(end.x,end.y);ctx.stroke();}}}
 for(const traffic of [...state.traffic].sort((first,second)=>first.z-second.z)){const point=project(traffic.x,traffic.z);car(ctx,point.x,point.y,point.scale,traffic.color);}
 for(const pickup of state.pickups){const point=project(pickup.x,pickup.z);ctx.save();ctx.translate(point.x,point.y-30*point.scale);ctx.rotate(Math.PI/4);ctx.fillStyle='#81f5ff';ctx.shadowColor='#57dfff';ctx.shadowBlur=20;ctx.fillRect(-12*point.scale,-12*point.scale,24*point.scale,24*point.scale);ctx.restore();}
 if(state.invincible<=0||Math.floor(state.time*10)%2===0){const point=project(state.position,.98);car(ctx,point.x,820,1.5,'#c6d0dc',true);if(state.speed>285){ctx.fillStyle='#79caff99';ctx.fillRect(point.x-27,850,12,30+Math.random()*20);ctx.fillRect(point.x+15,850,12,30+Math.random()*20);}}
 ctx.strokeStyle='#cde3f01c';ctx.lineWidth=1;for(let drop=0;drop<55;drop++){const x=(drop*139+state.time*180)%1600,y=(drop*67+state.time*620)%900;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-9,y+27);ctx.stroke();}if(state.flash>0){ctx.fillStyle=`rgba(255,65,78,${state.flash*.55})`;ctx.fillRect(0,0,1600,900);}
 }
 return {reset,update,render,stats:()=>({score:state.score,lives:state.lives,label:'MIDNIGHT RUN',stage:`STAGE ${state.stage} / 5`,progress:state.distance%1300/13,extra:`${Math.round(state.speed)} km/h  ·  BOOST ${Math.round(state.boost)}%`})};
};
