DKD.engines.shooter=session=>{
 const state={};const variant=session.game.variant||0;const difficulty=DKD.state.settings.difficulty==='Easy'?.75:DKD.state.settings.difficulty==='Hard'?1.25:1;
 function reset(){Object.assign(state,{time:0,score:0,lives:3,player:{x:800,y:530,angle:-Math.PI/2},wave:1,spawn:1,remaining:8,kills:0,weapon:1,shots:[],enemies:[],particles:[],pickups:[],invincible:2,fire:0,dash:0,transition:0,stars:Array.from({length:110},()=>({x:Math.random()*1600,y:Math.random()*900,size:Math.random()*1.5+.5}))});}
 function update(dt,input){state.time+=dt;state.invincible=Math.max(0,state.invincible-dt);state.dash=Math.max(0,state.dash-dt);const player=state.player;let moveX=(input.down('KeyD')?1:0)-(input.down('KeyA')?1:0)+input.pad.x,moveY=(input.down('KeyS')?1:0)-(input.down('KeyW')?1:0)+input.pad.y;const length=Math.hypot(moveX,moveY);if(length>1){moveX/=length;moveY/=length;}let speed=310;if((input.hit('KeyE')||input.pad.dash)&&state.dash<=0){state.dash=3.5;state.invincible=.35;player.x+=moveX*190;player.y+=moveY*190;DKD.audio.tone(240,.16,'sawtooth',.025);}player.x=DKD.clamp(player.x+moveX*speed*dt,30,1570);player.y=DKD.clamp(player.y+moveY*speed*dt,110,820);
 const aimX=(input.down('ArrowRight')?1:0)-(input.down('ArrowLeft')?1:0),aimY=(input.down('ArrowDown')?1:0)-(input.down('ArrowUp')?1:0);if(Math.hypot(input.pad.aimX,input.pad.aimY)>.25)player.angle=Math.atan2(input.pad.aimY,input.pad.aimX);else if(aimX||aimY)player.angle=Math.atan2(aimY,aimX);else if(input.pointer.active)player.angle=Math.atan2(input.pointer.y-player.y,input.pointer.x-player.x);else if(state.enemies.length&&document.getElementById('console').classList.contains('touch-device')){const enemy=state.enemies.reduce((best,item)=>Math.hypot(item.x-player.x,item.y-player.y)<Math.hypot(best.x-player.x,best.y-player.y)?item:best);player.angle=Math.atan2(enemy.y-player.y,enemy.x-player.x);}
 state.fire-=dt;if((input.down('Space')||input.pointer.down||aimX||aimY||input.pad.fire)&&state.fire<=0){for(let spread=0;spread<state.weapon;spread++){const angle=player.angle+(spread-(state.weapon-1)/2)*.12;state.shots.push({x:player.x+Math.cos(angle)*24,y:player.y+Math.sin(angle)*24,vx:Math.cos(angle)*790,vy:Math.sin(angle)*790,enemy:false,life:1.8});}state.fire=.15;DKD.audio.tone(880,.045,'triangle',.011);}
 state.spawn-=dt;if(state.remaining>0&&state.spawn<=0){const side=Math.floor(Math.random()*4);const boss=state.wave%3===0&&state.remaining===1;state.enemies.push({x:side===0?-25:side===1?1625:Math.random()*1600,y:side===2?90:side===3?840:150+Math.random()*620,hp:boss?18+state.wave*3:1+Math.floor(state.wave/3),boss,radius:boss?42:19,fire:1.5,phase:Math.random()*6});state.remaining--;state.spawn=Math.max(.33,1.05-state.wave*.07)/(1+variant*.1);}
 for(const enemy of state.enemies){const angle=Math.atan2(player.y-enemy.y,player.x-enemy.x),enemySpeed=(enemy.boss?45:55+state.wave*8+variant*7)*difficulty;enemy.x+=Math.cos(angle)*enemySpeed*dt;enemy.y+=Math.sin(angle)*enemySpeed*dt;enemy.fire-=dt;if((enemy.boss||state.wave>=3)&&enemy.fire<=0){for(let shot=0;shot<(enemy.boss?5:1);shot++){const bulletAngle=angle+(shot-(enemy.boss?2:0))*.24;state.shots.push({x:enemy.x,y:enemy.y,vx:Math.cos(bulletAngle)*235,vy:Math.sin(bulletAngle)*235,enemy:true,life:5});}enemy.fire=enemy.boss?1.4:3.5;}if(Math.hypot(player.x-enemy.x,player.y-enemy.y)<enemy.radius+17&&state.invincible<=0)hurt();}
 for(const shot of state.shots){shot.x+=shot.vx*dt;shot.y+=shot.vy*dt;shot.life-=dt;if(shot.enemy){if(Math.hypot(player.x-shot.x,player.y-shot.y)<19&&state.invincible<=0){shot.life=0;hurt();}}else{for(const enemy of state.enemies){if(enemy.hp>0&&Math.hypot(enemy.x-shot.x,enemy.y-shot.y)<enemy.radius+5){shot.life=0;enemy.hp--;if(enemy.hp<=0){state.score+=enemy.boss?1500:100;state.kills++;explode(enemy.x,enemy.y,enemy.boss?35:15);if(state.kills%12===0)state.pickups.push({x:enemy.x,y:enemy.y,type:'power',life:12});if(state.kills===20)DKD.award(session.game.id+'-defender','Defender of the void');}break;}}}}
 state.shots=state.shots.filter(shot=>shot.life>0&&shot.x>-80&&shot.x<1680&&shot.y>-80&&shot.y<980);state.enemies=state.enemies.filter(enemy=>enemy.hp>0);for(const pickup of state.pickups){pickup.life-=dt;if(Math.hypot(player.x-pickup.x,player.y-pickup.y)<40){pickup.life=0;state.weapon=Math.min(3,state.weapon+1);state.score+=250;session.message('WEAPON UPGRADED');DKD.audio.collect();}}state.pickups=state.pickups.filter(pickup=>pickup.life>0);state.particles.forEach(particle=>{particle.x+=particle.vx*dt;particle.y+=particle.vy*dt;particle.life-=dt;});state.particles=state.particles.filter(particle=>particle.life>0);
 if(state.remaining===0&&state.enemies.length===0){state.transition+=dt;if(state.transition>2){if(state.wave>=8){session.finish(true);return;}state.wave++;state.remaining=7+state.wave*3;state.transition=0;state.score+=500;session.message('WAVE '+state.wave+' / 8');DKD.audio.collect();}}
 }
 function hurt(){state.lives--;state.invincible=2;explode(state.player.x,state.player.y,20);DKD.audio.hit();if(state.lives<=0)session.finish();}
 function explode(x,y,count){for(let index=0;index<count;index++){const angle=Math.random()*Math.PI*2,speed=50+Math.random()*200;state.particles.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,life:.5+Math.random()*.6});}}
 function ship(ctx,x,y,angle,color,size){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.fillStyle=color;ctx.shadowColor=color;ctx.shadowBlur=14;ctx.beginPath();ctx.moveTo(size*1.5,0);ctx.lineTo(-size,size*.85);ctx.lineTo(-size*.5,0);ctx.lineTo(-size,-size*.85);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#1a2850';ctx.beginPath();ctx.moveTo(size*.5,0);ctx.lineTo(-size*.4,size*.22);ctx.lineTo(-size*.4,-size*.22);ctx.fill();ctx.fillStyle='#94d7ff';ctx.fillRect(-size*1.25,-size*.19,6+Math.random()*10,size*.38);ctx.restore();}
 function render(ctx){ctx.fillStyle='#060a1c';ctx.fillRect(0,0,1600,900);if(session.background.complete){ctx.globalAlpha=.3;ctx.drawImage(session.background,0,0,1600,900);ctx.globalAlpha=1;}ctx.fillStyle='#060a1c66';ctx.fillRect(0,0,1600,900);for(const star of state.stars){ctx.fillStyle=`rgba(193,218,255,${.35+Math.sin(state.time+star.x)*.25})`;ctx.fillRect(star.x,(star.y+state.time*star.size*7)%900,star.size,star.size);}
 for(const shot of state.shots){ctx.strokeStyle=shot.enemy?'#ff899d':'#89e4ff';ctx.lineWidth=shot.enemy?5:3;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=12;ctx.beginPath();ctx.moveTo(shot.x,shot.y);ctx.lineTo(shot.x-shot.vx*.02,shot.y-shot.vy*.02);ctx.stroke();}ctx.shadowBlur=0;
 for(const enemy of state.enemies){ship(ctx,enemy.x,enemy.y,Math.atan2(state.player.y-enemy.y,state.player.x-enemy.x),enemy.boss?'#ec71a4':'#b595e9',enemy.radius);if(enemy.boss){ctx.fillStyle='#ffffff22';ctx.fillRect(enemy.x-40,enemy.y-60,80,5);ctx.fillStyle='#f9a4cb';ctx.fillRect(enemy.x-40,enemy.y-60,80*enemy.hp/(18+state.wave*3),5);}}
 if(state.invincible<=0||Math.floor(state.time*10)%2===0)ship(ctx,state.player.x,state.player.y,state.player.angle,'#d4edff',22);
 for(const pickup of state.pickups){ctx.save();ctx.translate(pickup.x,pickup.y);ctx.rotate(state.time);ctx.strokeStyle='#7ef1cf';ctx.lineWidth=3;ctx.shadowColor='#7ef1cf';ctx.shadowBlur=16;ctx.strokeRect(-14,-14,28,28);ctx.restore();}for(const particle of state.particles){ctx.globalAlpha=Math.min(1,particle.life);ctx.fillStyle='#ffc8f0';ctx.fillRect(particle.x,particle.y,3,3);}ctx.globalAlpha=1;
 }
 return {reset,update,render,stats:()=>({score:state.score,lives:state.lives,label:'DEFEND THE SECTOR',stage:`WAVE ${state.wave} / 8`,healthLabel:'SHIELDS',progress:(1-(state.remaining+state.enemies.length)/(7+state.wave*3))*100,extra:`WEAPON ${state.weapon}  ·  DASH ${state.dash>0?state.dash.toFixed(1)+'s':'READY'}`})};
};
