import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { XMLParser } from 'fast-xml-parser';
import sharp from 'sharp';

const dkdRoot=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const dkdCommand=process.argv[2]||'update';
const dkdParser=new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_',textNodeName:'#text',cdataPropName:'__cdata',trimValues:true});
const dkdPaths={sources:path.join(dkdRoot,'config','sources.json'),news:path.join(dkdRoot,'data','news.json'),social:path.join(dkdRoot,'data','social-state.json'),socialImage:path.join(dkdRoot,'social','latest.png')};
const dkdNow=Date.now();
const dkdArray=dkdValue=>Array.isArray(dkdValue)?dkdValue:dkdValue?[dkdValue]:[];
async function dkdReadJson(dkdPath,dkdFallback){try{return JSON.parse(await fs.readFile(dkdPath,'utf8'));}catch{return dkdFallback;}}
async function dkdWriteJson(dkdPath,dkdValue){await fs.mkdir(path.dirname(dkdPath),{recursive:true});await fs.writeFile(dkdPath,JSON.stringify(dkdValue,null,2)+'\n','utf8');}
function dkdText(dkdValue){if(dkdValue==null)return '';if(typeof dkdValue==='string'||typeof dkdValue==='number')return String(dkdValue);if(typeof dkdValue==='object')return String(dkdValue['#text']??dkdValue.__cdata??dkdValue['@_href']??'');return '';}
function dkdStrip(dkdValue=''){return String(dkdValue).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\s+/g,' ').trim();}
function dkdNormalize(dkdValue=''){return dkdStrip(dkdValue).toLocaleLowerCase('tr').normalize('NFKD').replace(/[^a-z0-9çğıöşü\s]/gi,' ').replace(/\s+/g,' ').trim();}
function dkdId(dkdUrl,dkdTitle){return crypto.createHash('sha1').update(`${dkdUrl}|${dkdTitle}`).digest('hex').slice(0,14);}
function dkdGetLink(dkdEntry){const dkdLink=dkdEntry?.link;if(typeof dkdLink==='string')return dkdLink.trim();if(Array.isArray(dkdLink)){const dkdItem=dkdLink.find(dkdValue=>!dkdValue?.['@_rel']||dkdValue?.['@_rel']==='alternate')||dkdLink[0];return dkdText(dkdItem).trim();}return dkdText(dkdLink).trim()||dkdText(dkdEntry?.guid).trim();}
function dkdGetDate(dkdEntry){const dkdRaw=dkdText(dkdEntry?.pubDate)||dkdText(dkdEntry?.published)||dkdText(dkdEntry?.updated)||dkdText(dkdEntry?.['dc:date']);const dkdValue=Date.parse(dkdRaw);return Number.isFinite(dkdValue)?new Date(dkdValue).toISOString():new Date().toISOString();}
function dkdCategory(dkdTitle,dkdSummary,dkdDefault){const dkdTextValue=dkdNormalize(`${dkdTitle} ${dkdSummary}`);if(/\b(ai|artificial intelligence|yapay zeka|openai|anthropic|gemini|claude|copilot|llm)\b/.test(dkdTextValue))return ['Yapay Zeka','🧠'];if(/\b(gpu|cpu|chip|processor|nvidia|amd|intel|snapdragon|geforce|radeon|hardware)\b/.test(dkdTextValue))return ['Donanım','🧩'];if(/\b(iphone|ipad|ios|android|pixel|galaxy|smartphone|mobile)\b/.test(dkdTextValue))return ['Mobil','📱'];if(/\b(game|gaming|playstation|ps5|xbox|nintendo|switch|steam|game pass)\b/.test(dkdTextValue))return ['Oyun','🎮'];return [dkdDefault||'Teknoloji',dkdDefault==='Oyun'?'🎮':'⚡'];}
function dkdScore(dkdItem,dkdSource){const dkdAge=Math.max(0,(dkdNow-new Date(dkdItem.publishedAt).getTime())/36e5);const dkdFresh=Math.max(0,26-Math.min(26,dkdAge/4));const dkdHaystack=dkdNormalize(`${dkdItem.title} ${dkdItem.rawSummary}`);const dkdSignals=['launch','release','announced','acquisition','security','breach','price','update','major','console','gpu','ai','duyurdu','çıktı','güncelleme','fiyat'];const dkdSignal=Math.min(18,dkdSignals.reduce((dkdTotal,dkdValue)=>dkdTotal+(dkdHaystack.includes(dkdValue)?3:0),0));return Math.min(100,Math.round((Number(dkdSource.weight)||80)*.54+dkdFresh+dkdSignal+(dkdSource.type==='official'?7:0)));}
function dkdTokens(dkdTitle){return new Set(dkdNormalize(dkdTitle).split(' ').filter(dkdValue=>dkdValue.length>3));}
function dkdSimilar(dkdA,dkdB){const dkdOne=dkdTokens(dkdA),dkdTwo=dkdTokens(dkdB);if(!dkdOne.size||!dkdTwo.size)return 0;let dkdIntersection=0;for(const dkdToken of dkdOne)if(dkdTwo.has(dkdToken))dkdIntersection++;return dkdIntersection/(dkdOne.size+dkdTwo.size-dkdIntersection);}
function dkdDedupe(dkdItems){const dkdResult=[];for(const dkdItem of dkdItems){if(dkdResult.some(dkdExisting=>dkdExisting.url===dkdItem.url||dkdSimilar(dkdExisting.title,dkdItem.title)>.76))continue;dkdResult.push(dkdItem);}return dkdResult;}
async function dkdFetchSource(dkdSource){const dkdController=new AbortController();const dkdTimer=setTimeout(()=>dkdController.abort(),18000);try{const dkdResponse=await fetch(dkdSource.url,{headers:{'user-agent':'DraBornNews/0.1','accept':'application/rss+xml, application/atom+xml, application/xml, text/xml;q=0.9,*/*;q=0.5'},signal:dkdController.signal});if(!dkdResponse.ok)throw new Error(`HTTP ${dkdResponse.status}`);const dkdData=dkdParser.parse(await dkdResponse.text());const dkdEntries=dkdArray(dkdData?.rss?.channel?.item||dkdData?.feed?.entry||dkdData?.['rdf:RDF']?.item);return dkdEntries.slice(0,35).map(dkdEntry=>{const dkdTitle=dkdStrip(dkdText(dkdEntry?.title));const dkdUrl=dkdGetLink(dkdEntry);const dkdRawSummary=dkdStrip(dkdText(dkdEntry?.description)||dkdText(dkdEntry?.summary)||dkdText(dkdEntry?.['content:encoded'])||dkdText(dkdEntry?.content));const dkdPublishedAt=dkdGetDate(dkdEntry);const [dkdCategoryName,dkdIcon]=dkdCategory(dkdTitle,dkdRawSummary,dkdSource.category);const dkdBase={id:dkdId(dkdUrl,dkdTitle),title:dkdTitle,url:dkdUrl,publishedAt:dkdPublishedAt,source:dkdSource.name,sourceType:dkdSource.type,category:dkdCategoryName,icon:dkdIcon,rawSummary:dkdRawSummary};return {...dkdBase,score:dkdScore(dkdBase,dkdSource)};}).filter(dkdItem=>dkdItem.title&&/^https?:\/\//.test(dkdItem.url));}catch(dkdError){console.warn(`[source skipped] ${dkdSource.name}: ${dkdError.message}`);return [];}finally{clearTimeout(dkdTimer);}}
function dkdFallback(dkdItem){const dkdSummary=(dkdItem.rawSummary||'').slice(0,430);return {...dkdItem,summary:dkdSummary||`${dkdItem.source} tarafından yayımlanan yeni gelişme. Ayrıntılar için orijinal kaynağı açın.`,bullets:[],whyItMatters:'Ayrıntıları ve bağlamı doğrulamak için orijinal kaynağı inceleyin.',tags:[]};}
function dkdOutputText(dkdResponse){if(typeof dkdResponse?.output_text==='string')return dkdResponse.output_text;return dkdArray(dkdResponse?.output).flatMap(dkdPart=>dkdArray(dkdPart?.content)).map(dkdPart=>dkdPart?.text||'').filter(Boolean).join('\n');}
async function dkdRewrite(dkdItem){if(!process.env.OPENAI_API_KEY)return dkdFallback(dkdItem);const dkdPrompt=`DraBornNews editörüsün. YALNIZCA verilen kaynak başlığı ve RSS özetinden Türkçe, kısa, tarafsız ve özgün bir haber özeti üret. Asla yeni bilgi uydurma. JSON dışında hiçbir şey yazma. Alanlar: title, summary, bullets (2-3), whyItMatters, tags (3-5).\nKaynak: ${dkdItem.source}\nBaşlık: ${dkdItem.title}\nRSS özeti: ${dkdItem.rawSummary||'(yok)'}\nURL: ${dkdItem.url}`;try{const dkdResponse=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-6-luna',input:dkdPrompt,max_output_tokens:700})});if(!dkdResponse.ok)throw new Error(`OpenAI HTTP ${dkdResponse.status}`);const dkdRaw=dkdOutputText(await dkdResponse.json()).trim().replace(/^```json\s*/i,'').replace(/```$/,'').trim();const dkdJson=JSON.parse(dkdRaw);return {...dkdItem,title:String(dkdJson.title||dkdItem.title).slice(0,140),summary:String(dkdJson.summary||'').slice(0,520),bullets:dkdArray(dkdJson.bullets).slice(0,3).map(String),whyItMatters:String(dkdJson.whyItMatters||'').slice(0,420),tags:dkdArray(dkdJson.tags).slice(0,6).map(dkdTag=>String(dkdTag).replace(/^#/,'').slice(0,30))};}catch(dkdError){console.warn(`[ai fallback] ${dkdItem.title}: ${dkdError.message}`);return dkdFallback(dkdItem);}}
function dkdXmlEscape(dkdValue=''){return String(dkdValue).replace(/[&<>"']/g,dkdChar=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[dkdChar]));}
function dkdWrap(dkdTextValue){const dkdWords=String(dkdTextValue).split(/\s+/),dkdLines=[];let dkdLine='';for(const dkdWord of dkdWords){const dkdNext=`${dkdLine} ${dkdWord}`.trim();if(dkdNext.length>31&&dkdLine){dkdLines.push(dkdLine);dkdLine=dkdWord;if(dkdLines.length===3)break;}else dkdLine=dkdNext;}if(dkdLine&&dkdLines.length<4)dkdLines.push(dkdLine);return dkdLines;}
async function dkdCard(dkdItem){await fs.mkdir(path.dirname(dkdPaths.socialImage),{recursive:true});const dkdLines=dkdWrap(dkdItem.title).map((dkdLine,dkdIndex)=>`<text x="82" y="${285+dkdIndex*86}" font-size="66" font-weight="800" fill="#f8fbff" font-family="Arial">${dkdXmlEscape(dkdLine)}</text>`).join('');const dkdSvg=`<svg width="1080" height="1350" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="b"><stop stop-color="#07111d"/><stop offset=".55" stop-color="#12152d"/><stop offset="1" stop-color="#201126"/></linearGradient></defs><rect width="1080" height="1350" fill="url(#b)"/><text x="82" y="100" font-size="28" font-weight="800" fill="#4fe7ff" font-family="Arial">${dkdXmlEscape(dkdItem.category.toUpperCase())} • HABER RADARI</text>${dkdLines}<rect x="82" y="1020" width="916" height="1" fill="#fff" opacity=".15"/><text x="82" y="1095" font-size="30" fill="#aebbd0" font-family="Arial">Kaynak: ${dkdXmlEscape(dkdItem.source)}</text><text x="82" y="1198" font-size="42" font-weight="900" fill="#fff" font-family="Arial">DraBornNews</text><text x="82" y="1246" font-size="24" fill="#8190aa" font-family="Arial">OYUN • TEKNOLOJİ • YAPAY ZEKA</text></svg>`;await sharp(Buffer.from(dkdSvg)).png().toFile(dkdPaths.socialImage);}
async function dkdUpdate(){const dkdConfig=await dkdReadJson(dkdPaths.sources,{sources:[]});const dkdExisting=await dkdReadJson(dkdPaths.news,{items:[]});const dkdCollected=(await Promise.all(dkdConfig.sources.map(dkdFetchSource))).flat();const dkdFresh=dkdCollected.filter(dkdItem=>dkdNow-new Date(dkdItem.publishedAt).getTime()<432000000).sort((dkdA,dkdB)=>dkdB.score-dkdA.score);const dkdUnique=dkdDedupe(dkdFresh);const dkdExistingIds=new Set(dkdArray(dkdExisting.items).map(dkdItem=>dkdItem.id));const dkdNew=dkdUnique.filter(dkdItem=>!dkdExistingIds.has(dkdItem.id)).slice(0,Number(process.env.MAX_NEW_ARTICLES||10));console.log(`[update] ${dkdCollected.length} aday, ${dkdUnique.length} benzersiz, ${dkdNew.length} yeni`);const dkdRewritten=[];for(const dkdItem of dkdNew)dkdRewritten.push(await dkdRewrite(dkdItem));const dkdMerged=dkdDedupe([...dkdRewritten,...dkdArray(dkdExisting.items)]).sort((dkdA,dkdB)=>new Date(dkdB.publishedAt)-new Date(dkdA.publishedAt)).slice(0,160).map(({rawSummary,...dkdItem})=>dkdItem);await dkdWriteJson(dkdPaths.news,{generatedAt:new Date().toISOString(),items:dkdMerged});const dkdTop=[...dkdMerged].sort((dkdA,dkdB)=>dkdB.score-dkdA.score)[0];if(dkdTop)await dkdCard(dkdTop);}
if(dkdCommand==='update')await dkdUpdate();else if(dkdCommand==='publish'){const {dkdPublish}=await import('./social-publishers.mjs');await dkdPublish({root:dkdRoot,paths:dkdPaths});}else throw new Error(`Bilinmeyen komut: ${dkdCommand}`);
