const SUPABASE_URL='https://xpdiwyxnnrmyvpcqwuyb.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_cu71JQGPiRusMw_YeZzUbg_6r9r13TG';
const CONTACT_URL=`${SUPABASE_URL}/functions/v1/drabornpark-public-contact`;
const REQUEST_URL=`${SUPABASE_URL}/functions/v1/drabornpark-public-request`;
const DELETE_URL=`${SUPABASE_URL}/functions/v1/drabornpark-account-delete`;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url,body,headers={}){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||'request_failed');e.status=r.status;e.data=d;throw e}return d}

const TEST1_DATA={
  snapshot:{vehicle:{name:'Volkswagen Tiguan Demo',brand:'Volkswagen',model:'Tiguan',plate:'06 DBP 2026',color:'Gece Mavisi'}},
  categories:[
    {key:'exit_blocked',title:'Aracınız çıkışımı engelliyor',body:'Aracınızın başka bir aracın çıkışını engellediği bildirilecek.',priority:'normal'},
    {key:'move_vehicle',title:'Aracınızı hareket ettirebilir misiniz?',body:'Araç sahibine aracı hareket ettirme isteği gönderilir.',priority:'normal'},
    {key:'lights_on',title:'Farlarınız açık olabilir',body:'Araç farlarının açık olabileceği bildirilecek.',priority:'normal'},
    {key:'window_open',title:'Camınız açık olabilir',body:'Araç camlarından birinin açık olabileceği bildirilecek.',priority:'normal'},
    {key:'damage',title:'Aracınıza zarar verilmiş olabilir',body:'Araçta olası hasar fark edildiği bildirilecek.',priority:'high'},
    {key:'child',title:'Araçta çocuk var',body:'Araçta çocuk bulunduğuna dair yüksek öncelikli bildirim gönderilir.',priority:'emergency'},
    {key:'animal',title:'Araçta hayvan var',body:'Araçta hayvan bulunduğuna dair yüksek öncelikli bildirim gönderilir.',priority:'emergency'},
    {key:'witness',title:'Bir olaya şahit oldum',body:'Ziyaretçi araçla ilgili bir olaya şahit olduğunu bildirebilir.',priority:'high'},
    {key:'other',title:'Başka bir mesaj',body:'Kısa bir açıklama DraBornPark güvenlik filtresinden geçirilerek iletilir.',priority:'normal'}
  ]
};

let tagCode='',selected=null,sessionToken=null,pollTimer=null,demoMode=false,demoMessages=[];
function priorityClass(p){return p==='emergency'?'emergency':p==='high'?'high':''}
function renderVehicle(data){const v=data.snapshot?.vehicle||{};$('#tag-loading')?.classList.add('hidden');$('#tag-app')?.classList.remove('hidden');$('#vehicle-name').textContent=v.name||[v.brand,v.model].filter(Boolean).join(' ')||'DraBornPark korumalı araç';$('#vehicle-meta').textContent=[v.plate,v.color].filter(Boolean).join(' • ')||'Araç bilgileri gizli';const grid=$('#categories');grid.innerHTML='';for(const c of data.categories||[]){const b=document.createElement('button');b.className=`category ${priorityClass(c.priority)}`;b.innerHTML=`<div class="category-title">${esc(c.title)}</div><div class="category-body">${esc(c.body)}</div>${c.priority==='emergency'?'<span class="tag">ACİL</span>':''}`;b.onclick=()=>{selected=c;document.querySelectorAll('.category').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#compose').classList.remove('hidden');$('#selected-title').textContent=c.title;$('#selected-body').textContent=c.body};grid.appendChild(b)}}
function renderDemoChat(){const box=$('#chat-messages');if(!box)return;box.innerHTML=demoMessages.map(m=>`<div class="bubble ${m.role==='owner'?'owner':'visitor'}"><strong>${m.role==='owner'?'ARAÇ SAHİBİ':'SİZ'}</strong><div>${esc(m.body)}</div><small>${m.time}</small></div>`).join('')||'<div class="loading">Araç sahibinin cevabı bekleniyor…</div>'}
async function loadTag(){const raw=new URLSearchParams(location.search).get('tag');if(!raw)return;$('#landing')?.classList.add('hidden');$('#tag-shell')?.classList.remove('hidden');if(raw.trim().toLowerCase()==='test1'){demoMode=true;tagCode='DP-TEST1';document.title='DraBornPark — Test1 NFC / QR Demo';renderVehicle(TEST1_DATA);$('#notify-msg').innerHTML='<div class="message ok">Test1 canlı web demosu açık. Bu sayfadaki işlemler gerçek araç sahibine bildirim göndermez.</div>';return}tagCode=`DP-${raw.toUpperCase().replace(/^DP-/,'').replace(/[^A-Z0-9]/g,'')}`;try{renderVehicle(await api(CONTACT_URL,{action:'lookup',tagCode}))}catch{$('#tag-loading').innerHTML='<div class="message error">Bu DraBornPark etiketi bulunamadı veya şu anda kullanılamıyor.</div>'}}
async function notifyOwner(){if(!selected)return;const btn=$('#notify-btn');btn.disabled=true;$('#notify-msg').innerHTML='';if(demoMode){const note=$('#visitor-message').value.trim();sessionToken='TEST1-DEMO';demoMessages=[{role:'visitor',body:`${selected.title}${note?` — ${note}`:''}`,time:new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}];$('#compose').classList.add('hidden');$('#categories-wrap').classList.add('hidden');$('#chat-wrap').classList.remove('hidden');$('#notify-msg').innerHTML='<div class="message ok">Demo bildirim araç sahibine iletilmiş gibi gösterildi. Gerçek kullanıcı verisi değiştirilmedi.</div>';renderDemoChat();setTimeout(()=>{demoMessages.push({role:'owner',body:'5 dakika içinde geliyorum. Teşekkür ederim.',time:new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})});renderDemoChat()},900);btn.disabled=false;return}try{const d=await api(CONTACT_URL,{action:'notify',tagCode,category:selected.key,message:$('#visitor-message').value});sessionToken=d.sessionToken;$('#compose').classList.add('hidden');$('#categories-wrap').classList.add('hidden');$('#chat-wrap').classList.remove('hidden');$('#notify-msg').innerHTML='<div class="message ok">Bildirim araç sahibine güvenli şekilde iletildi.</div>';startPoll()}catch(e){$('#notify-msg').innerHTML=`<div class="message error">${e.status===429?'Çok fazla istek gönderildi. Lütfen daha sonra tekrar deneyin.':'Bildirim gönderilemedi. Lütfen tekrar deneyin.'}</div>`}finally{btn.disabled=false}}
async function poll(){if(!sessionToken||demoMode)return;try{const d=await api(CONTACT_URL,{action:'status',sessionToken});const box=$('#chat-messages');box.innerHTML=(d.messages||[]).map(m=>`<div class="bubble ${m.sender_role==='owner'?'owner':'visitor'}"><strong>${m.sender_role==='owner'?'ARAÇ SAHİBİ':'SİZ'}</strong><div>${esc(m.body_safe)}</div><small>${new Date(m.created_at).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')||'<div class="loading">Araç sahibinin cevabı bekleniyor…</div>'}catch(e){if(e.status===410){clearInterval(pollTimer);$('#chat-messages').innerHTML='<div class="message error">Geçici iletişim oturumu sona erdi.</div>'}}}
function startPoll(){poll();pollTimer=setInterval(poll,4000)}
async function sendChat(){const input=$('#chat-input');if(!input.value.trim())return;if(demoMode){demoMessages.push({role:'visitor',body:input.value.trim(),time:new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})});input.value='';renderDemoChat();setTimeout(()=>{demoMessages.push({role:'owner',body:'Mesajınızı gördüm, teşekkür ederim.',time:new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})});renderDemoChat()},650);return}try{await api(CONTACT_URL,{action:'chat',sessionToken,message:input.value});input.value='';await poll()}catch{$('#chat-error').textContent='Mesaj gönderilemedi.'}}

async function webDeleteLogin(ev){ev.preventDefault();const status=$('#delete-status');status.innerHTML='';const email=$('#delete-email').value.trim(),password=$('#delete-password').value;try{const auth=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:PUBLISHABLE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const session=await auth.json();if(!auth.ok||!session.access_token)throw new Error('Giriş bilgileri doğrulanamadı.');if(!confirm('DraBornPark hesabı ve hesaba bağlı kullanıcı verileri kalıcı olarak silinecek. Bu işlem geri alınamaz. Devam edilsin mi?'))return;await api(DELETE_URL,{confirm:true},{apikey:PUBLISHABLE_KEY,Authorization:`Bearer ${session.access_token}`});status.innerHTML='<div class="message ok">Hesabınız ve hesaba bağlı DraBornPark kullanıcı verileri kalıcı olarak silindi.</div>';ev.target.reset()}catch(e){status.innerHTML=`<div class="message error">${esc(e.message||'Silme işlemi tamamlanamadı.')}</div>`}}
async function deletionRequest(ev){ev.preventDefault();const status=$('#request-status');try{await api(REQUEST_URL,{action:'account_deletion_request',email:$('#request-email').value,reason:$('#request-reason').value});status.innerHTML='<div class="message ok">Hesap silme talebiniz alındı.</div>';ev.target.reset()}catch(e){status.innerHTML='<div class="message error">Talep gönderilemedi. Lütfen daha sonra tekrar deneyin.</div>'}}
async function supportRequest(ev){ev.preventDefault();const status=$('#support-status');try{await api(REQUEST_URL,{action:'support',email:$('#support-email').value,subject:$('#support-subject').value,body:$('#support-body').value});status.innerHTML='<div class="message ok">Destek talebiniz alındı.</div>';ev.target.reset()}catch{status.innerHTML='<div class="message error">Talep gönderilemedi. Lütfen daha sonra tekrar deneyin.</div>'}}

document.addEventListener('DOMContentLoaded',()=>{loadTag();$('#notify-btn')?.addEventListener('click',notifyOwner);$('#chat-send')?.addEventListener('click',sendChat);$('#delete-login-form')?.addEventListener('submit',webDeleteLogin);$('#delete-request-form')?.addEventListener('submit',deletionRequest);$('#support-form')?.addEventListener('submit',supportRequest)});
