/* DraBornPark production contact UI v0.5.1 — Remix Icon + live multi-message chat. */
(function(){
  const rawTag=(new URLSearchParams(location.search).get('tag')||'').trim();
  if(!rawTag)return;

  const CONTACT_URL='https://xpdiwyxnnrmyvpcqwuyb.supabase.co/functions/v1/drabornpark-public-contact';
  const iconMap={
    blocking_exit:['cyan','ri-car-line','PARK / GEÇİŞ'],blocked_exit:['cyan','ri-car-line','PARK / GEÇİŞ'],move_vehicle:['blue','ri-car-line','KISA İSTEK'],
    lights_on:['yellow','ri-lightbulb-line','ARAÇ UYARISI'],window_open:['aqua','ri-shield-check-line','GÜVENLİK'],door_open:['orange','ri-alert-line','YÜKSEK ÖNCELİK'],
    trunk_open:['orange','ri-alert-line','YÜKSEK ÖNCELİK'],damage:['pink','ri-error-warning-line','YÜKSEK ÖNCELİK'],suspicious:['purple','ri-eye-line','GÜVENLİK'],
    towing:['red','ri-alarm-warning-line','ACİL DURUM'],child:['red','ri-user-heart-line','ACİL DURUM'],animal:['red','ri-alarm-warning-line','ACİL DURUM'],fire:['red','ri-fire-line','ACİL DURUM'],
    forgotten_item:['yellow','ri-key-2-line','HATIRLATMA'],witness:['purple','ri-eye-line','TANIK'],emergency:['red','ri-alarm-warning-line','ACİL DURUM'],other:['blue','ri-message-3-line','MESAJ']
  };
  const state={snapshot:null,categories:[],selected:null,sessionToken:null,reportId:null,messages:[],poller:null,sending:false,chatSending:false};
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const clock=value=>new Date(value||Date.now()).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'});
  const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const SECURITY='<i class="ri-shield-check-line" aria-hidden="true"></i>';
  const CAR='<i class="ri-car-line" aria-hidden="true"></i>';

  async function api(payload){
    const response=await fetch(CONTACT_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
    let data=null;try{data=await response.json()}catch{}
    if(!response.ok){
      const code=data?.error||'request_failed';
      const map={tag_not_found:'Etiket bulunamadı.',tag_not_available:'Bu etiket şu anda bildirim kabul etmiyor.',rate_limited:'Çok fazla istek gönderildi. Lütfen biraz sonra tekrar deneyin.',session_closed:'Güvenli iletişim oturumu sona erdi.',session_not_found:'İletişim oturumu bulunamadı.',request_failed:'İstek işlenemedi. Lütfen tekrar deneyin.'};
      throw new Error(map[code]||'İşlem tamamlanamadı.');
    }
    return data;
  }

  function installStyles(){
    if(document.getElementById('dbp-v051-remix'))return;
    const style=document.createElement('style');style.id='dbp-v051-remix';style.textContent=`
      .dbp47-icon{display:grid!important;place-items:center!important;overflow:hidden!important}.dbp47-icon>i{font-size:34px;line-height:1;color:currentColor}
      .dbp47-lock,.dbp47-success-icon,.dbp47-safe-row>span,.dbp47-send>span{display:grid!important;place-items:center!important}.dbp47-lock>i,.dbp47-success-icon>i{font-size:34px}.dbp47-safe-row>span>i,.dbp47-send>span>i{font-size:28px}
      .dbp47-car{display:grid!important;place-items:center!important}.dbp47-car>i{font-size:42px;color:#2addff}.dbp47-car>span{display:none!important}
      .dbp47-brandmark{display:grid;place-items:center}.dbp47-chat-head span i{display:inline-block}
      .dbp47-send[disabled],.dbp47-chat-input button[disabled]{opacity:.5;pointer-events:none}.dbp47-inline-error{margin-top:12px;color:#ff7c9e;font-weight:800}
      .dbp47-chat-input button i{font-size:20px}.dbp47-again i{margin-right:8px}.dbp47-demo i{display:inline-block}
      .dbp47-messages{scroll-behavior:smooth}.dbp47-bubble.is-pending{opacity:.68}
    `;document.head.appendChild(style);
  }

  function cardMarkup(c){
    const [tone,icon,label]=iconMap[c.key]||['blue','ri-message-3-line','BİLDİRİM'];
    return `<button class="dbp47-choice tone-${tone}" type="button" data-key="${esc(c.key)}" aria-pressed="false"><span class="dbp47-choice-rail"></span><span class="dbp47-choice-top"><span class="dbp47-icon"><i class="${icon}" aria-hidden="true"></i></span><span class="dbp47-select-hint"><i></i> DOKUN • SEÇ</span></span><span class="dbp47-priority">${label}</span><strong>${esc(c.title)}</strong><small>${esc(c.body)}</small><span class="dbp47-selected-label">SEÇİLDİ <b>✓</b></span></button>`;
  }
  function vehicleText(){const v=state.snapshot?.vehicle||{};const name=v.name||[v.brand,v.model].filter(Boolean).join(' ')||'DraBornPark aracı';const plate=v.plate||'Plaka gizli';const detail=[v.color,v.brand&&v.model?`${v.brand} ${v.model}`:null].filter(Boolean).join(' • ');return{name,plate,detail};}
  function tagLabel(){return state.snapshot?.publicAlias?`ETİKET • ${state.snapshot.publicAlias}`:`ETİKET • ${state.snapshot?.tagCode||rawTag}`;}
  function shellMarkup(){const v=vehicleText();return `<div class="dbp47-app"><div class="dbp47-ambient dbp47-a1"></div><div class="dbp47-ambient dbp47-a2"></div>
    <header class="dbp47-top"><a href="./" class="dbp47-brand"><span class="dbp47-brandmark">DP</span><span><b>DraBornPark</b><small>GÜVENLİ ARAÇ İLETİŞİMİ</small></span></a><span class="dbp47-demo"><i></i> NFC + QR • AKTİF</span></header>
    <section class="dbp47-vehicle"><div class="dbp47-vehicle-main"><div class="dbp47-car">${CAR}</div><div class="dbp47-vehicle-copy"><span class="dbp47-kicker">DRABORNPARK KORUMALI ARAÇ</span><h1>${esc(v.name)}</h1><p><b>${esc(v.plate)}</b>${v.detail?`<i>•</i>${esc(v.detail)}`:''}</p></div></div><div class="dbp47-vehicle-status"><span>${SECURITY}<b>KORUMALI</b></span><span class="dbp47-tag">${esc(tagLabel())}</span></div></section>
    <section class="dbp47-privacy"><span class="dbp47-lock">${SECURITY}</span><div><span class="dbp47-kicker">GİZLİLİK AKTİF</span><h2>Telefon numarası gizlidir.</h2><p>Telefon, e-posta ve açık kimlik bilgileri gösterilmez. Bildiriminiz DraBornPark üzerinden güvenli biçimde iletilir.</p></div></section>
    <section class="dbp47-flow"><div class="is-current"><b>1</b><span>Durumu seç</span></div><i></i><div><b>2</b><span>Kısa açıklama</span></div><i></i><div><b>3</b><span>Güvenli gönder</span></div></section>
    <section id="dbp47-choose" class="dbp47-section"><div class="dbp47-heading"><span class="dbp47-kicker">1 • BİLDİRİM TÜRÜ</span><h2>Ne bildirmek istiyorsunuz?</h2><p>Araca en uygun durumu seçin. Acil durumlar yüksek öncelikle işaretlenir.</p></div><div class="dbp47-grid">${state.categories.map(cardMarkup).join('')}</div></section>
    <section id="dbp47-compose" class="dbp47-compose" hidden><div class="dbp47-compose-head"><div><span class="dbp47-kicker">2 • SEÇİLEN BİLDİRİM</span><h2 id="dbp47-selected-title"></h2><p id="dbp47-selected-body"></p></div><button id="dbp47-change" type="button">DEĞİŞTİR</button></div><label for="dbp47-message">İsteğe bağlı kısa açıklama</label><textarea id="dbp47-message" maxlength="700" placeholder="Örn. Sağ ön cam yaklaşık 2 cm açık görünüyor…"></textarea><div class="dbp47-safe-row"><span>${SECURITY}</span><p>Kişisel telefon/e-posta yazmanız gerekmez. Hassas içerikler güvenlik filtresinden geçirilir.</p></div><button id="dbp47-send" class="dbp47-send" type="button"><span>${SECURITY}</span><div><b>ARAÇ SAHİBİNE GÜVENLİ GÖNDER</b><small>Bildirim gerçek zamanlı olarak araç sahibine iletilir</small></div><em><i class="ri-send-plane-2-line"></i></em></button><div id="dbp47-send-error" class="dbp47-inline-error" hidden></div></section>
    <section id="dbp47-success" class="dbp47-success" hidden><div class="dbp47-success-icon">${SECURITY}</div><span class="dbp47-kicker">3 • BİLDİRİM İLETİLDİ</span><h2>Araç sahibine güvenli şekilde gönderildi.</h2><p>Telefon numaraları paylaşılmadan geçici anonim iletişim açıldı. İki tarafın yeni mesajları burada yaklaşık bir saniye içinde görünür.</p><div class="dbp47-chat"><div class="dbp47-chat-head"><div><b>Geçici anonim iletişim</b><small>Güvenli DraBornPark oturumu</small></div><span><i></i> AÇIK</span></div><div id="dbp47-messages" class="dbp47-messages"></div><div class="dbp47-chat-input"><input id="dbp47-chat-input" maxlength="700" autocomplete="off" placeholder="Kısa bir cevap yaz…"><button id="dbp47-chat-send" type="button"><i class="ri-send-plane-2-line"></i><span>GÖNDER</span></button></div><div id="dbp47-chat-error" class="dbp47-inline-error" hidden></div></div><button id="dbp47-again" class="dbp47-again" type="button"><i class="ri-arrow-left-line"></i>BAŞKA BİR DURUM BİLDİR</button></section>
    <footer class="dbp47-footer"><span>DraBornPark • DrabornEagle</span><nav><a href="./privacy/">Gizlilik</a><a href="./data-safety/">Veri Güvenliği</a><a href="./support/">Destek</a></nav></footer></div>`;}

  function syncFlow(step){document.querySelectorAll('.dbp47-flow div').forEach((x,i)=>x.classList.toggle('is-current',i===step-1));}
  function select(key){state.selected=state.categories.find(x=>x.key===key)||null;if(!state.selected)return;document.querySelectorAll('.dbp47-choice').forEach(btn=>{const active=btn.dataset.key===key;btn.classList.toggle('is-selected',active);btn.setAttribute('aria-pressed',String(active));const hint=btn.querySelector('.dbp47-select-hint');if(hint)hint.lastChild.textContent=active?' SEÇİLDİ':' DOKUN • SEÇ';});document.getElementById('dbp47-selected-title').textContent=state.selected.title;document.getElementById('dbp47-selected-body').textContent=state.selected.body;const compose=document.getElementById('dbp47-compose');compose.hidden=false;syncFlow(2);setTimeout(()=>compose.scrollIntoView({behavior:'smooth',block:'center'}),60);}
  function normalizeMessages(messages){const seen=new Set();return (messages||[]).filter(m=>m&&m.id&&!seen.has(m.id)&&seen.add(m.id));}
  function renderMessages(){const box=document.getElementById('dbp47-messages');if(!box)return;box.innerHTML=state.messages.map(m=>`<div class="dbp47-bubble ${m.sender_role==='owner'?'is-owner':'is-visitor'}"><span>${m.sender_role==='owner'?'ARAÇ SAHİBİ':'SİZ'}</span><p>${esc(m.body_safe)}</p><small>${clock(m.created_at)}</small></div>`).join('');box.scrollTop=box.scrollHeight;}
  async function refreshChat(){if(!state.sessionToken)return;try{const data=await api({action:'status',sessionToken:state.sessionToken});state.messages=normalizeMessages(data.messages||[]);renderMessages();}catch(e){const error=document.getElementById('dbp47-chat-error');if(error){error.textContent=e.message||'İletişim oturumu yenilenemedi.';error.hidden=false;}if(state.poller){clearInterval(state.poller);state.poller=null;}}}
  function startPolling(){if(state.poller)clearInterval(state.poller);state.poller=setInterval(()=>{if(document.visibilityState!=='hidden')void refreshChat();},1000);}
  async function send(){if(!state.selected||state.sending)return;const button=document.getElementById('dbp47-send');const error=document.getElementById('dbp47-send-error');state.sending=true;button.disabled=true;error.hidden=true;const title=button.querySelector('b');const original=title.textContent;title.textContent='GÖNDERİLİYOR…';try{const extra=document.getElementById('dbp47-message').value.trim();const data=await api({action:'notify',tagCode:rawTag,category:state.selected.key,message:extra||null,sessionKey:uid()});state.sessionToken=data.sessionToken;state.reportId=data.reportId;state.messages=data.initialMessage?[data.initialMessage]:[];document.getElementById('dbp47-choose').hidden=true;document.getElementById('dbp47-compose').hidden=true;document.getElementById('dbp47-success').hidden=false;syncFlow(3);renderMessages();await refreshChat();startPolling();document.getElementById('dbp47-success').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){error.textContent=e.message||'Bildirim gönderilemedi.';error.hidden=false;}finally{state.sending=false;button.disabled=false;title.textContent=original;}}
  async function chat(){const input=document.getElementById('dbp47-chat-input');const button=document.getElementById('dbp47-chat-send');const error=document.getElementById('dbp47-chat-error');const text=input.value.trim();if(!text||!state.sessionToken||state.chatSending)return;state.chatSending=true;button.disabled=true;error.hidden=true;try{const data=await api({action:'chat',sessionToken:state.sessionToken,message:text});input.value='';if(data.message){state.messages=normalizeMessages([...state.messages,data.message]);renderMessages();}await refreshChat();input.focus();}catch(e){error.textContent=e.message||'Mesaj gönderilemedi.';error.hidden=false;}finally{state.chatSending=false;button.disabled=false;}}
  function reset(){state.selected=null;state.sessionToken=null;state.reportId=null;state.messages=[];if(state.poller){clearInterval(state.poller);state.poller=null;}document.getElementById('dbp47-success').hidden=true;document.getElementById('dbp47-compose').hidden=true;document.getElementById('dbp47-choose').hidden=false;document.getElementById('dbp47-message').value='';document.querySelectorAll('.dbp47-choice').forEach(btn=>{btn.classList.remove('is-selected');btn.setAttribute('aria-pressed','false');const hint=btn.querySelector('.dbp47-select-hint');if(hint)hint.lastChild.textContent=' DOKUN • SEÇ';});syncFlow(1);document.getElementById('dbp47-choose').scrollIntoView({behavior:'smooth',block:'start'});}
  function bind(){document.querySelectorAll('.dbp47-choice').forEach(btn=>btn.addEventListener('click',()=>select(btn.dataset.key)));document.getElementById('dbp47-change').addEventListener('click',()=>document.getElementById('dbp47-choose').scrollIntoView({behavior:'smooth'}));document.getElementById('dbp47-send').addEventListener('click',send);document.getElementById('dbp47-chat-send').addEventListener('click',chat);document.getElementById('dbp47-chat-input').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void chat();}});document.getElementById('dbp47-again').addEventListener('click',reset);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&state.sessionToken)void refreshChat();});}
  async function boot(){installStyles();const landing=document.getElementById('landing');const shell=document.getElementById('tag-shell');if(landing)landing.classList.add('hidden');shell.classList.remove('hidden');shell.innerHTML='<div class="dbp-production-loading"><div class="dbp-production-spinner"></div><b>Güvenli araç bağlantısı hazırlanıyor</b><span>Etiket ve araç bilgileri doğrulanıyor…</span></div>';try{const data=await api({action:'lookup',tagCode:rawTag});state.snapshot=data.snapshot;state.categories=data.categories||[];shell.innerHTML=shellMarkup();bind();}catch(e){shell.innerHTML=`<div class="dbp-production-error"><i class="ri-error-warning-line" style="font-size:42px;color:#ff6b8a"></i><b>Etiket açılamadı</b><span>${esc(e.message||'DraBornPark bağlantısı doğrulanamadı.')}</span></div>`;}}
  void boot();
})();
