/* DraBornPark production contact UI v0.5.1 — premium Test1 visual language, live Supabase data. */
(function(){
  const rawTag=(new URLSearchParams(location.search).get('tag')||'').trim();
  if(!rawTag)return;

  const CONTACT_URL='https://xpdiwyxnnrmyvpcqwuyb.supabase.co/functions/v1/drabornpark-public-contact';
  const toneMap={
    blocking_exit:['cyan','blocking','PARK / GEÇİŞ'],blocked_exit:['cyan','blocking','PARK / GEÇİŞ'],move_vehicle:['blue','blocking','KISA İSTEK'],
    lights_on:['yellow','lights','ARAÇ UYARISI'],window_open:['aqua','window','GÜVENLİK'],door_open:['orange','window','YÜKSEK ÖNCELİK'],
    trunk_open:['orange','window','YÜKSEK ÖNCELİK'],damage:['pink','damage','YÜKSEK ÖNCELİK'],suspicious:['purple','witness','GÜVENLİK'],
    towing:['red','blocking','ACİL DURUM'],child:['red','child','ACİL DURUM'],animal:['red','animal','ACİL DURUM'],fire:['red','lights','ACİL DURUM'],
    forgotten_item:['yellow','other','HATIRLATMA'],witness:['purple','witness','TANIK'],emergency:['red','child','ACİL DURUM'],other:['blue','other','MESAJ']
  };
  const SECURITY='<img class="dbp49-security-raster" src="./assets/test1-privacy-icon-v049.webp" alt="" aria-hidden="true">';
  const CAR='<span class="dbp48-raster dbp48-i-blocking dbp49-car-raster" aria-hidden="true"></span>';
  const state={snapshot:null,categories:[],selected:null,sessionToken:null,reportId:null,messages:[],poller:null,sending:false};
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const clock=value=>new Date(value||Date.now()).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'});

  async function api(payload){
    const response=await fetch(CONTACT_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
    let data=null;try{data=await response.json()}catch{}
    if(!response.ok){const code=data?.error||'request_failed';const map={tag_not_found:'Etiket bulunamadı.',tag_not_available:'Bu etiket şu anda bildirim kabul etmiyor.',rate_limited:'Çok fazla istek gönderildi. Lütfen biraz sonra tekrar deneyin.',session_closed:'Güvenli iletişim oturumu sona erdi.',request_failed:'İstek işlenemedi. Lütfen tekrar deneyin.'};throw new Error(map[code]||'İşlem tamamlanamadı.');}
    return data;
  }

  function installRasterIcons(){
    if(document.getElementById('dbp-production-raster-icons'))return;
    const style=document.createElement('style');style.id='dbp-production-raster-icons';style.textContent=`
      .dbp47-icon{padding:0!important;border:0!important;background:transparent!important;overflow:hidden!important}
      .dbp48-raster{display:block;width:54px;height:54px;border-radius:18px;background-image:url('./assets/test1-icons-v048.webp');background-repeat:no-repeat;background-size:216px 108px}
      .dbp48-i-blocking{background-position:0 0}.dbp48-i-lights{background-position:-54px 0}.dbp48-i-window{background-position:-108px 0}.dbp48-i-damage{background-position:-162px 0}
      .dbp48-i-child{background-position:0 -54px}.dbp48-i-animal{background-position:-54px -54px}.dbp48-i-witness{background-position:-108px -54px}.dbp48-i-other{background-position:-162px -54px}
      .dbp47-choice.is-selected .dbp48-raster{transform:scale(1.04)}.dbp49-security-raster{display:block;width:30px;height:30px;object-fit:cover;border-radius:10px}.dbp49-car-raster{width:54px;height:54px;border-radius:18px}
      .dbp-production-loading,.dbp-production-error{max-width:760px;margin:80px auto;padding:28px;border:1px solid rgba(42,221,255,.28);border-radius:28px;background:rgba(10,25,47,.92);color:#f7f8ff;text-align:center}
      .dbp-production-loading b,.dbp-production-error b{display:block;font-size:24px;margin-bottom:8px}.dbp-production-loading span,.dbp-production-error span{color:#a9b8d0;line-height:1.55}
      .dbp-production-spinner{width:48px;height:48px;margin:0 auto 18px;border:4px solid rgba(255,255,255,.12);border-top-color:#2addff;border-right-color:#a764ff;border-radius:50%;animation:dbpProdSpin 1s linear infinite}@keyframes dbpProdSpin{to{transform:rotate(360deg)}}
      .dbp47-send[disabled],.dbp47-chat-input button[disabled]{opacity:.55;pointer-events:none}.dbp47-inline-error{margin-top:12px;color:#ff7c9e;font-weight:800}.dbp47-success-note{margin-top:10px;color:#8fffd0;font-weight:800}
    `;document.head.appendChild(style);
  }

  function cardMarkup(c){const [tone,icon,label]=toneMap[c.key]||['blue','other','BİLDİRİM'];return `<button class="dbp47-choice tone-${tone}" type="button" data-key="${esc(c.key)}" aria-pressed="false"><span class="dbp47-choice-rail"></span><span class="dbp47-choice-top"><span class="dbp47-icon"><span class="dbp48-raster dbp48-i-${icon}" aria-hidden="true"></span></span><span class="dbp47-select-hint"><i></i> DOKUN • SEÇ</span></span><span class="dbp47-priority">${label}</span><strong>${esc(c.title)}</strong><small>${esc(c.body)}</small><span class="dbp47-selected-label">SEÇİLDİ <b>✓</b></span></button>`;}
  function vehicleText(){const v=state.snapshot?.vehicle||{};const name=v.name||[v.brand,v.model].filter(Boolean).join(' ')||'DraBornPark aracı';const plate=v.plate||'Plaka gizli';const detail=[v.color,v.brand&&v.model?`${v.brand} ${v.model}`:null].filter(Boolean).join(' • ');return {name,plate,detail};}
  function tagLabel(){return state.snapshot?.publicAlias?`ETİKET • ${state.snapshot.publicAlias}`:`ETİKET • ${state.snapshot?.tagCode||rawTag}`;}
  function shellMarkup(){const v=vehicleText();return `<div class="dbp47-app"><div class="dbp47-ambient dbp47-a1"></div><div class="dbp47-ambient dbp47-a2"></div>
    <header class="dbp47-top"><a href="./" class="dbp47-brand"><span class="dbp47-brandmark">DP</span><span><b>DraBornPark</b><small>GÜVENLİ ARAÇ İLETİŞİMİ</small></span></a><span class="dbp47-demo"><i></i> NFC + QR • AKTİF</span></header>
    <section class="dbp47-vehicle"><div class="dbp47-vehicle-main"><div class="dbp47-car">${CAR}<span></span></div><div class="dbp47-vehicle-copy"><span class="dbp47-kicker">DRABORNPARK KORUMALI ARAÇ</span><h1>${esc(v.name)}</h1><p><b>${esc(v.plate)}</b>${v.detail?`<i>•</i>${esc(v.detail)}`:''}</p></div></div><div class="dbp47-vehicle-status"><span>${SECURITY}<b>KORUMALI</b></span><span class="dbp47-tag">${esc(tagLabel())}</span></div></section>
    <section class="dbp47-privacy"><span class="dbp47-lock">${SECURITY}</span><div><span class="dbp47-kicker">GİZLİLİK AKTİF</span><h2>Telefon numarası gizlidir.</h2><p>Telefon, e-posta ve açık kimlik bilgileri gösterilmez. Bildiriminiz DraBornPark üzerinden güvenli biçimde iletilir.</p></div></section>
    <section class="dbp47-flow"><div class="is-current"><b>1</b><span>Durumu seç</span></div><i></i><div><b>2</b><span>Kısa açıklama</span></div><i></i><div><b>3</b><span>Güvenli gönder</span></div></section>
    <section id="dbp47-choose" class="dbp47-section"><div class="dbp47-heading"><span class="dbp47-kicker">1 • BİLDİRİM TÜRÜ</span><h2>Ne bildirmek istiyorsunuz?</h2><p>Araca en uygun durumu seçin. Acil durumlar yüksek öncelikle işaretlenir.</p></div><div class="dbp47-grid">${state.categories.map(cardMarkup).join('')}</div></section>
    <section id="dbp47-compose" class="dbp47-compose" hidden><div class="dbp47-compose-head"><div><span class="dbp47-kicker">2 • SEÇİLEN BİLDİRİM</span><h2 id="dbp47-selected-title"></h2><p id="dbp47-selected-body"></p></div><button id="dbp47-change" type="button">DEĞİŞTİR</button></div><label for="dbp47-message">İsteğe bağlı kısa açıklama</label><textarea id="dbp47-message" maxlength="700" placeholder="Örn. Sağ ön cam yaklaşık 2 cm açık görünüyor…"></textarea><div class="dbp47-safe-row"><span>${SECURITY}</span><p>Kişisel telefon/e-posta yazmanız gerekmez. Hassas içerikler güvenlik filtresinden geçirilir.</p></div><button id="dbp47-send" class="dbp47-send" type="button"><span>${SECURITY}</span><div><b>ARAÇ SAHİBİNE GÜVENLİ GÖNDER</b><small>Bildirim gerçek zamanlı olarak araç sahibine iletilir</small></div><em>→</em></button><div id="dbp47-send-error" class="dbp47-inline-error" hidden></div></section>
    <section id="dbp47-success" class="dbp47-success" hidden><div class="dbp47-success-icon">${SECURITY}</div><span class="dbp47-kicker">3 • BİLDİRİM İLETİLDİ</span><h2>Araç sahibine güvenli şekilde gönderildi.</h2><p>Telefon numaraları paylaşılmadan geçici anonim iletişim açıldı. Araç sahibi cevap verdiğinde burada görünür.</p><div class="dbp47-chat"><div class="dbp47-chat-head"><div><b>Geçici anonim iletişim</b><small>Güvenli DraBornPark oturumu</small></div><span><i></i> AÇIK</span></div><div id="dbp47-messages" class="dbp47-messages"></div><div class="dbp47-chat-input"><input id="dbp47-chat-input" maxlength="700" placeholder="Kısa bir cevap yaz…"><button id="dbp47-chat-send" type="button">GÖNDER</button></div><div id="dbp47-chat-error" class="dbp47-inline-error" hidden></div></div><button id="dbp47-again" class="dbp47-again" type="button">← BAŞKA BİR DURUM BİLDİR</button></section>
    <footer class="dbp47-footer"><span>DraBornPark • DrabornEagle</span><nav><a href="./privacy/">Gizlilik</a><a href="./data-safety/">Veri Güvenliği</a><a href="./support/">Destek</a></nav></footer></div>`;}

  function syncFlow(step){document.querySelectorAll('.dbp47-flow div').forEach((x,i)=>x.classList.toggle('is-current',i===step-1));}
  function select(key){state.selected=state.categories.find(x=>x.key===key)||null;if(!state.selected)return;document.querySelectorAll('.dbp47-choice').forEach(btn=>{const active=btn.dataset.key===key;btn.classList.toggle('is-selected',active);btn.setAttribute('aria-pressed',String(active));const hint=btn.querySelector('.dbp47-select-hint');if(hint)hint.lastChild.textContent=active?' SEÇİLDİ':' DOKUN • SEÇ';});document.getElementById('dbp47-selected-title').textContent=state.selected.title;document.getElementById('dbp47-selected-body').textContent=state.selected.body;const compose=document.getElementById('dbp47-compose');compose.hidden=false;syncFlow(2);setTimeout(()=>compose.scrollIntoView({behavior:'smooth',block:'center'}),80);}
  function renderMessages(){const box=document.getElementById('dbp47-messages');if(!box)return;box.innerHTML=state.messages.map(m=>`<div class="dbp47-bubble ${m.sender_role==='owner'?'is-owner':'is-visitor'}"><span>${m.sender_role==='owner'?'ARAÇ SAHİBİ':'SİZ'}</span><p>${esc(m.body_safe)}</p><small>${clock(m.created_at)}</small></div>`).join('');box.scrollTop=box.scrollHeight;}
  async function refreshChat(){if(!state.sessionToken)return;try{const data=await api({action:'status',sessionToken:state.sessionToken});state.messages=data.messages||[];renderMessages();}catch(e){if(state.poller){clearInterval(state.poller);state.poller=null;}}}
  async function send(){if(!state.selected||state.sending)return;const button=document.getElementById('dbp47-send');const error=document.getElementById('dbp47-send-error');state.sending=true;button.disabled=true;error.hidden=true;const original=button.querySelector('b').textContent;button.querySelector('b').textContent='GÖNDERİLİYOR…';try{const extra=document.getElementById('dbp47-message').value.trim();const data=await api({action:'notify',tagCode:rawTag,category:state.selected.key,message:extra||null,sessionKey:crypto.randomUUID?crypto.randomUUID():String(Date.now())});state.sessionToken=data.sessionToken;state.reportId=data.reportId;state.messages=[];document.getElementById('dbp47-choose').hidden=true;document.getElementById('dbp47-compose').hidden=true;document.getElementById('dbp47-success').hidden=false;syncFlow(3);await refreshChat();state.poller=setInterval(refreshChat,4000);document.getElementById('dbp47-success').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){error.textContent=e.message||'Bildirim gönderilemedi.';error.hidden=false;}finally{state.sending=false;button.disabled=false;button.querySelector('b').textContent=original;}}
  async function chat(){const input=document.getElementById('dbp47-chat-input');const button=document.getElementById('dbp47-chat-send');const error=document.getElementById('dbp47-chat-error');const text=input.value.trim();if(!text||!state.sessionToken)return;button.disabled=true;error.hidden=true;try{await api({action:'chat',sessionToken:state.sessionToken,message:text});input.value='';await refreshChat();}catch(e){error.textContent=e.message||'Mesaj gönderilemedi.';error.hidden=false;}finally{button.disabled=false;}}
  function reset(){state.selected=null;if(state.poller){clearInterval(state.poller);state.poller=null;}document.getElementById('dbp47-success').hidden=true;document.getElementById('dbp47-compose').hidden=true;document.getElementById('dbp47-choose').hidden=false;document.getElementById('dbp47-message').value='';document.querySelectorAll('.dbp47-choice').forEach(btn=>{btn.classList.remove('is-selected');btn.setAttribute('aria-pressed','false');const hint=btn.querySelector('.dbp47-select-hint');if(hint)hint.lastChild.textContent=' DOKUN • SEÇ';});syncFlow(1);window.scrollTo({top:0,behavior:'smooth'});}
  function bind(){document.querySelectorAll('.dbp47-choice').forEach(btn=>btn.addEventListener('click',()=>select(btn.dataset.key)));document.getElementById('dbp47-change')?.addEventListener('click',()=>{document.getElementById('dbp47-choose').scrollIntoView({behavior:'smooth',block:'start'});syncFlow(1)});document.getElementById('dbp47-send')?.addEventListener('click',send);document.getElementById('dbp47-chat-send')?.addEventListener('click',chat);document.getElementById('dbp47-chat-input')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();chat();}});document.getElementById('dbp47-again')?.addEventListener('click',reset);}
  async function boot(){installRasterIcons();document.body.classList.add('test1-v047','test1-v048');document.getElementById('landing')?.classList.add('hidden');const shell=document.getElementById('tag-shell');if(!shell)return;shell.classList.remove('hidden');shell.innerHTML='<div class="dbp-production-loading"><div class="dbp-production-spinner"></div><b>Etiket doğrulanıyor</b><span>DraBornPark güvenli araç ağına bağlanılıyor…</span></div>';try{const data=await api({action:'lookup',tagCode:rawTag});state.snapshot=data.snapshot;state.categories=data.categories||[];shell.innerHTML=shellMarkup();bind();}catch(e){shell.innerHTML=`<div class="dbp-production-error"><b>Etiket açılamadı</b><span>${esc(e.message||'Lütfen etiketi yeniden okutun.')}</span></div>`;}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();