DKD.ccOpen=false;DKD.ccPanel='';
DKD.ccItems=[['Home','home'],['Switcher','switcher'],['Notifications','bell'],['Game Base','friends'],['Music','music'],['Sound','sound'],['Mic','mic'],['Accessories','controller'],['Profile','profile'],['Power','power']];
DKD.toggleCC=()=>{if(DKD.powerState)return;if(DKD.ccOpen){DKD.closeCC();return;}DKD.closeModal();DKD.ccOpen=true;DKD.ccPanel='';DKD.ccWasRunning=DKD.route==='game'&&DKD.activeSession?.started&&!DKD.activeSession.paused&&!DKD.activeSession.over;DKD.activeSession?.pause();DKD.renderCC();document.querySelector('.cc-item[data-id="Home"]')?.focus({preventScroll:true});};
DKD.closeCC=(resume=true)=>{DKD.ccOpen=false;DKD.ccPanel='';document.getElementById('control-center').hidden=true;if(resume&&DKD.ccWasRunning&&DKD.route==='game')DKD.activeSession?.resume();DKD.ccWasRunning=false;};
DKD.renderCC=()=>{const container=document.getElementById('control-center');container.hidden=false;const active=DKD.activeSession?.game;const activities=active?[active,...DKD.catalog.filter(game=>game.installed&&game.id!==active.id)].slice(0,3):DKD.catalog.slice(0,3);container.innerHTML=`<div class="cc-overlay"><div class="cc-header"><span>${active?'Continue your adventure':'Activities'}</span><time class="clock"></time></div><div class="activity-row">${activities.map(game=>`<button class="activity-card" data-action="launch" data-id="${game.id}"><img src="${DKD.art(game.id)}" alt=""><div class="activity-info"><span class="tag">${game.title}</span><strong>${game.target}</strong><small>${DKD.sessions[game.id]?'Resume activity':'Start activity'} ${DKD.icon('arrow')}</small></div></button>`).join('')}<button class="activity-card" data-action="trophies" style="width:285px"><div class="activity-info">${DKD.icon('trophy')}<strong>Your next trophy awaits</strong><small>${DKD.state.trophies.length} trophies earned</small></div></button></div><nav class="cc-dock" aria-label="Control Center">${DKD.ccItems.map(([label,icon])=>`<button class="cc-item ${DKD.ccPanel===label?'active':''}" data-action="cc-item" data-id="${label}" aria-label="${label}">${DKD.icon(icon)}<span>${label}</span></button>`).join('')}</nav>${DKD.ccPanel?`<section class="cc-panel panel">${DKD.ccContent(DKD.ccPanel)}</section>`:''}</div>`;DKD.clock();};
DKD.ccContent=label=>{
 let content='';
 if(label==='Switcher')content=DKD.state.recent.length?DKD.state.recent.map(id=>`<button class="list-button" data-action="launch" data-id="${id}"><img src="${DKD.art(id)}" alt=""><span class="grow">${DKD.game(id).title}<small class="muted tiny" style="display:block;margin-top:7px">${DKD.sessions[id]?'Suspended · Resume':'Recently played'}</small></span>${DKD.icon('play')}</button>`).join(''):'<p>Your recently played games will appear here.</p>';
 if(label==='Notifications')content=DKD.state.notifications.length?DKD.state.notifications.slice(0,7).map(note=>`<div class="setting-row"><div><span>${DKD.escape(note.title)}</span><small>${DKD.escape(note.body)}</small></div>${DKD.icon('bell')}</div>`).join(''):'<p>You’re all caught up.</p>';
 if(label==='Game Base')content=`<p>Friends · Local demo profiles</p>${DKD.friends.map(friend=>`<button class="list-button" data-action="friend" data-id="${friend.name}">${DKD.avatar(friend.name,false,friend.color)}<span><strong style="font-weight:400">${friend.name}</strong><small class="muted tiny" style="display:block;margin-top:5px">Playing ${friend.game}</small></span></button>`).join('')}`;
 if(label==='Music')content=`<div class="row">${DKD.icon('music')}<div><h3 style="font-weight:300;margin:0">Blue hour</h3><p>Original console ambience</p></div></div><button class="pill primary" data-action="toggle-music">${DKD.icon(DKD.state.settings.music?'pause':'play')}${DKD.state.settings.music?'Pause':'Play'}</button>${DKD.rangeRow('Volume','volume')}`;
 if(label==='Sound')content=`${DKD.rangeRow('Master Volume','volume')}${DKD.toggleRow('Home Screen Music','music')}<p>Output: Browser audio</p><button class="list-button" data-action="sound-settings">Sound Settings ${DKD.icon('arrow')}</button>`;
 if(label==='Mic')content=`${DKD.toggleRow('Microphone','mic','Simulated status. No microphone is recorded.')}<p>Input device: Controller microphone</p>`;
 if(label==='Accessories')content=`<div class="row">${DKD.icon('controller')}<span>DualSense wireless controller</span></div><div class="row" style="margin-top:18px">${DKD.icon('battery')}<span>Fully charged · Connected</span></div><div class="row" style="margin-top:26px">${DKD.icon('headphones')}<span>PULSE Elite™ wireless headset</span></div><div class="row" style="margin-top:18px">${DKD.icon('battery')}<span>86% · Connected</span></div><p>Hardware status is simulated.</p><button class="list-button" data-action="controls-help">View Controls ${DKD.icon('arrow')}</button>`;
 if(label==='Profile')content=`<div class="row">${DKD.avatar(undefined,true)}<div><h3 style="font-weight:400;margin:0">${DKD.escape(DKD.state.profile.name)}</h3><p>${DKD.state.settings.status}</p></div></div><button class="list-button" data-action="edit-profile">Edit Profile</button><button class="list-button" data-action="trophies">${DKD.icon('trophy')} Trophies · ${DKD.state.trophies.length}</button>${DKD.selectRow('Online Status','status',['Online','Busy','Appear Offline'])}`;
 if(label==='Power')content=`<button class="list-button" data-action="power" data-id="rest">${DKD.icon('moon')}Enter Rest Mode</button><button class="list-button" data-action="power" data-id="off">${DKD.icon('power')}Turn Off PS5</button><button class="list-button" data-action="power" data-id="restart">${DKD.icon('restart')}Restart PS5</button>`;
 return `<h2>${label}</h2><div class="modal-list">${content}</div>`;
};
DKD.power=mode=>{DKD.activeSession?.pause();DKD.closeModal();DKD.closeCC(false);DKD.powerState=mode;DKD.persist();if(mode!=='rest'){Object.values(DKD.sessions).forEach(session=>session.destroy());DKD.sessions={};DKD.activeSession=null;document.getElementById('game-host').hidden=true;}
 const content=mode==='rest'?['Rest mode','Your game is suspended. Downloads continue in the background.','Wake Console']:mode==='off'?['PS5 is turned off','Your library, purchases and records are saved.','Turn On']:['Restarting your PS5…','Please wait a moment.',''];
 document.getElementById('modal-root').innerHTML=`<div class="power-screen">${DKD.icon('ps')}<div class="power-light" style="${mode==='rest'?'':'background:#cce3ff;box-shadow:0 0 20px #70b0ff'}"></div><h1>${content[0]}</h1><p>${content[1]}</p>${content[2]?`<button class="pill primary" data-action="wake">${content[2]}</button>`:''}</div>`;if(mode==='restart')setTimeout(()=>{if(DKD.powerState==='restart')DKD.wake();},1600);};
DKD.wake=()=>{DKD.powerState=null;DKD.closeModal();DKD.navigate('home');DKD.audio.tone(440,.35);setTimeout(()=>DKD.audio.tone(660,.55),100);};
