DKD.homeSelection='welcome';DKD.homeTab='Games';DKD.editWidgets=false;
DKD.avatar=(name=DKD.state.profile.name,large=false,color)=>{const friend=DKD.friends?.find(item=>item.name===name);const initials=DKD.escape(name.substring(0,2).toUpperCase());return `<span class="avatar ${large?'large':''}" style="${color?'background:linear-gradient(145deg,'+color+',#22334b)':''}">${initials}${friend?.photo?`<img src="${friend.photo}" alt="${DKD.escape(name)} profile photo" decoding="async" onerror="this.remove()">`:''}</span>`;};
DKD.topbar=()=>`<header class="topbar"><nav class="main-nav" aria-label="Home sections"><button data-action="home-tab" data-id="Games" class="${DKD.homeTab==='Games'?'active':''}">Games</button><button data-action="home-tab" data-id="Projects" class="${DKD.homeTab==='Projects'?'active':''}">Projects</button><button data-action="home-tab" data-id="Media" class="${DKD.homeTab==='Media'?'active':''}">Media</button></nav><div class="top-right"><span class="dkd-version">v0.6</span><button class="icon-btn" data-action="search" aria-label="Search">${DKD.icon('search')}</button><button class="icon-btn" data-action="settings" aria-label="Settings">${DKD.icon('settings')}</button><button class="icon-btn" data-action="profile" aria-label="Profile">${DKD.avatar()}</button><time class="clock"></time></div></header>`;
DKD.homeItems=()=>{const priority=['last-mile','shift-error'];const rank=id=>{const position=priority.indexOf(id);return position<0?99:position;};const installed=[...DKD.state.installed].sort((a,b)=>rank(a)-rank(b));return [{id:'store',title:'PlayStation Store',icon:'store'},{id:'welcome',title:'Welcome',icon:'welcome'},...installed.map(id=>({id,title:DKD.game(id).title,art:true})),{id:'plus',title:'PlayStation Plus',icon:'plus'},{id:'library',title:'Game Library',icon:'library'}];};
DKD.renderHome=()=>{
 const dkdFocused=document.activeElement?.dataset;
 const dkdFocusAction=dkdFocused?.action,dkdFocusId=dkdFocused?.id;
 const dkdPreviousRail=DKD.screen.querySelector('.project-rail');
 const dkdRailScroll=dkdPreviousRail?.scrollLeft||0;
 const items=DKD.homeItems();if(!items.some(item=>item.id===DKD.homeSelection))DKD.homeSelection='welcome';
 DKD.screen.innerHTML=DKD.topbar()+(DKD.homeTab==='Media'?DKD.mediaView():DKD.homeTab==='Projects'?DKD.projectsView():`<nav class="game-rail" aria-label="Games and apps">${items.map(item=>`<button class="game-tile ${item.id} ${DKD.homeSelection===item.id?'selected':''}" data-action="select-home" data-id="${item.id}" aria-label="${item.title}" aria-pressed="${DKD.homeSelection===item.id}">${item.art?`<img src="${DKD.art(item.id)}" alt=""><span class="tile-title">${DKD.game(item.id).art.toUpperCase()}</span>`:DKD.icon(item.icon)}<span class="tile-label">${item.title}</span></button>`).join('')}</nav><div class="home-body">${DKD.homeSelection==='welcome'?DKD.welcomeView():DKD.homeHero()}</div>`);
 DKD.setWallpaper(DKD.homeTab==='Media'||DKD.homeTab==='Projects'?'default':DKD.homeSelection==='welcome'?DKD.state.wallpaper:DKD.game(DKD.homeSelection)?.art || 'default');DKD.clock();
 const dkdProjectRail=DKD.screen.querySelector('.project-rail');
 if(dkdProjectRail){
  dkdProjectRail.scrollLeft=dkdRailScroll;
  dkdProjectRail.querySelector('.selected')?.scrollIntoView({block:'nearest',inline:'nearest',behavior:'instant'});
 }
 if(['home-tab','project-select'].includes(dkdFocusAction)){
  [...DKD.screen.querySelectorAll('[data-action]')].find(dkdButton=>dkdButton.dataset.action===dkdFocusAction&&dkdButton.dataset.id===dkdFocusId)?.focus({preventScroll:true});
 }
 if(DKD.editWidgets)DKD.bindWidgetDrag();
};
DKD.welcomeView=()=>`<div class="welcome-heading"><div><h1>Welcome back, ${DKD.escape(DKD.state.profile.name)}</h1><p>Your games. Your friends. Your next adventure.</p></div><div class="welcome-actions">${DKD.editWidgets?`<button class="pill" data-action="add-widgets">${DKD.icon('plus')} Add widgets</button>`:''}<button class="pill" data-action="wallpaper">${DKD.icon('image')} Change background</button><button class="pill" data-action="edit-widgets">${DKD.icon(DKD.editWidgets?'check':'edit')} ${DKD.editWidgets?'Done':'Edit widgets'}</button></div></div><section class="widgets ${DKD.editWidgets?'editing':''}" aria-label="Welcome widgets">${DKD.state.widgets.map(widget=>DKD.widget(widget)).join('')}</section>`;
DKD.widget=widget=>{
 const titles={friends:'Online Friends',battery:'Accessories',headset:'Accessories',storage:'Console Storage',trophies:'Trophies',wishlist:'Wishlist',store:'PlayStation Store'};
 const icons={friends:'friends',battery:'controller',headset:'headphones',storage:'storage',trophies:'trophy',wishlist:'heart',store:'store'};
 const actions={friends:'friends',battery:'accessories',headset:'accessories',storage:'storage',trophies:'trophies',wishlist:'wishlist',store:'store'};
 const used=DKD.state.installed.reduce((sum,id)=>sum+DKD.game(id).size,0);
 let body='';
 if(widget.id==='friends')body=`<div class="friend-avatars">${DKD.friends.map(friend=>DKD.avatar(friend.name,false,friend.color)).join('')}<span class="friend-summary">${DKD.friends.length} online</span></div><div class="widget-detail">See what your friends are playing</div>`;
 if(widget.id==='battery')body='<div class="battery-meter"><span></span><span></span><span></span></div><div class="widget-detail">DualSense™<br>Fully charged</div>';
 if(widget.id==='headset')body=`<div class="headset-meter">${DKD.icon('headphones')}</div><div class="widget-detail">PULSE Elite™<br>Connected · 86%</div>`;
 if(widget.id==='storage')body=`<div class="storage-stats"><span class="widget-big">${(667-used).toFixed(1)}</span><small>GB available</small></div><div class="progress"><span style="width:${Math.max(5,used/667*100)}%"></span></div><div class="widget-detail">${used.toFixed(1)} GB used of 667 GB</div>`;
 if(widget.id==='trophies')body=`<div class="trophy-display">${DKD.icon('trophy')}<span class="widget-big">${DKD.state.trophies.length}</span></div><div class="widget-detail">Your collection</div>`;
 if(widget.id==='wishlist'){const wished=DKD.game(DKD.state.wishlist[0]);body=wished?`<div class="row"><img src="${DKD.art(wished.id)}" alt=""><div><div class="small">${wished.title}</div><div class="widget-detail">${DKD.price(wished.price)} <span class="gold"> · On sale</span></div></div></div>`:'<span class="widget-detail">Save the games you love.</span>';}
 if(widget.id==='store')body='<h3>Find your next adventure.</h3><div class="widget-detail">Discover new worlds, great games and this week’s offers. <span style="margin-left:15px">›</span></div>';
 return `<article class="widget ${widget.id}" data-widget="${widget.id}" draggable="${DKD.editWidgets}" style="--span:${widget.size}">${DKD.editWidgets?`<div class="widget-edit-tools"><button data-action="widget-move" data-id="${widget.id}" aria-label="Move ${titles[widget.id]} left">${DKD.icon('back')}</button><button data-action="widget-resize" data-id="${widget.id}" aria-label="Resize ${titles[widget.id]}">${DKD.icon('resize')}</button><button data-action="widget-remove" data-id="${widget.id}" aria-label="Remove ${titles[widget.id]}">${DKD.icon('close')}</button></div>`:''}<button class="widget-main" data-action="${actions[widget.id]}" aria-label="Open ${titles[widget.id]}"><div class="widget-title">${DKD.icon(icons[widget.id])}${titles[widget.id]}</div>${body}</button></article>`;
};
DKD.homeHero=()=>{
 const id=DKD.homeSelection,game=DKD.game(id);
 if(game)return `<section class="game-hero"><div class="hero-meta"><span class="badge">PS5</span><span>${game.tag}</span><span>•</span><span>Original game</span></div><h1 class="game-wordmark ${game.art}" style="margin-top:24px">${game.title}</h1><p class="hero-subtitle">${game.subtitle}</p><div class="hero-actions"><button class="pill primary" data-action="launch" data-id="${id}">${DKD.sessions?.[id]?'Resume Game':'Play Game'}</button><button class="circle-btn" data-action="product" data-id="${id}" aria-label="Game details">${DKD.icon('more')}</button></div></section><div class="hero-bottom"><div><span class="small">Personal best</span><strong>${(DKD.state.scores[id]||0).toLocaleString()}</strong></div><div><span class="small">Game size</span><strong>${game.size} GB</strong></div></div>`;
 const info={store:['PlayStation Store','Discover your next great adventure.','Explore the Store','store'],library:['Game Library','All your games. Ready when you are.','View Collection','library'],plus:['PlayStation Plus','More ways to play. More to discover.','Explore Games','store']}[id];
 return `<section class="game-hero"><div style="margin-bottom:28px">${DKD.icon(id==='plus'?'plus':id)}</div><h1 style="font-size:64px;font-weight:300;margin:0 0 25px">${info[0]}</h1><p class="hero-subtitle">${info[1]}</p><button class="pill primary" data-action="${info[3]}">${info[2]}</button></section>`;
};
DKD.mediaView=()=>`<div class="home-body dkd-media-home"><div class="welcome-heading"><div><h1>Media</h1><p>A moment between adventures.</p></div></div><div class="media-grid"><button class="media-card" data-action="gallery" style="background-image:linear-gradient(0deg,#081524,transparent),url('${DKD.art('lumen')}')">${DKD.icon('image')}Media Gallery<small>Explore your game artwork</small></button><button class="media-card" data-action="music">${DKD.icon('music')}Music<small>Original ambient console soundtrack</small></button><button class="media-card" data-action="trailer" style="background-image:linear-gradient(0deg,#081524,transparent),url('${DKD.art('apex')}')">${DKD.icon('video')}Game Showcase<small>Explore the arcade demo</small></button></div></div>`;
DKD.bindWidgetDrag=()=>{let dragged;document.querySelectorAll('[data-widget]').forEach(element=>{element.addEventListener('dragstart',event=>{dragged=element.dataset.widget;event.dataTransfer.setData('text/plain',dragged);});element.addEventListener('dragover',event=>{event.preventDefault();element.classList.add('drag-over');});element.addEventListener('dragleave',()=>element.classList.remove('drag-over'));element.addEventListener('drop',event=>{event.preventDefault();const from=DKD.state.widgets.findIndex(item=>item.id===dragged),to=DKD.state.widgets.findIndex(item=>item.id===element.dataset.widget);if(from>=0&&to>=0){const [item]=DKD.state.widgets.splice(from,1);DKD.state.widgets.splice(to,0,item);DKD.persist();DKD.renderHome();}});});};
DKD.showBackgrounds=()=>DKD.modal('Change background',`<p>Choose a background for your Welcome Hub.</p><div class="background-choices">${['default','apex','lumen','orbital'].map(id=>`<button class="background-choice ${DKD.state.wallpaper===id?'active':''}" data-action="set-wallpaper" data-id="${id}" style="${id!=='default'?`background-image:linear-gradient(0deg,#071322aa,transparent),url('${DKD.art(id)}')`:''}">${id==='default'?'Default':id.toUpperCase()}</button>`).join('')}</div>`);
DKD.showAddWidgets=()=>DKD.modal('Add widgets',`<div class="modal-list">${[['friends','Online Friends'],['battery','Accessories'],['headset','Headset Accessories'],['storage','Console Storage'],['trophies','Trophies'],['wishlist','Wishlist'],['store','PlayStation Store']].map(([id,title])=>`<button class="list-button" data-action="widget-add" data-id="${id}" ${DKD.state.widgets.some(item=>item.id===id)?'disabled':''}>${DKD.icon(DKD.state.widgets.some(item=>item.id===id)?'check':'plus')}${title}</button>`).join('')}</div>`);
