DKD.settingsSection='Sound';
DKD.settingsSections=[['Sound','sound'],['Accessibility','access'],['Network','network'],['Users and Accounts','profile'],['Family and Parental Controls','friends'],['System','settings'],['Storage','storage'],['Screen and Video','screen'],['Accessories','controller'],['Saved Data and Game/App Settings','save']];
DKD.toggleRow=(label,key,detail='')=>`<div class="setting-row"><div>${label}${detail?`<small>${detail}</small>`:''}</div><button class="switch ${DKD.state.settings[key]?'on':''}" data-action="toggle-setting" data-id="${key}" role="switch" aria-checked="${!!DKD.state.settings[key]}" aria-label="${label}"></button></div>`;
DKD.selectRow=(label,key,choices,detail='')=>`<label class="setting-row"><div>${label}${detail?`<small>${detail}</small>`:''}</div><select data-setting="${key}" aria-label="${label}">${choices.map(choice=>`<option ${DKD.state.settings[key]===choice?'selected':''}>${choice}</option>`).join('')}</select></label>`;
DKD.rangeRow=(label,key)=>`<label class="setting-row"><span>${label}</span><span class="row"><input type="range" min="0" max="100" value="${DKD.state.settings[key]}" data-setting="${key}" aria-label="${label}"><span class="small" data-range-label="${key}">${DKD.state.settings[key]}</span></span></label>`;
DKD.renderSettings=()=>{DKD.setWallpaper('default');DKD.screen.innerHTML=`<div class="page"><header class="page-header"><h1 class="page-title"><button class="icon-btn" data-action="home" aria-label="Back to Home">${DKD.icon('back')}</button>Settings</h1><time class="clock"></time></header><div class="settings-layout"><nav class="settings-nav" aria-label="Settings categories">${DKD.settingsSections.map(([title,icon])=>`<button class="${DKD.settingsSection===title?'active':''}" data-action="settings-section" data-id="${title}">${DKD.icon(icon)}<span>${title}</span></button>`).join('')}</nav><section class="settings-content" id="settings-content">${DKD.settingsContent()}</section></div></div>`;DKD.clock();};
DKD.settingsContent=()=>{
 let content='';const section=DKD.settingsSection;
 if(section==='Accessibility')content=`<p>Make your console experience comfortable for you.</p>${DKD.toggleRow('Reduce Motion','reducedMotion','Reduce menu animations and background transitions.')}${DKD.toggleRow('High Contrast','contrast','Increase the contrast of menus and widgets.')}${DKD.selectRow('Text Size','textSize',['Normal','Large'])}${DKD.toggleRow('Subtitles','subtitles','Show gameplay guidance in the game overlay.')}`;
 if(section==='Network')content=`${DKD.toggleRow('Connect to the Internet','network','Simulated console connection. Pauses downloads when disabled.')}<div class="setting-row"><span>Connection Status</span><span class="muted">${DKD.state.settings.network?'Connected':'Disconnected'}</span></div><div class="setting-row"><span>Connection Method</span><span class="muted">Wi-Fi · Console Lab</span></div><button class="list-button" data-action="network-test">${DKD.icon('network')} Test Internet Connection ${DKD.icon('arrow')}</button>`;
 if(section==='Users and Accounts')content=`<div class="row" style="margin:30px 0">${DKD.avatar(undefined,true)}<div><h3>${DKD.escape(DKD.state.profile.name)}</h3><p class="small">Local console profile</p></div></div><button class="list-button" data-action="edit-profile">${DKD.icon('edit')}Edit Profile</button>${DKD.selectRow('Online Status','status',['Online','Busy','Appear Offline'])}${DKD.selectRow('Privacy','privacy',['Friends only','Anyone','No one'],'Controls the visibility of your simulated profile.')}<button class="list-button" data-action="transactions">${DKD.icon('store')}Transaction History</button>`;
 if(section==='Family and Parental Controls')content=`<p>Local family settings for this browser console.</p>${DKD.selectRow('Age Level for Games','parental',['No restrictions','Teen and below','Everyone'])}<div class="setting-row"><span>Spending Limit<small>All purchases use demo credit.</small></span><span class="muted">No real payments</span></div>${DKD.selectRow('Play Time Reminder','playReminder',['Off','30 minutes','60 minutes'])}`;
 if(section==='System')content=`<div class="setting-row"><span>System Software</span><span class="muted">DraBornPS v0.6 Software Update</span></div><div class="setting-row"><span>Appearance and Sound<small>Games, Projects and Media with Welcome Hub, Miami Nights colors and project mockups.</small></span><span>Miami Nights</span></div><button class="list-button" data-action="wallpaper">${DKD.icon('image')}Welcome Hub Background${DKD.icon('arrow')}</button>${DKD.selectRow('Enter Rest Mode Automatically','autoRest',['Never','20 minutes','1 hour'],'Simulated inactivity timer.') }<button class="list-button" data-action="about">${DKD.icon('ps')}About this console experience</button>`;
 if(section==='Storage'){const used=DKD.state.installed.reduce((sum,id)=>sum+DKD.game(id).size,0);content=`<div class="settings-storage"><div class="row between"><span>Console Storage</span><span>${(667-used).toFixed(1)} GB free</span></div><div class="progress"><span style="width:${used/667*100}%"></span></div><span class="small muted">${used.toFixed(1)} GB used / 667 GB · Simulated capacity</span></div>${DKD.state.installed.map(id=>`<div class="storage-game"><img src="${DKD.art(id)}" alt=""><div class="grow"><span class="small">${DKD.game(id).title}</span><div class="muted tiny" style="margin-top:8px">${DKD.game(id).external?'Web game':DKD.game(id).size+' GB'}</div></div><button class="pill" data-action="uninstall-confirm" data-id="${id}">Delete</button></div>`).join('')}`;}
 if(section==='Sound')content=`${DKD.rangeRow('Master Volume','volume')}${DKD.toggleRow('Home Screen Music','music','An original ambient soundtrack generated on this device.')}<div class="setting-row"><span>Output Device</span><span class="muted">Browser audio output</span></div>${DKD.selectRow('Audio Focus','audioFocus',['Off','Boost Low Pitch','Boost Voices','Boost High Pitch','Boost Quiet Sounds'],'Stored as a console preference; no system audio processing.')}<button class="list-button" data-action="audio-test">${DKD.icon('sound')}Play Test Sound</button>`;
 if(section==='Screen and Video')content=`${DKD.selectRow('Resolution','resolution',['1920 × 1080','1280 × 720','3840 × 2160'],'Display preference. The interface scales to your browser.')}${DKD.toggleRow('HDR','hdr','Simulated output setting.')}${DKD.rangeRow('Brightness','brightness')}<button class="list-button" data-action="fullscreen">${DKD.icon('resize')}Enter Full Screen</button><div class="setting-row"><span>Aspect Ratio</span><span class="muted">16:9</span></div>`;
 if(section==='Accessories')content=`<div class="row" style="margin:28px 0">${DKD.icon('controller')}<span style="font-size:25px">DualSense wireless controller</span>${DKD.icon('battery')}</div><p>Keyboard, mouse, touch and standard browser gamepads are supported. Hardware status is simulated.</p>${DKD.toggleRow('Vibration','vibration','Use connected gamepad vibration when supported.')}${DKD.rangeRow('Controller Speaker','controllerSpeaker')}<button class="list-button" data-action="controls-help">${DKD.icon('controller')}View Controls</button>`;
 if(section==='Saved Data and Game/App Settings')content=`<p>Best scores and your trophy collection are saved on this device.</p>${DKD.selectRow('Difficulty Preset','difficulty',['Easy','Normal','Hard'],'Applies when starting a new game.')}${DKD.catalog.filter(game=>DKD.state.scores[game.id]!==undefined).map(game=>`<div class="setting-row"><span>${game.title}</span><span>${DKD.state.scores[game.id].toLocaleString()} points</span></div>`).join('')||'<div class="empty">Play a game to set your first record.</div>'}<button class="list-button" data-action="reset-scores-confirm">${DKD.icon('restart')}Delete Saved Scores</button>`;
 return `<h2>${section}</h2>${content}`;
};
DKD.applySettings=()=>{document.getElementById('console').classList.toggle('reduced-motion',DKD.state.settings.reducedMotion);document.getElementById('console').classList.toggle('high-contrast',DKD.state.settings.contrast);document.getElementById('console').classList.toggle('large-text',DKD.state.settings.textSize==='Large');document.getElementById('wallpaper').style.filter=`brightness(${.55+DKD.state.settings.brightness/155})`;DKD.audio?.applyVolume?.();};
