DKD.storeTab='Latest';DKD.storeQuery='';DKD.libraryTab='Your Collection';DKD.libraryFilter='All';
DKD.cover=game=>`<div class="cover"><img src="${DKD.art(game.id)}" alt="${game.title} artwork"><span class="badge">PS5</span>${game.oldPrice?`<span class="discount">−${Math.round((1-game.price/game.oldPrice)*100)}%</span>`:''}<span class="cover-wordmark">${game.title.split(':')[0]}${game.title.includes(':')?`<small>${game.title.split(':')[1]}</small>`:''}</span></div>`;
DKD.gameCard=(game,library=false)=>{const download=DKD.state.downloads[game.id],installed=DKD.state.installed.includes(game.id),owned=DKD.state.owned.includes(game.id);return `<button class="game-card" data-action="${library&&installed?'launch':'product'}" data-id="${game.id}" aria-label="${library&&installed?'Play ':''}${game.title}">${DKD.cover(game)}<span class="game-card-title">${game.title}</span><span class="card-meta">${download?`${DKD.icon('download')} <span data-download-label="${game.id}">${Math.floor(download.progress)}% · ${download.paused?'Paused':'Downloading'}</span>`:game.external?(library?'Ready to play':'DraBornGames · Included'):installed&&library?'Installed':owned?'Purchased':`${DKD.price(game.price)} ${game.oldPrice?`<del>${DKD.price(game.oldPrice)}</del>`:''}`}</span>${download?`<div class="progress"><span data-download-progress="${game.id}" style="width:${download.progress}%"></span></div>`:''}</button>`;};
DKD.renderStore=()=>{DKD.setWallpaper('default');DKD.screen.innerHTML=`<div class="page store-page"><header class="page-header"><h1 class="page-title"><button class="icon-btn" data-action="home" aria-label="Back to Home">${DKD.icon('back')}</button>${DKD.icon('store')} PlayStation Store</h1><div class="row"><span class="small muted">${DKD.escape(DKD.state.profile.name)}</span>${DKD.avatar()}</div></header><div class="row between store-toolbar"><nav class="tabs" aria-label="Store sections">${['Latest','Collections','Deals','Wishlist'].map(tab=>`<button class="tab ${DKD.storeTab===tab?'active':''}" data-action="store-tab" data-id="${tab}">${tab}</button>`).join('')}</nav><label class="search-field">${DKD.icon('search')}<input id="store-search" placeholder="Search games" aria-label="Search Store" value="${DKD.escape(DKD.storeQuery)}"></label></div><div id="store-content">${DKD.storeContent()}</div></div>`;};
DKD.storeContent=()=>{
 let games=DKD.catalog.filter(game=>game.title.toLowerCase().includes(DKD.storeQuery.toLowerCase()));const dkdStorePriority={'last-mile':0,'shift-error':1};games=[...games].sort((a,b)=>(dkdStorePriority[a.id]??99)-(dkdStorePriority[b.id]??99));if(DKD.storeTab==='Wishlist')games=games.filter(game=>DKD.state.wishlist.includes(game.id));if(DKD.storeTab==='Deals')games=games.filter(game=>game.oldPrice);
 const showHero=DKD.storeTab==='Latest'&&!DKD.storeQuery;
 if(DKD.storeTab==='Collections'&&!DKD.storeQuery)return ['Racing','Platformer','Arcade'].map(type=>`<div class="store-section-title"><h2>${{Racing:'Chase the horizon',Platformer:'Extraordinary journeys',Arcade:'One more run'}[type]}</h2><span class="small muted">${type}</span></div><div class="game-grid" style="grid-template-columns:repeat(3,1fr);max-width:1200px">${games.filter(game=>game.tag===type).map(game=>DKD.gameCard(game)).join('')}</div>`).join('');
 return `${showHero?`<section class="store-hero"><span class="tag">DraBornGames Featured</span><h1>LAST MILE</h1><p>Ankara sokaklarında vardiyana başla, teslimatlarını tamamla ve kurye kariyerini büyüt.</p><button class="pill primary" data-action="product" data-id="last-mile">Discover Last Mile ${DKD.icon('arrow')}</button></section>`:''}<div class="store-section-title"><h2>${DKD.storeQuery?'Search results':DKD.storeTab==='Wishlist'?'Your wishlist':DKD.storeTab==='Deals'?'Great games. Smaller prices.':'Made for your next adventure'}</h2><span class="small muted">${games.length} games</span></div>${games.length?`<div class="game-grid">${games.map(game=>DKD.gameCard(game)).join('')}</div>`:`<div class="empty">${DKD.icon('search')}<div>${DKD.storeTab==='Wishlist'?'Your wishlist is waiting for an adventure.':'No games found. Try another title.'}</div></div>`}`;
};
DKD.renderProduct=id=>{
 const game=DKD.game(id);DKD.productId=id;DKD.setWallpaper(game.art);const owned=DKD.state.owned.includes(id),installed=DKD.state.installed.includes(id),download=DKD.state.downloads[id];
 DKD.screen.innerHTML=`<div class="product-screen"><div class="row between"><button class="pill dark back-product" data-action="store">${DKD.icon('back')} PlayStation Store</button><span class="tag">${game.external?'DraBornGames':'Original browser game'}</span></div><section class="product-main"><div class="hero-meta"><span class="badge">PS5</span><span>${game.tag}</span><span>•</span><span>1 player</span></div><h1>${game.title}</h1><div class="stars">${[1,2,3,4,5].map(()=>DKD.icon('star')).join('')}<span style="color:#dce4ed;margin-left:14px">${game.rating} <span class="tiny muted">· Rating</span></span></div><p class="description">${game.description}</p><div class="product-price">${game.external?'DraBornGames · Web':owned?'Purchased':DKD.price(game.price)}${!game.external&&!owned&&game.oldPrice?`<del>${DKD.price(game.oldPrice)}</del>`:''}</div><div class="hero-actions"><button class="pill primary" data-action="${installed?'launch':download?'downloads':owned?'download':'checkout'}" data-id="${id}">${installed?(DKD.sessions?.[id]?'Resume Game':'Play Game'):download?`Downloading · <span data-download-label="${id}">${Math.floor(download.progress)}%</span>`:owned?'Download':'Add to Cart'}</button><button class="circle-btn ${DKD.state.wishlist.includes(id)?'active':''}" data-action="wishlist-toggle" data-id="${id}" aria-label="${DKD.state.wishlist.includes(id)?'Remove from':'Add to'} wishlist" aria-pressed="${DKD.state.wishlist.includes(id)}">${DKD.icon('heart')}</button></div>${download?`<div class="progress" style="width:340px;margin-top:25px"><span data-download-progress="${id}" style="width:${download.progress}%"></span></div>`:''}</section><div class="product-foot"><span>${DKD.icon('controller')}Single player</span>${game.external?`<span>${DKD.icon('network')}Web game</span><span>${DKD.icon('save')}DraBornGames experience</span>`:`<span>${DKD.icon('storage')}${game.size} GB</span><span>${DKD.icon('save')}Local save supported</span>`}</div></div>`;
};
DKD.checkout=id=>{const game=DKD.game(id);DKD.modal('Confirm purchase',`<div class="checkout-item"><img src="${DKD.art(id)}" alt=""><div class="stack"><h3>${game.title}</h3><span class="muted small">Standard edition · Original browser game</span><span class="badge" style="width:fit-content">PS5</span></div></div><div class="separator"></div><div class="row between" style="font-size:26px"><span>Total</span><span>${DKD.price(game.price)}</span></div><p class="demo-notice">No real payment is taken and no payment details are needed. The game will be added to your library and its download will begin.</p><div class="modal-actions"><button class="pill" data-action="close-modal">Cancel</button><button class="pill primary" data-action="buy" data-id="${id}">Confirm Purchase</button></div>`);};
DKD.renderLibrary=()=>{
 DKD.setWallpaper('default');let games=DKD.catalog.filter(game=>DKD.state.owned.includes(game.id));if(DKD.libraryTab==='Installed')games=games.filter(game=>DKD.state.installed.includes(game.id));if(DKD.libraryFilter!=='All')games=games.filter(game=>game.tag===DKD.libraryFilter);const lastMileIndex=games.findIndex(game=>game.id==='last-mile'),apexIndex=games.findIndex(game=>game.id==='apex');if(lastMileIndex>=0&&apexIndex>=0)[games[lastMileIndex],games[apexIndex]]=[games[apexIndex],games[lastMileIndex]];
 DKD.screen.innerHTML=`<div class="page"><header class="page-header"><h1 class="page-title"><button class="icon-btn" data-action="home" aria-label="Back to Home">${DKD.icon('back')}</button>Game Library</h1><button class="pill" data-action="downloads">${DKD.icon('download')} Downloads <span>${Object.keys(DKD.state.downloads).length||''}</span></button></header><div class="tabs">${['Your Collection','Installed'].map(tab=>`<button class="tab ${DKD.libraryTab===tab?'active':''}" data-action="library-tab" data-id="${tab}">${tab}</button>`).join('')}<span class="grow"></span><span class="small muted">${games.length} games</span></div><div class="filter-pills">${['All',...new Set(DKD.catalog.map(game=>game.tag))].map(type=>`<button class="${DKD.libraryFilter===type?'active':''}" data-action="library-filter" data-id="${type}">${type}</button>`).join('')}</div>${games.length?`<div class="game-grid library-grid">${games.map(game=>DKD.gameCard(game,true)).join('')}</div>`:'<div class="empty">No games in this category yet.</div>'}</div>`;
};
DKD.showDownloads=()=>DKD.modal('Downloads / Uploads',Object.keys(DKD.state.downloads).length?`<div class="modal-list">${Object.entries(DKD.state.downloads).map(([id,download])=>`<div class="panel" style="padding:22px"><div class="row between"><h3>${DKD.game(id).title}</h3><span data-download-label="${id}" class="small">${Math.floor(download.progress)}% · ${download.paused?'Paused':'Downloading'}</span></div><div class="progress" style="margin:20px 0"><span data-download-progress="${id}" style="width:${download.progress}%"></span></div><div class="row"><button class="pill" data-action="pause-download" data-id="${id}" style="font-size:17px;min-height:38px">${download.paused?'Resume':'Pause'}</button><button class="pill" data-action="cancel-download" data-id="${id}" style="font-size:17px;min-height:38px">Cancel download</button></div></div>`).join('')}</div>`:'<div class="empty">'+DKD.icon('check')+'<div>You’re all up to date.</div></div>');
DKD.refreshDownloads=()=>{document.querySelectorAll('[data-download-progress]').forEach(element=>{element.style.width=(DKD.state.downloads[element.dataset.downloadProgress]?.progress||100)+'%';});document.querySelectorAll('[data-download-label]').forEach(element=>{const download=DKD.state.downloads[element.dataset.downloadLabel];element.textContent=download?Math.floor(download.progress)+'%'+(download.paused?' · Paused':''):'Ready to play';});const signature=DKD.state.installed.join(',');if(DKD.lastInstalled!==signature){DKD.lastInstalled=signature;if(['library','product','home'].includes(DKD.route))DKD.render();if(DKD.modalTitle==='Downloads / Uploads')DKD.showDownloads();}};
