import React,{useEffect,useRef,useState} from 'react';
import {AppState,View,Linking} from 'react-native';
import * as Location from 'expo-location';
import {api,supabase,useData,Row as DataRow,money,dateLabel,clock,statusLabel,istanbul,today} from './data';
import {Badge,Button,Card,Empty,Fade,Head,Input,Row,Sheet,Stack,T,TaskStatus,useTask,useTheme} from './ui';
export function Bookings({openChat}:{openChat:(id:string)=>void}){
 const {rows,session,act,directory,isManager,page}=useData(),{colors}=useTheme(),task=useTask();
 const [filter,setFilter]=useState('upcoming'),[modal,setModal]=useState<DataRow|null>(null),[kind,setKind]=useState(''),[day,setDay]=useState(today()),[time,setTime]=useState('10:00'),[rating,setRating]=useState('5'),[body,setBody]=useState(''),[tracked,setTracked]=useState(''),[more,setMore]=useState<DataRow[]>([]),[manual,setManual]=useState(false),[staffId,setStaffId]=useState(''),[serviceId,setServiceId]=useState(''),[customerName,setCustomerName]=useState(''),[source,setSource]=useState('phone'),[calendar,setCalendar]=useState('all'),[calendarDate,setCalendarDate]=useState(today());
 const watch=useRef<Location.LocationSubscription|null>(null);
 const [queueInfo,setQueueInfo]=useState<Record<string,DataRow>>({});
 const myQueue=(rows.queue||[]).filter(q=>q.customer_user_id===session?.user.id&&q.state==='waiting');
 useEffect(()=>{let alive=true;void Promise.all(myQueue.map(async q=>{const r=await supabase.rpc('queue_status',{queue_id:q.id});return [q.id,r.data||{}];})).then(r=>{if(alive)setQueueInfo(Object.fromEntries(r));});return()=>{alive=false;};},[rows.queue,rows.staff_availability,session?.user.id]);
 useEffect(()=>{const sub=AppState.addEventListener('change',s=>{if(s!=='active'){watch.current?.remove();watch.current=null;setTracked('');}});return()=>{sub.remove();watch.current?.remove();};},[]);
 const records=[...(rows.appointments||[]),...more.filter(r=>!(rows.appointments||[]).some(x=>x.id===r.id))];
 const permitted=(rows.staff||[]).filter(s=>s.active&&(isManager||s.user_id===session?.user.id));
 const list=records.filter(a=>{if(calendar==='all')return true;const d=new Date(a.starts_at).toLocaleDateString('en-CA',{timeZone:'Europe/Istanbul'});if(calendar==='day')return d===calendarDate;if(calendar==='month')return d.slice(0,7)===calendarDate.slice(0,7);const delta=(new Date(d).getTime()-new Date(calendarDate).getTime())/86400000;return delta>=0&&delta<7;}).filter(a=>filter==='all'?true:filter==='completed'?a.status==='completed':['confirmed','late','in_progress'].includes(a.status)).sort((a,b)=>filter==='upcoming'?new Date(a.starts_at).getTime()-new Date(b.starts_at).getTime():new Date(b.starts_at).getTime()-new Date(a.starts_at).getTime());
 const track=(a:DataRow)=>task.run(async()=>{
  if(tracked===a.id){watch.current?.remove();watch.current=null;await act('location_revoke',{appointment_id:a.id});setTracked('');return;}
  const p=await Location.requestForegroundPermissionsAsync();if(p.status!=='granted')throw new Error('İzin verilmedi. Randevun etkilenmez.');
  if(tracked)await api('location_revoke',{appointment_id:tracked});watch.current?.remove();
  await api('location_consent',{appointment_id:a.id});setTracked(a.id);
  watch.current=await Location.watchPositionAsync({accuracy:Location.Accuracy.Balanced,timeInterval:20000,distanceInterval:75},loc=>{void api('location_update',{appointment_id:a.id,latitude:loc.coords.latitude,longitude:loc.coords.longitude,accuracy:loc.coords.accuracy}).catch(()=>{watch.current?.remove();setTracked('');});});
  await act('profile');
 },tracked===a.id?'Varış takibi sonlandırıldı.':'Varış takibi başladı. Yalnızca bu randevunun yetkili işletmesi görebilir.');
 const cancel=(a:DataRow)=>{setModal(a);setKind('cancel');};
 return <Fade><Stack><Head eyebrow="Takvimin" title={isManager?'Randevu takvimi':'Sana ayrılmış saatler'} subtitle="Randevu, mesaj ve varış bilgileri aynı akışta." action={permitted.length?<Button title="＋ Telefon randevusu" small onPress={()=>{setManual(true);setStaffId(permitted[0].id);setServiceId('');}}/>:undefined}/><Row>{[['all','Tüm takvim'],['day','Günlük'],['week','Haftalık'],['month','Aylık']].map(([k,l])=><Button key={k} title={l} small secondary={calendar!==k} onPress={()=>setCalendar(k)}/>)}</Row>{calendar!=='all'&&<Input label="Takvim günü YYYY-AA-GG" value={calendarDate} onChangeText={setCalendarDate}/>}<Row>{[['upcoming','Yaklaşan'],['completed','Tamamlanan'],['all','Tümü']].map(([k,l])=><Button key={k} title={l} small secondary={filter!==k} onPress={()=>setFilter(k)}/>)}</Row>
 {myQueue.map(q=><Card key={q.id}><T bold>Dijital sıradasın · {directory.find(b=>b.id===q.business_id)?.name||'İşletme'}</T><Row><Badge title={`${queueInfo[q.id]?.position||'—'}. sıra`}/><T color={colors.muted}>Tahmini bekleme {queueInfo[q.id]?.wait_minutes??'—'} dk</T></Row><T size={11} color={colors.muted}>Süre, devam eden işin ve önündeki hizmetlerin tahminidir; randevu saati garantisi değildir.</T><Button title="Sıradan çık" small secondary onPress={()=>task.run(()=>act('queue_change',{id:q.id,state:'cancelled'}))}/></Card>)}
 {!list.length?<Empty title="Henüz bir randevu yok" body="Keşfet ekranında bir işletme ve usta seçerek ilk randevunu oluşturabilirsin."/>:list.map(a=>{const b=directory.find(b=>b.id===a.business_id)||rows.businesses?.find(b=>b.id===a.business_id),s=b?.staff?.find((s:DataRow)=>s.id===a.staff_id)||rows.staff?.find(s=>s.id===a.staff_id),service=b?.services?.find((s:DataRow)=>s.id===a.service_id)||rows.services?.find(s=>s.id===a.service_id),conversation=rows.conversations?.find(c=>c.appointment_id===a.id),location=rows.location_sessions?.find(l=>l.appointment_id===a.id&&l.revoked_at===null&&new Date(l.expires_at)>new Date()),own=a.customer_user_id===session?.user.id;return <Card key={a.id} style={{borderColor:a.status==='in_progress'?colors.coral+'80':colors.border}}><Row style={{justifyContent:'space-between'}}><View style={{flex:1,gap:4}}><T bold size={19}>{b?.name||'İşletme'} · {s?.name||'Usta'}</T><T color={colors.muted}>{service?.name||'Hizmet'} · {a.customer_name}</T></View><Badge title={statusLabel(a.status)} tone={a.status==='completed'?colors.mint:a.status==='cancelled'?colors.danger:colors.blue}/></Row><Row style={{justifyContent:'space-between'}}><T bold size={22} color={colors.blue}>{clock(a.starts_at)}</T><T color={colors.muted}>{dateLabel(a.starts_at)}</T><T bold>{money(Number(a.service_price)+Number(a.platform_fee))}</T></Row><T size={11} color={colors.muted}>Hizmet {money(a.service_price)} + platform {money(a.platform_fee)} · {statusLabel(a.source)}</T>
 <Row>{conversation&&<Button title="Sohbeti aç" small onPress={()=>openChat(conversation.id)}/>} {['confirmed','late'].includes(a.status)&&<><Button title="Ertele" small secondary onPress={()=>{setModal(a);setKind('reschedule');}}/><Button title="İptal et" small secondary onPress={()=>cancel(a)}/>{own&&<Button title={tracked===a.id?'Varış takibini durdur':'Süreli varış takibi'} small secondary onPress={()=>{if(tracked===a.id)void track(a);else{setModal(a);setKind('consent')}}}/>}</>}{own&&a.status==='completed'&&<Button title="Değerlendir" small secondary onPress={()=>{setModal(a);setKind('review');setBody('');}}/>}{b?.latitude&&<Button title="Yol tarifi" small secondary onPress={()=>void Linking.openURL(`https://www.google.com/maps/dir/?api=1&destination=${b.latitude},${b.longitude}`)}/>}</Row>
 {location&&<Card style={{padding:13,backgroundColor:colors.raised}}><Row><Badge title={location.eta_minutes!==null&&Date.now()+location.eta_minutes*60000>new Date(a.starts_at).getTime()?'Gecikebilir':'Yaklaşıyor'} tone={colors.coral}/><T bold>{location.distance_km!==null?Number(location.distance_km).toFixed(1)+' km':'Konum güncellemesi bekleniyor'}</T><T>{location.eta_minutes!==null?`~${location.eta_minutes} dk`:''}</T></Row><T size={10} color={colors.muted}>Son güncelleme {dateLabel(location.updated_at)} · Mesafe üzerinden tahmin, trafik içermez. {Date.now()-new Date(location.updated_at).getTime()>120000?'Konum güncel olmayabilir.':''}</T></Card>}
 </Card>})}
 {records.length>=250&&<Button title="Daha eski randevuları yükle" secondary onPress={()=>task.run(async()=>{const r=await page('appointments',records.length);setMore(m=>[...m,...r]);})}/>}<TaskStatus task={task}/>
 <Sheet open={manual} title="Manuel randevu oluştur" onClose={()=>setManual(false)}><Stack><Row>{permitted.map(s=><Button key={s.id} title={s.name} small secondary={staffId!==s.id} onPress={()=>{setStaffId(s.id);setServiceId('');}}/>)}</Row><Input label="Müşteri adı" value={customerName} onChangeText={setCustomerName}/><Row>{['phone','private','walk_in'].map(s=><Button key={s} title={statusLabel(s)} small secondary={source!==s} onPress={()=>setSource(s)}/>)}</Row><Row>{(rows.services||[]).filter(v=>v.active&&(rows.staff_services||[]).some(x=>x.staff_id===staffId&&x.service_id===v.id)).map(v=><Button key={v.id} title={v.name+' · '+money(v.price)} small secondary={serviceId!==v.id} onPress={()=>setServiceId(v.id)}/>)}</Row><Input label="Gün YYYY-AA-GG" value={day} onChangeText={setDay}/><Input label="Saat SS:DD" value={time} onChangeText={setTime}/><Button title="Randevuyu kaydet" disabled={!serviceId||task.busy} onPress={()=>task.run(async()=>{await act('book',{staff_id:staffId,service_id:serviceId,customer_name:customerName,source,starts_at:istanbul(day,time)});setManual(false);})}/><TaskStatus task={task}/></Stack></Sheet>
 <Sheet open={!!modal} title={kind==='consent'?'Süreli varış takibi':kind==='reschedule'?'Yeni randevu zamanı':kind==='review'?'Hizmeti değerlendir':'Randevuyu iptal et'} onClose={()=>setModal(null)}>
 {kind==='cancel'&&<Stack><T>Bu randevuyu iptal etmek istediğinde işletmeye ve ustaya haber verilir. Mevcut diğer randevular etkilenmez.</T><Button title="İptali onayla" onPress={()=>task.run(async()=>{await act('appointment_change',{appointment_id:modal?.id,status:'cancelled'});setModal(null);})}/></Stack>}
 {kind==='reschedule'&&<Stack><Input label="Yeni gün YYYY-AA-GG" value={day} onChangeText={setDay}/><Input label="Yeni saat SS:DD" value={time} onChangeText={setTime}/><T size={12} color={colors.muted}>Yeni saat sunucuda kontrol edilir. Müsait değilse mevcut randevun korunur.</T><Button title="Yeni zamanı onayla" onPress={()=>task.run(async()=>{await act('appointment_change',{appointment_id:modal?.id,starts_at:istanbul(day,time)});setModal(null);})}/></Stack>}
 {kind==='consent'&&<Stack><T>Bu randevu için konumun, kalan mesafen ve yaklaşık varış süren ilgili usta ve işletme yöneticisiyle paylaşılır.</T><T color={colors.muted}>Takip randevudan iki saat önce açılabilir, en fazla iki saat sürer. Uygulama açıkken konum güncellenir. Takibi istediğin anda durdurabilirsin; randevun etkilenmez.</T><T color={colors.muted}>Hizmet tamamlanınca, randevu iptal edilince veya izin süresi dolunca konum paylaşımı sona erer.</T><Button title="Bu randevu için izin ver ve başlat" onPress={()=>{if(modal)void track(modal);setModal(null);}}/></Stack>}
 {kind==='review'&&<Stack><Row>{[1,2,3,4,5].map(n=><Button key={n} title={String(n)+' ★'} small secondary={rating!==String(n)} onPress={()=>setRating(String(n))}/>)}</Row><Input label="Yorumun" value={body} onChangeText={setBody} multiline/><Button title="Değerlendirmemi kaydet" onPress={()=>task.run(async()=>{await act('review',{appointment_id:modal?.id,rating:Number(rating),body});setModal(null);})}/></Stack>}
 <TaskStatus task={task}/></Sheet></Stack></Fade>;
}
