import React,{useEffect,useState} from 'react';
import {View,Image,Pressable,Linking,useWindowDimensions} from 'react-native';
import * as Location from 'expo-location';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {LinearGradient} from 'expo-linear-gradient';
import {api,useData,Row as DataRow,money,dateLabel,clock,dayAfter,istanbul,km,statusLabel} from './data';
import {Avatar,Badge,Button,Card,Empty,Fade,Head,Input,Row,Sheet,Stack,T,TaskStatus,useTask,useTheme,Busy} from './ui';
import MapView from './MapView';
export function Discover({onLogin}:{onLogin:()=>void}){
 const {directory,session,act,rows}=useData(),{colors}=useTheme(),{width}=useWindowDimensions(),task=useTask();
 const [search,setSearch]=useState(''),[position,setPosition]=useState<{latitude:number;longitude:number}|null>(null),[business,setBusiness]=useState<DataRow|null>(null),[service,setService]=useState<DataRow|null>(null),[staff,setStaff]=useState<DataRow|null>(null),[day,setDay]=useState(dayAfter(0)),[slots,setSlots]=useState<string[]>([]),[slot,setSlot]=useState(''),[code,setCode]=useState(''),[appliedCode,setAppliedCode]=useState(''),[quote,setQuote]=useState<DataRow|null>(null),[fetching,setFetching]=useState(false),[requested,setRequested]=useState(false),[repeat,setRepeat]=useState('1');
 useEffect(()=>{AsyncStorage.getItem('dbstyle-referral').then(c=>{if(c){setCode(c);setAppliedCode(c);}});},[]);
 useEffect(()=>{if(business){const latest=directory.find(b=>b.id===business.id);if(latest)setBusiness(latest);}},[directory]);
 useEffect(()=>{setSlot('');setSlots([]);setQuote(null);if(!session||!service||!staff)return;let valid=true;setFetching(true);Promise.all([api('slots',{staff_id:staff.id,service_id:service.id,date:day}),api('quote',{staff_id:staff.id,service_id:service.id,code:appliedCode||undefined})]).then(([s,q])=>{if(valid){setSlots(s);setQuote(q);}}).catch(e=>{void task.run(async()=>{throw e;});}).finally(()=>valid&&setFetching(false));return()=>{valid=false};},[staff?.id,service?.id,day,session?.user.id,appliedCode]);
 const list=directory.filter(b=>`${b.name} ${b.city} ${b.address} ${b.description}`.toLocaleLowerCase('tr-TR').includes(search.toLocaleLowerCase('tr-TR'))).map<DataRow>(b=>({...b,distance:position&&b.latitude!=null?km(position.latitude,position.longitude,Number(b.latitude),Number(b.longitude)):null})).sort((a,b)=>position?(a.distance??9999)-(b.distance??9999):0);
 const open=(b:DataRow)=>{setBusiness(b);setService(null);setStaff(null);setSlot('');setQuote(null);setRequested(false);};
 const nearby=()=>task.run(async()=>{const p=await Location.requestForegroundPermissionsAsync();if(p.status!=='granted')throw new Error('Konum izni verilmedi. İşletmeleri arayarak keşfedebilirsin.');const loc=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});setPosition(loc.coords);},'İşletmeler mesafeye göre sıralandı.');
 const applyCode=()=>task.run(async()=>{if(!service||!staff)return;const q=await api('quote',{staff_id:staff.id,service_id:service.id,code});setQuote(q);setAppliedCode(code);},'Fiyat güncellendi.');
 const book=()=>task.run(async()=>{if(!staff||!service||!slot||!quote)throw new Error('Hizmet, usta ve saat seç.');const r=await act(Number(repeat)>1?'repeat_book':'book',{staff_id:staff.id,service_id:service.id,starts_at:slot,code:appliedCode||undefined,count:Number(repeat),expected_total:quote.total});setRequested(true);setSlot('');return r;},'Randevun oluşturuldu. Randevularım ekranında görebilirsin.');
 const wait=(type:string)=>task.run(async()=>{if(!staff||!service)throw new Error('Önce hizmet ve usta seç.');await act(type,{staff_id:staff.id,service_id:service.id,starts_at:istanbul(day,'09:00'),ends_at:istanbul(day,'21:00'),message:'Seçtiğim gün için uygun saat talep ediyorum.'});},type==='waitlist'?'Bekleme listesine katıldın. Boşluk oluştuğunda haber vereceğiz.':'Talebin işletmeye iletildi.');
 return <Fade><Stack><LinearGradient colors={['#163044','#132032','#241d33']} start={{x:0,y:0}} end={{x:1,y:1}} style={{padding:width>800?36:25,borderRadius:27,gap:19,overflow:'hidden'}}><Badge title="STİLİN İÇİN AYRILMIŞ BİR SAAT" tone="#72b6ff"/><T size={width>800?43:31} color="#f5f8fc" bold>Bir sonraki stilin,{ '\n'}bir randevu uzağında.</T><T color="#aebed3" style={{maxWidth:540}}>Ustanı keşfet. Müsait saati seç. Fiyatı önceden bil.{ '\n'}Günün geri kalanı sana kalsın.</T><Row><Button title="Yakınımdaki işletmeler" onPress={nearby}/>{!session&&<Button title="Hesabımı oluştur" secondary onPress={onLogin}/>}</Row></LinearGradient>
 <Head eyebrow="Studio seçkisi" title="İyi stil burada başlar" subtitle={`${directory.length} onaylı işletme · Güncel hizmet ve usta bilgileri`}/><Input label="İşletme, şehir veya adres ara" value={search} onChangeText={setSearch} placeholder="Berberini keşfet…"/><TaskStatus task={task}/>
 {!list.length?<Empty title="Yeni stüdyolar için yer hazır" body="Onaylanan işletmeler, ustaları ve gerçek fiyatları burada görünecek. İşletmeni kaydetmek için hesabını aç." action={!session?<Button title="Başla" onPress={onLogin}/>:undefined}/>:<Row style={{alignItems:'stretch'}}>{list.map(b=><Pressable key={b.id} onPress={()=>open(b)} style={{width:width>1200?'32%':width>750?'48.7%':'100%'}}><Card style={{padding:0,overflow:'hidden',height:'100%'}}>{b.cover_url?<Image source={{uri:b.cover_url}} style={{height:176,width:'100%'}}/>:<LinearGradient colors={['#153648','#19304f','#3d2542']} style={{height:154,padding:24,justifyContent:'space-between'}}><T color="#84c5ff" size={10} bold style={{letterSpacing:3}}>BARBER / HAIR STUDIO</T><T color="#e3edfb" size={43} bold style={{letterSpacing:-2}}>{b.name.slice(0,2).toUpperCase()}</T><View style={{height:2,width:70,backgroundColor:'#4de0c7'}}/></LinearGradient>}<View style={{padding:20,gap:13}}><Row style={{justifyContent:'space-between'}}><T bold size={20} style={{flex:1}}>{b.name}</T><Badge title={b.rating?`★ ${b.rating}`:'Yeni'}/></Row><T size={12} color={colors.muted}>{b.city} · {b.address}</T><Row>{b.staff.slice(0,3).map((s:DataRow)=><Avatar key={s.id} name={s.name} url={s.photo_url} size={32}/>)}<T size={11} color={colors.muted}>{b.staff.length} usta</T>{b.distance!==null&&<Badge title={`${b.distance.toFixed(1)} km`}/>}</Row><Row style={{justifyContent:'space-between'}}><T size={12} color={colors.muted}>{b.services.length?`${money(Math.min(...b.services.map((s:DataRow)=>Number(s.price))))}’den başlayan hizmet`:'Hizmetler hazırlanıyor'}</T><T size={12} color={colors.mint} bold>Stüdyoyu aç ↗</T></Row></View></Card></Pressable>)}</Row>}
 <Sheet open={!!business} title={business?.name||'İşletme'} onClose={()=>setBusiness(null)}>{business&&<Stack><Row><Avatar name={business.name} url={business.logo_url} size={60}/><View style={{flex:1,gap:5}}><T size={12} color={colors.muted}>{business.address}</T><Row><Badge title={business.rating?`★ ${business.rating} · ${business.review_count} yorum`:'Yeni stüdyo'}/><T size={11} color={colors.muted}>{business.city}</T></Row></View></Row>{business.description&&<T color={colors.muted}>{business.description}</T>}
 {business.gallery?.length>0&&<Row>{business.gallery.map((url:string,i:number)=><Image key={i} source={{uri:url}} style={{width:92,height:92,borderRadius:14}}/>)}</Row>}
 {business.latitude!=null&&business.longitude!=null&&<><MapView latitude={Number(business.latitude)} longitude={Number(business.longitude)}/><Button title="Yol tarifi" secondary small onPress={()=>void Linking.openURL(`https://www.google.com/maps/dir/?api=1&destination=${business.latitude},${business.longitude}`)}/></>}
 {business.phone&&<Button title={'Ara · '+business.phone} secondary small onPress={()=>void Linking.openURL('tel:'+business.phone)}/>}
 <T bold size={18}>01  Hizmetini seç</T><Stack style={{gap:10}}>{business.services.map((v:DataRow)=><Pressable key={v.id} onPress={()=>{setService(v);setStaff(null);setRequested(false);}}><Card style={{padding:15,borderColor:service?.id===v.id?colors.mint:colors.border}}><Row style={{justifyContent:'space-between'}}><View style={{flex:1}}><T bold>{v.name}</T><T color={colors.muted} size={11}>{v.duration_minutes} dk {v.buffer_minutes>0?`· ${v.buffer_minutes} dk hazırlık`:''}</T></View><T bold color={colors.mint}>{money(v.price)}</T></Row></Card></Pressable>)}</Stack>
 <T bold size={18}>02  Ustanı seç</T><Row>{business.staff.filter((s:DataRow)=>!service||!(rows.staff_services||[]).length||(rows.staff_services||[]).some(x=>x.staff_id===s.id&&x.service_id===service.id)).map((s:DataRow)=><Pressable key={s.id} onPress={()=>setStaff(s)} style={{minWidth:130,flex:1}}><Card style={{alignItems:'center',padding:15,borderColor:staff?.id===s.id?colors.blue:colors.border}}><Avatar name={s.name} url={s.photo_url} size={54}/><T bold>{s.name}</T><Badge title={statusLabel(s.state)} tone={s.state==='available'?colors.mint:colors.coral}/>{s.busy_until&&<T size={10} color={colors.muted}>Tahmini bitiş {clock(s.busy_until)}</T>}{s.bio&&<T color={colors.muted} size={11} style={{textAlign:'center'}}>{s.bio}</T>}</Card></Pressable>)}</Row>
 {!session?<Card><T>Randevu için hesabınla giriş yap.</T><Button title="Giriş yap / kayıt ol" onPress={()=>{setBusiness(null);onLogin();}}/></Card>:<><T bold size={18}>03  Sana uygun saat</T><Row>{Array.from({length:7},(_,i)=>dayAfter(i)).map(d=><Button key={d} small secondary={day!==d} title={new Date(d+'T12:00:00+03:00').toLocaleDateString('tr-TR',{day:'numeric',month:'short'})} onPress={()=>setDay(d)}/>)}</Row><Input label="Başka bir tarih (YYYY-AA-GG)" value={day} onChangeText={setDay}/>{fetching?<Busy/>:<Row>{slots.map(t=><Button key={t} title={clock(t)} small secondary={slot!==t} onPress={()=>setSlot(t)}/>)}</Row>}
 {service&&staff&&!slots.length&&!fetching&&<Card><T bold>Bu gün için boş saat bulunamadı</T><Button title="Boş saat olduğunda haber ver" secondary onPress={()=>wait('waitlist')}/><Button title="İşletmeye müsaitlik talebi gönder" secondary onPress={()=>wait('availability_request')}/></Card>}
 {staff&&service&&<><Input label="Bu ustaya özel indirim kodun" value={code} onChangeText={setCode}/><Button title="Kodu fiyatıma uygula" secondary small onPress={applyCode}/><Button title="Çat kapı sırasına katıl" secondary small onPress={()=>task.run(()=>act('queue_add',{staff_id:staff.id,service_id:service.id}),'Dijital sıraya katıldın.')}/></>}
 {quote&&<Card style={{borderColor:colors.mint+'60'}}><T bold size={17}>Fiyatın, tüm detaylarıyla</T><Row style={{justifyContent:'space-between'}}><T color={colors.muted}>Hizmet bedeli</T><T>{money(quote.base_price)}</T></Row>{Number(quote.discount)>0&&<Row style={{justifyContent:'space-between'}}><T color={colors.mint}>İndirim</T><T color={colors.mint}>− {money(quote.discount)}</T></Row>}<Row style={{justifyContent:'space-between'}}><T color={colors.muted}>Platform hizmet bedeli</T><T>{money(quote.platform_fee)}</T></Row><Row style={{justifyContent:'space-between',borderTopWidth:1,borderColor:colors.border,paddingTop:12}}><T bold>Nihai müşteri fiyatı</T><T size={25} bold color={colors.mint}>{money(quote.total)}</T></Row><T size={11} color={colors.muted}>Ödeme hizmet sonrası işletmeye yapılır. Online kart tahsilatı alınmaz.</T></Card>}
 {slot&&<><Input label="Haftalık tekrar sayısı (1–8)" value={repeat} onChangeText={setRepeat} numeric/><Button title={`${clock(slot)} · Randevumu onayla`} disabled={task.busy||requested} onPress={book}/></>}
 <TaskStatus task={task}/></>}
 {business.reviews?.length>0&&<><T bold size={18}>Stüdyonun yorumları</T>{business.reviews.map((r:DataRow,i:number)=><Card key={i}><T color={colors.coral}>{'★'.repeat(r.rating)}</T><T>{r.body||'Müşteri puan verdi.'}</T><T color={colors.muted} size={10}>{dateLabel(r.created_at)}</T></Card>)}</>}
 </Stack>}</Sheet></Stack></Fade>;
}
