import React,{useEffect,useState} from 'react';
import {View,Linking} from 'react-native';
import * as Crypto from 'expo-crypto';
import {supabase,useData,Row as DataRow,money,dateLabel,statusLabel,today,istanbul,dayAfter} from './data';
import {Badge,Bars,Button,Card,Empty,Fade,Head,Input,Metric,Row,Sheet,Stack,T,TaskStatus,useTask,useTheme,Avatar} from './ui';
import {exportReport,uploadMedia,uploadReceipt,receiptUrl} from './files';
export function Management({admin=false}:{admin?:boolean}){
 const {rows,act,isAdmin,isManager,session,refresh}=useData(),{colors}=useTheme(),task=useTask();
 const businesses=(rows.businesses||[]).filter(b=>isAdmin||(rows.business_members||[]).some(m=>m.business_id===b.id&&m.user_id===session?.user.id&&m.active&&['owner','manager'].includes(m.role)));
 const [selected,setSelected]=useState(''),[period,setPeriod]=useState('today'),[dateFrom,setDateFrom]=useState(today()),[dateTo,setDateTo]=useState(today()),[dashboard,setDashboard]=useState<DataRow>({}),[modal,setModal]=useState(''),[form,setForm]=useState<Record<string,string>>({}),[edited,setEdited]=useState<DataRow|null>(null),[sourcePolicy,setSourcePolicy]=useState<string[]>(['platform']),[affects,setAffects]=useState(false),[key,setKey]=useState(Crypto.randomUUID());
 const b=businesses.find(b=>b.id===selected)||businesses[0];
 const from=period==='today'?istanbul(today()):period==='week'?new Date(Date.now()-7*86400000).toISOString():period==='month'?new Date(Date.now()-30*86400000).toISOString():period==='all'?'2000-01-01T00:00:00Z':istanbul(dateFrom);
 const end=period==='custom'?istanbul(dateTo,'23:59'):new Date(Date.now()+86400000).toISOString();
 useEffect(()=>{if(!isManager)return;let alive=true;supabase.rpc('dashboard',{date_from:from,date_to:end}).then(r=>{if(r.error)void task.run(async()=>{throw r.error;});else if(alive)setDashboard(r.data||{});});return()=>{alive=false}},[from,dateTo,period,rows.service_sessions,rows.business_balances,isManager]);
 const update=(name:string,value:string)=>setForm(f=>({...f,[name]:value}));
 const open=(name:string,data:DataRow|null=null)=>{setEdited(data);setForm({name:data?.name||'',price:String(data?.price||''),duration:String(data?.duration_minutes||30),buffer:String(data?.buffer_minutes||0),email:'',max_discount_pct:String(data?.max_discount_pct||0),address:data?.address||'',city:data?.city||'',phone:data?.phone||'',description:data?.description||'',latitude:String(data?.latitude??''),longitude:String(data?.longitude??''),weekday:'1',opens:'09:00',closes:'20:00',amount:'',method:'transfer',paid_at:today(),note:'',period:'weekly',day:'1',next_due:dayAfter(7),loyalty_every:'10',title:'',body:'',audience:'all',loyalty_percent:'15',recall_after_days:'0',role:'staff',active:'true',ledger_id:data?.id||'',reason:'',bio:data?.bio||'',specialties:(data?.specialties||[]).join(', ')});setKey(Crypto.randomUUID());setModal(name);};
 const save=(action:string,data:DataRow,close=true)=>task.run(async()=>{const r=await act(action,{business_id:b?.id,...data});if(close)setModal('');return r;});
 const filteredStaff=(rows.staff||[]).filter(s=>s.business_id===b?.id),services=(rows.services||[]).filter(s=>s.business_id===b?.id),balance=rows.business_balances?.find(s=>s.business_id===b?.id),schedule=rows.payment_schedules?.find(s=>s.business_id===b?.id),requests=(rows.payment_requests||[]).filter(p=>admin||p.business_id===b?.id);
 const fin=dashboard.finance||{},stats=dashboard.services||{}, businessStats=dashboard.businesses?.find((r:DataRow)=>r.id===b?.id),performance=(dashboard.staff||[]).filter((r:DataRow)=>r.business_id===b?.id);
 const report=()=>[['İşletme','Durum','Dönem müşteri','Hizmet hasılatı (TL)','Tahakkuk (TL)','Onaylı tahsilat (TL)','Platform borcu (TL)'],...(dashboard.businesses||[]).map((r:DataRow)=>[r.name,statusLabel(r.status),Number(r.customers),Number(r.revenue),Number(r.accrued||0),Number(r.paid||0),Number(r.balance||0)])] as (string|number)[][];
 return <Fade><Stack><Head eyebrow={admin?'Platform yönetimi':'İşletme çalışma alanı'} title={admin?'DraBornStyle kontrol merkezi':b?.name||'İşletmeni büyüt'} subtitle={admin?'Hizmetlerden tahakkuka. Tahsilatlardan büyümeye.':'Ustaların, müşterilerin ve kazancın aynı ekranda.'} action={<Button title="＋ İşletme kaydet" small onPress={()=>open('business')}/>}/>
 {!isManager&&!businesses.length&&<Empty title="İşletmen için daha iyi bir gün" body="İşletmeni kaydet, başvurun onaylandıktan sonra ustalarını ve hizmetlerini ekle. Çalışma akışın hazır olacak." action={<Button title="İşletmemi kaydet" onPress={()=>open('business')}/>}/>}
 <Row>{businesses.map(biz=><Button key={biz.id} title={biz.name} small secondary={b?.id!==biz.id} onPress={()=>setSelected(biz.id)}/>)}</Row>
 {isManager&&<><Row>{[['today','Bugün'],['week','7 gün'],['month','30 gün'],['all','Tüm zamanlar'],['custom','Tarih aralığı']].map(([k,l])=><Button key={k} title={l} small secondary={period!==k} onPress={()=>setPeriod(k)}/>)}</Row>{period==='custom'&&<Row><Input label="Başlangıç YYYY-AA-GG" value={dateFrom} onChangeText={setDateFrom} style={{flex:1}}/><Input label="Bitiş YYYY-AA-GG" value={dateTo} onChangeText={setDateTo} style={{flex:1}}/></Row>}
 <Row style={{alignItems:'stretch'}}><Metric label={admin?'Toplam platform tahakkuku':'Hizmet hasılatı'} value={money(admin?fin.accrued:businessStats?.revenue)} tone={colors.mint}/><Metric label={admin?'Onaylı tahsilat':'Bu dönem müşteri'} value={admin?money(fin.paid):String(businessStats?.customers||0)}/><Metric label={admin?'Tahsilat bekleyen bakiye':'Platform borcun'} value={money(admin?fin.balance:balance?.balance)} tone={colors.coral}/><Metric label="Dönem platform geliri" value={money(admin?dashboard.period_commission:performance.reduce((n:number,s:DataRow)=>n+Number(s.fees),0))}/></Row>
 {admin&&<Row style={{alignItems:'stretch'}}><Metric label="Aktif işletmeler" value={String(businesses.filter(b=>b.status==='active').length)}/><Metric label="Aktif ustalar" value={String((rows.staff||[]).filter(s=>s.active).length)}/><Metric label="Tamamlanan işlemler" value={String(stats.count||0)}/><Metric label="Dönem tahsilatı" value={money(dashboard.period_collections)}/></Row>}
 {b&&<Card style={{borderColor:colors.blue+'50'}}><Row style={{justifyContent:'space-between'}}><Row><Avatar name={b.name} url={b.logo_url} size={55}/><View><T size={21} bold>{b.name}</T><T color={colors.muted} size={12}>{b.city} · {b.address}</T></View></Row><Badge title={statusLabel(b.status)} tone={b.status==='active'?colors.mint:colors.coral}/></Row>{b.status!=='active'&&<T color={colors.coral}>İşletme aktif olduğunda müşteriler randevu alabilir ve ustalar işlem başlatabilir.</T>}<Row><Button title="Vitrini düzenle" small secondary onPress={()=>open('edit_business',b)}/><Button title="Kapak yükle" small secondary onPress={()=>task.run(async()=>{const url=await uploadMedia(b.id,'cover');if(url)await act('business_update',{business_id:b.id,cover_url:url});})}/><Button title="Logo yükle" small secondary onPress={()=>task.run(async()=>{const url=await uploadMedia(b.id,'logo');if(url)await act('business_update',{business_id:b.id,logo_url:url});})}/><Button title="Galeriye görsel ekle" small secondary onPress={()=>task.run(async()=>{const url=await uploadMedia(b.id,'gallery');if(url)await act('business_update',{business_id:b.id,gallery:[...(b.gallery||[]),url]});})}/>{isAdmin&&<><Button title="İşletmeyi onayla" small onPress={()=>save('business_status',{status:'active'},false)}/><Button title="Durdur" small secondary onPress={()=>save('business_status',{status:'suspended'},false)}/><Button title="Komisyon anlaşması" small secondary onPress={()=>{const cr=rows.commission_rules?.find(r=>r.business_id===b.id);open('commission');setForm(f=>({...f,fee:String(cr?.fixed_fee??20),percent:String(cr?.percentage||0)}));setSourcePolicy(cr?.sources||['platform']);setAffects(cr?.discount_affects_commission||false);}}/></>}</Row></Card>}
 {admin&&<Card><Head title="İşletme gelirleri" subtitle="Her işletmede tahakkuk, tahsilat ve bakiye ayrı izlenir"/>{(dashboard.businesses||[]).map((r:DataRow)=><View key={r.id} style={{borderTopWidth:1,borderColor:colors.border,paddingVertical:13,gap:8}}><Row style={{justifyContent:'space-between'}}><Button title={r.name} small secondary onPress={()=>setSelected(r.id)}/><Badge title={statusLabel(r.status)}/></Row><Row><T size={12}>{r.customers} işlem</T><T size={12} color={colors.mint}>{money(r.accrued)} tahakkuk</T><T size={12}>{money(r.paid)} tahsilat</T><T size={12} color={colors.coral}>{money(r.balance)} bakiye</T></Row></View>)}</Card>}
 <Head title="Ustaların ve hizmetlerin" subtitle="Yetki, çalışma programı ve fiyat yönetimi" action={<Row><Button title="＋ Usta" small onPress={()=>open('staff')}/><Button title="＋ Hizmet" small secondary onPress={()=>open('service')}/></Row>}/>
 <Row style={{alignItems:'stretch'}}>{filteredStaff.map(s=><Card key={s.id} style={{flex:1,minWidth:220}}><Row><Avatar name={s.name} url={s.photo_url}/><View style={{flex:1}}><T bold>{s.name}</T><Badge title={statusLabel(rows.staff_availability?.find(a=>a.staff_id===s.id)?.state||'available')}/></View></Row><T color={colors.muted} size={11}>{s.can_discount?`En fazla %${s.max_discount_pct} indirim`:'İndirim yetkisi kapalı'}</T><Row><Button title="Düzenle" small secondary onPress={()=>open('staff',s)}/><Button title="Program" small secondary onPress={()=>open('schedule',s)}/><Button title={s.active?'Pasife al':'Aktife al'} small secondary onPress={()=>save('staff_save',{staff_id:s.id,active:!s.active},false)}/><Button title="Fotoğraf" small secondary onPress={()=>task.run(async()=>{const url=await uploadMedia(b.id,'staff');if(url)await act('staff_save',{business_id:b.id,staff_id:s.id,photo_url:url});})}/></Row></Card>)}</Row>
 <Card>{services.length?services.map(s=><Row key={s.id} style={{paddingVertical:10,borderBottomWidth:1,borderColor:colors.border,justifyContent:'space-between'}}><View style={{flex:1}}><T bold>{s.name}</T><T size={11} color={colors.muted}>{s.duration_minutes} dk · Hazırlık {s.buffer_minutes} dk · {s.active?'Aktif':'Pasif'}</T></View><T color={colors.mint} bold>{money(s.price)}</T><Button title="Düzenle" small secondary onPress={()=>open('service',s)}/></Row>):<T color={colors.muted}>İlk hizmetini fiyatı ve süresiyle birlikte ekle.</T>}</Card>
 <Card><Head title="Çalışan performansı" subtitle="Bu dönem · Hizmet hasılatı ve platform bedeli"/>{performance.map((s:DataRow)=><Row key={s.id} style={{justifyContent:'space-between',paddingVertical:10,borderBottomWidth:1,borderColor:colors.border}}><T bold style={{flex:1}}>{s.name}</T><T size={12}>{s.customers} müşteri</T><T size={12} color={colors.mint}>{money(s.revenue)}</T><T size={12} color={colors.muted}>{money(s.fees)} platform</T></Row>)}</Card>
 <Row style={{alignItems:'stretch'}}><Card style={{flex:1,minWidth:250}}><T size={18} bold>Yoğun saatler</T><Bars items={dashboard.hours||[]} label={r=>r.hour+':00'} value={r=>Number(r.customers)}/></Card><Card style={{flex:1,minWidth:250}}><T size={18} bold>En çok tercih edilen hizmetler</T><Bars items={dashboard.popular_services||[]} label={r=>r.name} value={r=>Number(r.customers)}/></Card></Row>
 <Card><T bold size={18}>Akıllı günlük kapanış</T><Row><Badge title={`${stats.count||0} hizmet`}/><Badge title={`${money(stats.revenue)} hizmet hasılatı`}/><Badge title={`${money(stats.discount)} indirim`}/><Badge title={`${money(stats.collected)} işletme tahsilatı`}/></Row><Row><T color={colors.muted}>Nakit {money(stats.cash)} · Kart {money(stats.card)}</T><T color={colors.muted}>Ortalama {stats.average_minutes||0} dk</T></Row><Row><T color={colors.muted}>Tekrar gelen müşteri oranı %{dashboard.repeat_rate||0}</T><T color={colors.muted}>Gelecek hafta tahmini {money(dashboard.forecast_week)}</T></Row><T size={11} color={colors.muted}>Tahmin son 28 günün haftalık ortalamasıdır. Çok işletmen varsa genel grafikler erişebildiğin işletmeleri kapsar.</T></Card>
 {b&&<Card><Head title="Platform ödemeleri" subtitle={`Sıradaki ödeme günü ${schedule?.next_due||'—'}`}/><Row><Metric label="Toplam tahakkuk" value={money(balance?.accrued)}/><Metric label="Onaylı ödemelerin" value={money(balance?.paid)}/><Metric label="Kalan borcun" value={money(balance?.balance)} tone={colors.coral}/></Row><Row><Button title="Ödeme bildir" onPress={()=>open('payment')}/><Button title="Ödeme günümü seç" secondary onPress={()=>open('payment_schedule')}/><Button title="Çalışan yetkileri" secondary onPress={()=>open('members')}/><Button title="Sadakat ve otomatik yanıt" secondary onPress={()=>(()=>{open('settings');const bs=rows.business_settings?.find(r=>r.business_id===b.id);setForm(f=>({...f,loyalty_every:String(bs?.loyalty_every??0),loyalty_percent:String(bs?.loyalty_percent??0),recall_after_days:String(bs?.recall_after_days??0),auto_reply:bs?.auto_reply||''}));})()}/><Button title="Gider kaydet" secondary onPress={()=>open('expense')}/></Row><T size={11} color={colors.muted}>Ödeme bildirimi borcu azaltmaz. Admin kontrolü ve onayı sonrası kısmi ödeme dağıtılır.</T></Card>}
 <Head title={admin?'Ödeme kontrol talepleri':'Ödeme geçmişin'}/>{requests.slice(0,40).map(p=><Card key={p.id}><Row style={{justifyContent:'space-between'}}><View><T bold size={19}>{money(p.amount)}</T><T color={colors.muted} size={11}>{businesses.find(b=>b.id===p.business_id)?.name} · {dateLabel(p.paid_at)} · {statusLabel(p.method)}</T></View><Badge title={statusLabel(p.status)} tone={p.status==='approved'?colors.mint:colors.coral}/></Row>{p.note&&<T color={colors.muted} size={12}>{p.note}</T>}<Row>{(rows.payment_receipts||[]).filter(r=>r.request_id===p.id).map(r=><Button key={r.id} title="Dekontu aç (120 sn)" small secondary onPress={()=>task.run(async()=>{await Linking.openURL(await receiptUrl(r.storage_path));})}/>)}{p.status==='pending'&&<Button title="Dekont ekle" small secondary onPress={()=>task.run(async()=>{await uploadReceipt(p.business_id,p.id);await refresh();})}/>} {admin&&['pending','reviewing'].includes(p.status)&&<><Button title="Ödemeyi onayla" small onPress={()=>save('payment_review',{id:p.id,status:'approved'},false)}/><Button title="İncele" small secondary onPress={()=>save('payment_review',{id:p.id,status:'reviewing'},false)}/><Button title="Reddet" small secondary onPress={()=>save('payment_review',{id:p.id,status:'rejected'},false)}/></>}</Row></Card>)}
 {(rows.availability_requests||[]).filter(r=>r.business_id===b?.id&&r.status==='pending').map(r=><Card key={r.id}><T bold>Müsaitlik talebi · {dateLabel(r.starts_at)}</T><T>{r.message}</T><T size={11} color={colors.muted}>Önce çalışma programını düzenle; müşteri uygun saati kendisi onaylayacak.</T><Row><Button title="Takvim güncellendi" small onPress={()=>save('availability_reply',{id:r.id,status:'offered'},false)}/><Button title="Uygun değil" small secondary onPress={()=>save('availability_reply',{id:r.id,status:'rejected',message:'Bu zaman için ek müsaitlik açılamadı.'},false)}/></Row></Card>)}
 <Card><Head title="Raporunu dışa aktar" subtitle="Yetkin kapsamındaki gerçek finans ve performans verileri"/><Row>{['xlsx','csv','pdf'].map(f=><Button key={f} title={f.toUpperCase()} secondary onPress={()=>task.run(()=>exportReport(f,report()),'Rapor hazırlandı.')}/>)}</Row></Card>
 {admin&&<><Card><Button title="Sistem duyurusu oluştur" small secondary onPress={()=>open('announcement')}/><Head title="Yetkili platform yöneticileri" action={<Button title="Admin yetkisi düzenle" small secondary onPress={()=>open('admins')}/>}/>{(rows.admin_users||[]).map(r=><Row key={r.user_id}><T size={12}>{rows.profiles?.find(p=>p.id===r.user_id)?.display_name||r.user_id}</T><Badge title={r.active?'Aktif':'Kapalı'}/></Row>)}</Card><Card><Head title="Komisyon denetimi" subtitle="Düzeltmeler gerekçe ve işlem sahibiyle kaydedilir"/>{(rows.commission_ledger||[]).filter(l=>l.business_id===b?.id).slice(0,30).map(l=><Row key={l.id} style={{paddingVertical:8,borderBottomWidth:1,borderColor:colors.border}}><T size={11} style={{flex:1}}>{dateLabel(l.created_at)} · {filteredStaff.find(s=>s.id===l.staff_id)?.name} · {statusLabel(l.source)}</T><T size={12}>{money(l.amount)} / {money(l.paid)} tahsil</T><Button title="Düzelt" small secondary onPress={()=>open('adjust',l)}/></Row>)}</Card><Head title="Destek ve denetim"/>{(rows.support_requests||[]).slice(0,20).map(r=><Card key={r.id}><Row><Badge title={r.kind}/><Badge title={statusLabel(r.status)}/><T size={11}>{dateLabel(r.created_at)}</T></Row><T>{r.body}</T><Button title={r.kind==='data_delete'?'Veri silme talebini sonuçlandır':'Çözüldü olarak kaydet'} small secondary onPress={()=>save(r.kind==='data_delete'?'data_erase':'support_resolve',{id:r.id,status:'resolved'},false)}/></Card>)}<Card><T bold>Son denetim hareketleri</T>{(rows.admin_logs||[]).slice(0,15).map(r=><T key={r.id} size={11} color={colors.muted}>{dateLabel(r.created_at)} · {r.action} · {r.actor_id?.slice(0,8)}</T>)}</Card></>}
 </>}
 <TaskStatus task={task}/>
 <Sheet open={!!modal} title={({business:'İşletme başvurusu',edit_business:'İşletme vitrini',staff:'Çalışan yönetimi',service:'Hizmet ve fiyat',schedule:'Haftalık çalışma programı',payment:'Platform ödeme bildirimi',commission:'İşletme komisyon anlaşması',payment_schedule:'Ödeme periyodu',expense:'İşletme gideri',settings:'Sadakat ve mesaj ayarları',members:'İşletme çalışan yetkileri',admins:'Platform admin yetkilendirme',adjust:'Gerekçeli komisyon düzeltmesi',announcement:'Sistem duyurusu'} as any)[modal]||'Yönetim'} onClose={()=>setModal('')}>
 {['business','edit_business'].includes(modal)&&<Stack>{[['name','İşletme adı'],['address','Açık adres'],['city','Şehir'],['phone','Telefon'],['description','İşletme hakkında'],['latitude','Enlem'],['longitude','Boylam']].map(([k,l])=><Input key={k} label={l} value={form[k]||''} onChangeText={v=>update(k,v)}/>)}<Button title={modal==='business'?'Başvuruyu gönder':'Vitrini kaydet'} onPress={()=>save(modal==='business'?'business_create':'business_update',{...form,business_id:edited?.id||b?.id})}/><T size={11} color={colors.muted}>Başvurular platform yöneticisi tarafından onaylanır. Müşteri fiyatında platform hizmet bedeli ayrıca gösterilir.</T></Stack>}
 {modal==='staff'&&<Stack><Input label="Ustanın adı" value={form.name} onChangeText={v=>update('name',v)}/><Input label="Kayıtlı hesap e-postası (isteğe bağlı)" value={form.email} onChangeText={v=>update('email',v)} placeholder={edited?'Boş bırakırsan mevcut hesap korunur':'Usta önce hesap oluşturmalı'}/><Input label="Usta hakkında" value={form.bio} onChangeText={v=>update('bio',v)} multiline/><Input label="Uzmanlıklar (virgülle ayır)" value={form.specialties} onChangeText={v=>update('specialties',v)}/><Input label="İndirim sınırı (%) · 0 yetkiyi kapatır" value={form.max_discount_pct} onChangeText={v=>update('max_discount_pct',v)} numeric/><Input label="Haftalık hizmet hasılatı hedefi (TL)" value={form.weekly_goal||String(edited?.weekly_goal||0)} onChangeText={v=>update('weekly_goal',v)} numeric/><Button title="Ustayı kaydet" onPress={()=>save('staff_save',{...form,specialties:form.specialties.split(',').map(s=>s.trim()).filter(Boolean),staff_id:edited?.id,can_discount:Number(form.max_discount_pct)>0,max_discount_pct:Number(form.max_discount_pct),weekly_goal:Number(form.weekly_goal||0)})}/></Stack>}
 {modal==='service'&&<Stack><Input label="Hizmet adı" value={form.name} onChangeText={v=>update('name',v)}/><Input label="İşletme hizmet fiyatı (TL)" value={form.price} onChangeText={v=>update('price',v)} numeric/><Input label="Hizmet süresi (dakika)" value={form.duration} onChangeText={v=>update('duration',v)} numeric/><Input label="Hazırlık süresi (dakika)" value={form.buffer} onChangeText={v=>update('buffer',v)} numeric/><Button title="Hizmeti kaydet" onPress={()=>save('service_save',{...form,service_id:edited?.id,price:form.price.replace(',','.'),duration:Number(form.duration),buffer:Number(form.buffer)})}/>{edited&&<Button title={edited.active?'Hizmeti pasife al':'Hizmeti aç'} secondary onPress={()=>save('service_save',{service_id:edited.id,active:!edited.active})}/>}</Stack>}
 {modal==='schedule'&&<Stack><Row>{['Pazar','Pzt','Salı','Çar','Per','Cuma','Cmt'].map((d,i)=><Button key={i} title={d} small secondary={form.weekday!==String(i)} onPress={()=>update('weekday',String(i))}/>)}</Row><Input label="Açılış saati (SS:DD)" value={form.opens} onChangeText={v=>update('opens',v)}/><Input label="Kapanış saati (SS:DD)" value={form.closes} onChangeText={v=>update('closes',v)}/><Button title="Programı kaydet" onPress={()=>save('schedule_save',{staff_id:edited?.id,weekday:Number(form.weekday),opens:form.opens,closes:form.closes})}/><Button title="Bu günü tatil yap" secondary onPress={()=>save('schedule_save',{staff_id:edited?.id,weekday:Number(form.weekday),closed:true})}/><T bold>Bu ustanın hizmetleri</T>{services.map(s=><Button key={s.id} title={`${(rows.staff_services||[]).some(v=>v.staff_id===edited?.id&&v.service_id===s.id)?'✓':'○'} ${s.name}`} secondary small onPress={()=>save('staff_services',{staff_id:edited?.id,service_id:s.id,enabled:!(rows.staff_services||[]).some(v=>v.staff_id===edited?.id&&v.service_id===s.id)},false)}/>)}</Stack>}
 {modal==='commission'&&<Stack><Input label="Sabit platform bedeli (TL)" value={form.fee||'20'} onChangeText={v=>update('fee',v)} numeric/><Input label="Ek yüzdesel bedel (%)" value={form.percent||'0'} onChangeText={v=>update('percent',v)} numeric/><T bold>Komisyon uygulanan müşteri kaynakları</T><Row>{['platform','walk_in','phone','private'].map(s=><Button key={s} title={(sourcePolicy.includes(s)?'✓ ':'○ ')+statusLabel(s)} small secondary onPress={()=>setSourcePolicy(p=>p.includes(s)?p.filter(v=>v!==s):[...p,s])}/>)}</Row><Button title={(affects?'✓ ':'○ ')+'İndirim yüzdesel komisyonu etkiler'} secondary onPress={()=>setAffects(!affects)}/><T size={11} color={colors.muted}>Değişiklik yeni işlemlere uygulanır. Önceden onaylanan randevuların fiyatı korunur.</T><Button title="Anlaşmayı kaydet" onPress={()=>save('commission_rule',{fee:form.fee,percent:form.percent,sources:sourcePolicy,discount_affects:affects})}/></Stack>}
 {modal==='payment'&&<Stack><Metric label="Kalan platform borcun" value={money(balance?.balance)}/><Input label="Ödediğin tutar (TL)" value={form.amount} onChangeText={v=>update('amount',v)} numeric/><Row>{['transfer','cash'].map(m=><Button key={m} title={statusLabel(m)} small secondary={form.method!==m} onPress={()=>update('method',m)}/>)}</Row><Input label="Ödeme günü YYYY-AA-GG" value={form.paid_at} onChangeText={v=>update('paid_at',v)}/><Input label="Açıklama" value={form.note} onChangeText={v=>update('note',v)}/><T size={11} color={colors.muted}>Ödeme yöntemini ve gerçek tahsilatı admin kontrol eder. Bildirim sonrasında dekont ekleyebilirsin.</T><Button title="Ödeme bildir" onPress={()=>save('payment_submit',{amount:form.amount.replace(',','.'),method:form.method,paid_at:istanbul(form.paid_at,'12:00'),note:form.note,key})}/></Stack>}
 {modal==='payment_schedule'&&<Stack><Row>{['weekly','monthly'].map(p=><Button key={p} title={p==='weekly'?'Haftalık':'Aylık'} secondary={form.period!==p} onPress={()=>update('period',p)}/>)}</Row><Input label={form.period==='weekly'?'Gün: Pazartesi 1 … Pazar 7':'Ayın günü: 1–28'} value={form.day} onChangeText={v=>update('day',v)} numeric/><Input label="Sonraki ödeme tarihi YYYY-AA-GG" value={form.next_due} onChangeText={v=>update('next_due',v)}/><Button title="Ödeme gününü kaydet" onPress={()=>save('payment_schedule',{period:form.period,day:Number(form.day),next_due:form.next_due})}/></Stack>}
 {modal==='expense'&&<Stack><Input label="Gider tutarı (TL)" value={form.amount} onChangeText={v=>update('amount',v)} numeric/><Input label="Kategori (kira, malzeme…)" value={form.category||''} onChangeText={v=>update('category',v)}/><Input label="Açıklama" value={form.note} onChangeText={v=>update('note',v)}/><Button title="Gideri kaydet" onPress={()=>save('expense',{amount:form.amount.replace(',','.'),category:form.category,note:form.note})}/></Stack>}
 {modal==='settings'&&<Stack><Input label="Kaçıncı ziyarette avantaj? (0 kapatır)" value={form.loyalty_every} onChangeText={v=>update('loyalty_every',v)} numeric/><Input label="Sadakat indirimi (%)" value={form.loyalty_percent} onChangeText={v=>update('loyalty_percent',v)} numeric/><Input label="Otomatik geri çağırma: kaç gün sonra? (0 kapatır)" value={form.recall_after_days} onChangeText={v=>update('recall_after_days',v)} numeric/><T size={11} color={colors.muted}>Yalnızca kampanya izni olan müşteriye, son ziyaretinden sonra bir kez uygulama içi hatırlatma gönderilir.</T><Input label="Mesai dışı yanıt" value={form.auto_reply||''} onChangeText={v=>update('auto_reply',v)} multiline/><Button title="Ayarları kaydet" onPress={()=>save('settings',{loyalty_every:Number(form.loyalty_every),loyalty_percent:Number(form.loyalty_percent),recall_after_days:Number(form.recall_after_days),auto_reply:form.auto_reply||undefined})}/></Stack>}
 {modal==='announcement'&&<Stack><Input label="Duyuru başlığı" value={form.title} onChangeText={v=>update('title',v)}/><Input label="Sistem duyurusu metni" value={form.body} onChangeText={v=>update('body',v)} multiline/><Row>{[['all','Tüm Style kullanıcıları'],['staff','Ustalar'],['business','İşletme yöneticileri']].map(([v,l])=><Button key={v} title={l} small secondary={form.audience!==v} onPress={()=>update('audience',v)}/>)}</Row><T size={11} color={colors.muted}>Bu işlem hedef kitlenin uygulama içi bildirim kutusuna sistem duyurusu gönderir.</T><Button title="Duyuruyu gönder" disabled={task.busy||form.title.length<3||form.body.length<3} onPress={()=>save('announcement',{title:form.title,body:form.body,audience:form.audience,key})}/></Stack>}
 {['members','admins'].includes(modal)&&<Stack><Input label="Kayıtlı hesabın e-postası" value={form.email} onChangeText={v=>update('email',v)}/>{modal==='members'&&<Row>{[['staff','Çalışan'],['manager','İşletme yöneticisi']].map(([r,l])=><Button key={r} title={l} secondary={form.role!==r} onPress={()=>update('role',r)}/>)}</Row>}<Row>{[['true','Yetki açık'],['false','Yetki kapalı']].map(([v,l])=><Button key={v} title={l} secondary={form.active!==v} onPress={()=>update('active',v)}/>)}</Row><T color={colors.muted} size={12}>{modal==='admins'?'Platform admin yetkisi tüm işletme ve finans kayıtlarına erişim verir. Yalnızca güvendiğin yetkili hesabı ekle.':'Çalışan yalnızca bağlı olduğu ustanın özel bilgilerini görür; yönetici işletmenin bütün kayıtlarını görür.'}</T><Button title="Yetkiyi kaydet" disabled={!form.email||task.busy} onPress={()=>save(modal==='admins'?'admin_grant':'member_role',{email:form.email.trim(),role:form.role,active:form.active==='true'})}/></Stack>}
 {modal==='adjust'&&<Stack><Metric label="Kayıtlı tahakkuk" value={money(edited?.amount)}/><Metric label="Bu kaydın tahsilatı" value={money(edited?.paid)}/><Input label="Düzeltme farkı (TL, azaltmak için negatif)" value={form.amount} onChangeText={v=>update('amount',v)} numeric/><Input label="Düzeltme gerekçesi" value={form.reason} onChangeText={v=>update('reason',v)} multiline/><T size={12} color={colors.muted}>Tahsil edilmiş tutarın altına düzeltme yapılamaz. Orijinal hareket ve düzeltme denetim geçmişinde korunur.</T><Button title="Düzeltmeyi kaydet" disabled={task.busy||form.reason.length<3} onPress={()=>save('commission_adjust',{ledger_id:edited?.id,amount:form.amount.replace(',','.'),reason:form.reason})}/></Stack>}
 <TaskStatus task={task}/></Sheet></Stack></Fade>;
}
