import React,{useEffect,useRef,useState} from 'react';
import {View} from 'react-native';
import * as Crypto from 'expo-crypto';
import {api,supabase,useData,dateLabel,Row as DataRow} from './data';
import {Badge,Button,Card,Empty,Fade,Head,Input,Row,Stack,T,TaskStatus,useTask,useTheme} from './ui';
export function Messages({initial=''}:{initial?:string}){
 const {rows,act,session,directory}=useData(),{colors}=useTheme(),task=useTask();const [chosen,setChosen]=useState(initial),[body,setBody]=useState(''),[history,setHistory]=useState<DataRow[]>([]),[hasMore,setHasMore]=useState(false);const typed=useRef(0);
 const conversations=rows.conversations||[],conv=conversations.find(c=>c.id===chosen)||conversations[0];const messages=[...(rows.messages||[]),...history.filter(h=>!(rows.messages||[]).some(r=>r.id===h.id))].filter(m=>m.conversation_id===conv?.id).sort((a,b)=>new Date(a.created_at).getTime()-new Date(b.created_at).getTime());
 useEffect(()=>{if(conv)void api('chat_read',{conversation_id:conv.id}).catch(()=>{});},[conv?.id,messages.length]);
 useEffect(()=>{let alive=true;setHistory([]);setHasMore(false);if(conv)void supabase.from('db_style_messages').select('*').eq('conversation_id',conv.id).order('created_at',{ascending:false}).order('id',{ascending:false}).limit(100).then(r=>{if(!alive)return;if(r.error)void task.run(async()=>{throw r.error;});else{setHistory(r.data||[]);setHasMore(r.data?.length===100);}});return()=>{alive=false;};},[conv?.id]);
 const older=()=>task.run(async()=>{if(!conv)return;const oldest=history.reduce((t,m)=>m.created_at<t?m.created_at:t,history[0]?.created_at||new Date().toISOString());const r=await supabase.from('db_style_messages').select('*').eq('conversation_id',conv.id).lt('created_at',oldest).order('created_at',{ascending:false}).limit(100);if(r.error)throw r.error;setHistory(h=>[...h,...(r.data||[])]);setHasMore(r.data?.length===100);});
 const send=(text=body)=>task.run(async()=>{if(!conv||!text.trim())return;await act('message',{conversation_id:conv.id,body:text.trim(),key:Crypto.randomUUID()});setBody('');});
 if(!conv)return <Empty title="Sohbet randevunla başlar" body="Randevu oluşturduktan sonra ilgili işletme ve ustayla mesajlaşabilirsin."/>;
 const ap=rows.appointments?.find(a=>a.id===conv.appointment_id),business=directory.find(b=>b.id===conv.business_id)||rows.businesses?.find(b=>b.id===conv.business_id);
 const typing=rows.conversation_presence?.some(p=>p.conversation_id===conv.id&&p.user_id!==session?.user.id&&new Date(p.typing_until)>new Date());
 return <Fade><Stack><Head eyebrow="Randevu bağlantılı sohbet" title="Bir mesaj, daha kolay bir gün" subtitle="Müşteri ve usta arasında güvenli iletişim"/><Row>{conversations.map(c=><Button key={c.id} title={rows.appointments?.find(a=>a.id===c.appointment_id)?.customer_name||'Randevu sohbeti'} small secondary={conv.id!==c.id} onPress={()=>{setChosen(c.id);setHistory([]);}}/>)}</Row><Card><Row style={{justifyContent:'space-between'}}><View><T bold size={19}>{business?.name||'Randevu sohbeti'}</T><T color={colors.muted} size={12}>{ap?.customer_name} · {dateLabel(ap?.starts_at)}</T></View><Badge title={conv.blocked?'Engellendi':'Sohbet açık'}/></Row>
 {hasMore&&<Button title="Daha eski mesajları yükle" small secondary disabled={task.busy} onPress={()=>void older()}/>}
 {messages.length===0&&<T color={colors.muted}>İlk mesajını gönder. İletişim yalnızca bu randevunun yetkili kişilerine açıktır.</T>}
 {messages.map(m=><View key={m.id} style={{maxWidth:'90%',alignSelf:m.sender_id===session?.user.id?'flex-end':'flex-start',backgroundColor:m.sender_id===session?.user.id?colors.raised:colors.bg,borderColor:colors.border,borderWidth:1,borderRadius:17,padding:14,gap:6}}><T>{m.body}</T><T color={colors.muted} size={9}>{dateLabel(m.created_at)}{m.sender_id===session?.user.id?(m.read_at?' · Okundu':' · Gönderildi'):''}</T></View>)}
 {typing&&<T size={11} color={colors.mint}>Karşı taraf yazıyor…</T>}
 <Input label="Mesajın" value={body} onChangeText={s=>{setBody(s);if(Date.now()-typed.current>2500){typed.current=Date.now();void api('typing',{conversation_id:conv.id}).catch(()=>{});}}} multiline/>
 <Row><Button title="Mesaj gönder" disabled={task.busy||conv.blocked||!body.trim()} onPress={()=>void send()}/><Button title={conv.blocked?'Engeli kaldır':'Sohbeti engelle'} small secondary onPress={()=>task.run(()=>act('chat_block',{conversation_id:conv.id,blocked:!conv.blocked}))}/><Button title="Şikâyet et" small secondary onPress={()=>task.run(()=>act('support',{kind:'message_report',body:'Sohbet şikâyeti: '+conv.id}),'Şikâyetin inceleme için gönderildi.')}/></Row>
 <Row>{['Merhaba, 10 dakika gecikeceğim.','Randevunuz için sizi bekliyoruz.','Teşekkür ederim.'].map(text=><Button key={text} title={text} small secondary disabled={conv.blocked} onPress={()=>void send(text)}/>)}</Row><TaskStatus task={task}/></Card></Stack></Fade>;
}
