import React,{useState} from 'react';
import {View,Platform,Linking} from 'react-native';
import QRCode from 'react-native-qrcode-svg';
import {api,supabase,useData,dateLabel,statusLabel} from './data';
import {Avatar,Badge,Button,Card,Head,Input,Row,Sheet,Stack,T,TaskStatus,useTask,useTheme} from './ui';
import {SITE,VERSION} from './config';
import {testNotification,enableReminders} from './notifications';
export function Profile(){
 const {rows,session,act,isAdmin,isManager}=useData(),{colors,light,toggle}=useTheme(),task=useTask();const p=rows.profiles?.find(p=>p.id===session?.user.id);
 const [name,setName]=useState(p?.display_name||session?.user.email?.split('@')[0]||''),[phone,setPhone]=useState(p?.phone||''),[password,setPassword]=useState(''),[support,setSupport]=useState(''),[modal,setModal]=useState(''),[qr,setQr]=useState<{token:string;expires_at:string}|null>(null),[marketing,setMarketing]=useState(!!p?.marketing_consent);
 return <Stack><Head eyebrow="Senin alanın" title="Profil ve tercihler" subtitle="Hesabın, izinlerin ve sana ait veriler"/><Card><Row><Avatar name={p?.display_name||'DS'} url={p?.avatar_url} size={65}/><View style={{flex:1}}><T bold size={22}>{p?.display_name||'DraBornStyle kullanıcısı'}</T><T color={colors.muted}>{session?.user.email}</T><Row>{isAdmin&&<Badge title="Platform yöneticisi"/>}{isManager&&<Badge title="İşletme yöneticisi"/>}<Badge title="Müşteri"/></Row></View></Row><Input label="Adın" value={name} onChangeText={setName}/><Input label="Telefon (isteğe bağlı)" value={phone} onChangeText={setPhone}/><Button title={(marketing?'✓ ':'○ ')+'Kampanya ve geri çağırma izni'} secondary onPress={()=>setMarketing(!marketing)}/><Button title="Profilimi kaydet" onPress={()=>task.run(()=>act('profile',{name,phone,marketing}))}/></Card>
 <Card><Head title="QR ile hızlı tanın" subtitle="5 dakika geçerli, kişisel hesabına erişim vermez"/><T color={colors.muted} size={12}>İşletmedeki yetkili usta kodunu tarayarak adını müşteri listesine ekleyebilir ve hizmetini hızlıca başlatabilir.</T><Button title="Müşteri QR kodumu oluştur" onPress={()=>task.run(async()=>{const q=await api('qr_create');setQr(q);setModal('qr');})}/></Card>
 <Card><Head title="Görünüm ve bildirimler"/><Row><Button title={light?'Koyu temaya geç':'Açık temaya geç'} secondary onPress={toggle}/><Button title="Yerel hatırlatmaları aç" secondary onPress={()=>task.run(enableReminders,'Bu cihazda yerel randevu hatırlatmaları açıldı.')}/><Button title="Bildirim testi" secondary onPress={()=>task.run(testNotification,'Test bildirimi gönderildi.')}/></Row><T size={11} color={colors.muted}>Uygulama içi bildirimler canlıdır. Expo Go’da yerel hatırlatmalar test edilir. Android uzak push ve arka planda konum için geliştirme derlemesi gerekir; bu sürümde kullanılmaz.</T><Row><Button title="Randevu bildirimlerini aç" small secondary onPress={()=>task.run(()=>act('notification_preferences',{appointments:true,messages:true,marketing}))}/><Button title="Randevu ve mesaj bildirimlerini sessize al" small secondary onPress={()=>task.run(()=>act('notification_preferences',{appointments:false,messages:false,marketing}))}/></Row></Card>
 <Card><Head title="Güvenli hesabın"/><Input label="Yeni şifre (en az 8 karakter)" value={password} onChangeText={setPassword} secure/><Button title="Şifremi değiştir" secondary onPress={()=>task.run(async()=>{if(password.length<8)throw new Error('Şifre en az 8 karakter olmalı.');const r=await supabase.auth.updateUser({password});if(r.error)throw r.error;setPassword('');})}/><Row><Button title="Bu cihazdan çıkış" secondary onPress={()=>task.run(async()=>{const r=await supabase.auth.signOut({scope:'local'});if(r.error)throw r.error;})}/><Button title="Tüm cihazlardan çıkış" secondary onPress={()=>setModal('logout')}/></Row></Card>
 <Card><Head title="Destek ve kişisel veriler"/><Input label="Destek mesajın" value={support} onChangeText={setSupport} multiline/><Button title="Destek talebi oluştur" secondary onPress={()=>task.run(async()=>{if(support.trim().length<4)throw new Error('Talebini biraz daha ayrıntılı yaz.');await act('support',{body:support});setSupport('');},'Destek talebin kaydedildi.')}/><Row><Button title="Gizlilik ve kullanım koşulları" small secondary onPress={()=>void Linking.openURL(SITE+'legal.html')}/><Button title="Veri silme talebi" small secondary onPress={()=>setModal('delete')}/></Row></Card>
 {(rows.support_requests||[]).filter(r=>r.user_id===session?.user.id).map(r=><Card key={r.id}><Row><Badge title={r.kind}/><Badge title={statusLabel(r.status)}/></Row><T>{r.body}</T><T color={colors.muted} size={11}>{dateLabel(r.created_at)}</T></Card>)}
 <T color={colors.muted} size={11} style={{textAlign:'center'}}>DraBornStyle {VERSION} · Modern Barber Studio</T><TaskStatus task={task}/>
 <Sheet open={!!modal} title={modal==='qr'?'Müşteri QR kodun':modal==='delete'?'Kişisel veri talebi':'Tüm cihazlardan çıkış'} onClose={()=>setModal('')}>
 {modal==='qr'&&qr&&<Stack><View style={{alignItems:'center',backgroundColor:'#fff',padding:25,borderRadius:20}}><QRCode value={'dbstyle:'+qr.token} size={215} backgroundColor="#fff" color="#0b192a"/></View><T color={colors.muted} size={12}>Geçerlilik sonu: {dateLabel(qr.expires_at)}</T><T size={11} color={colors.muted}>Kodu yalnızca hizmet almak istediğin ustaya göster.</T></Stack>}
 {modal==='delete'&&<Stack><T>DraBornStyle kişisel verilerinin silinmesini talep edebilirsin. Yönetici yasal saklama gereksinimlerini ve finansal kayıtları kontrol ederek talebini sonuçlandırır.</T><T color={colors.muted}>Aktif varış izinlerin hemen kapatılır. Ortak kimlik hesabının diğer DraBorn uygulamalarındaki verileri bu taleple silinmez.</T><Button title="Silme talebimi gönder" onPress={()=>task.run(async()=>{await act('data_delete');setModal('');},'Veri silme talebin kaydedildi.')}/></Stack>}
 {modal==='logout'&&<Stack><T>Bu hesabın açık oturumları kapatılacak. Tekrar giriş yaparak devam edebilirsin.</T><Button title="Çıkışı onayla" onPress={()=>task.run(async()=>{const r=await supabase.auth.signOut({scope:'global'});if(r.error)throw r.error;setModal('');})}/></Stack>}
 <TaskStatus task={task}/></Sheet></Stack>;
}
