import React,{useEffect,useState} from 'react';
import {View} from 'react-native';
import {QRScanner} from './QRScanner';
import {supabase,useData,money,dateLabel,clock,statusLabel,Row as DataRow,istanbul,today} from './data';
import {Avatar,Badge,Bars,Button,Card,Empty,Fade,Head,Input,Metric,Row,Sheet,Stack,T,TaskStatus,useTask,useTheme} from './ui';
export function Staff(){
 const {rows,session,act,isManager}=useData(),{colors}=useTheme(),task=useTask();
 const staff=(rows.staff||[]).filter(s=>s.active&&(isManager||s.user_id===session?.user.id));
 const [selected,setSelected]=useState(''),[modal,setModal]=useState(''),[source,setSource]=useState('walk_in'),[name,setName]=useState(''),[service,setService]=useState(''),[customer,setCustomer]=useState(''),[price,setPrice]=useState(''),[reason,setReason]=useState(''),[collected,setCollected]=useState(''),[method,setMethod]=useState('cash'),[minutes,setMinutes]=useState('15'),[code,setCode]=useState(''),[pct,setPct]=useState('15'),[maxUses,setMaxUses]=useState(''),[expires,setExpires]=useState(''),[note,setNote]=useState(''),[day,setDay]=useState(today()),[from,setFrom]=useState('12:00'),[to,setTo]=useState('13:00'),[now,setNow]=useState(Date.now()),[stats,setStats]=useState<DataRow>({});
 const me=staff.find(s=>s.id===selected)||staff[0];useEffect(()=>{if(me)void supabase.rpc('staff_dashboard',{staff:me.id}).then(r=>{if(!r.error)setStats(r.data||{});});},[me?.id,rows.service_sessions]);useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(t)},[]);
 if(!me)return <Empty title="Usta panelin hazır" body="İşletme sahibi seni e-posta hesabınla çalışan listesine eklediğinde, randevuların ve çalışma ekranın burada açılacak."/>;
 const av=rows.staff_availability?.find(a=>a.staff_id===me.id),sessions=(rows.service_sessions||[]).filter(s=>s.staff_id===me.id),live=sessions.find(s=>!s.completed_at),finished=sessions.filter(s=>s.completed_at),tod=finished.filter(s=>new Date(s.completed_at).toLocaleDateString('en-CA',{timeZone:'Europe/Istanbul'})===today());
 const week=finished.filter(s=>new Date(s.completed_at).getTime()>now-7*86400000),month=finished.filter(s=>new Date(s.completed_at).getTime()>now-30*86400000),sum=(a:DataRow[])=>a.reduce((n,s)=>n+Number(s.service_price),0),avg=finished.length?Math.round(finished.reduce((n,s)=>n+(new Date(s.completed_at).getTime()-new Date(s.started_at).getTime())/60000,0)/finished.length):0;
 const appointments=(rows.appointments||[]).filter(a=>a.staff_id===me.id&&['confirmed','late'].includes(a.status)).sort((a,b)=>new Date(a.starts_at).getTime()-new Date(b.starts_at).getTime());
 const services=(rows.services||[]).filter(s=>s.business_id===me.business_id&&s.active&&(rows.staff_services||[]).some(v=>v.staff_id===me.id&&v.service_id===s.id));
 const customers=(rows.customers||[]).filter(c=>c.business_id===me.business_id&&(isManager||c.staff_id===me.id||sessions.some(se=>se.customer_id===c.id)));
 const save=(action:string,data:DataRow={},close=true)=>task.run(async()=>{const r=await act(action,{staff_id:me.id,...data});if(close)setModal('');return r;});
 const start=()=>save('start',{service_id:service,customer_name:name,source,customer_id:customer||undefined});
 const finishOpen=()=>{if(!live)return;setPrice(String(live.service_price));setCollected(String(Number(live.service_price)+Number(live.platform_fee)));setReason('');setModal('finish');};
 const next=appointments[0];
 const schedule=(rows.staff_schedules||[]).filter(s=>s.staff_id===me.id);
 return <Fade><Stack><Head eyebrow="Usta çalışma alanı" title={`İyi çalışmalar, ${me.name}`} subtitle="Bir bakışta günün. Birkaç dokunuşla işin."/>
 <Row>{staff.map(s=><Button key={s.id} title={s.name} secondary={s.id!==me.id} small onPress={()=>setSelected(s.id)}/>)}</Row>
 <Card style={{borderColor:colors.mint+'55',padding:24}}><Row style={{justifyContent:'space-between'}}><Row><Avatar name={me.name} url={me.photo_url} size={60}/><View style={{gap:6}}><T size={22} bold>{me.name}</T><Badge title={statusLabel(av?.state||'available')} tone={av?.state==='working'?colors.coral:colors.mint}/></View></Row>{av?.busy_until&&<View><T size={11} color={colors.muted}>Tahmini kalan süre</T><T size={24} color={colors.coral} bold>{Math.max(0,Math.ceil((new Date(av.busy_until).getTime()-now)/60000))} dk</T></View>}</Row>
 {live?<><T bold>{rows.appointments?.find(a=>a.id===live.appointment_id)?.customer_name} · {rows.services?.find(v=>v.id===live.service_id)?.name}</T><T color={colors.muted} size={12}>Başlangıç {clock(live.started_at)} · Tahmini bitiş {clock(live.estimated_end)}</T><Row><Button title="Tıraşı bitir →" onPress={finishOpen}/><Button title="Süreyi uzat" secondary onPress={()=>setModal('extend')}/></Row></>:<><Row><Button title="＋ Hızlı müşteri başlat" onPress={()=>{setService(services[0]?.id||'');setCustomer('');setName('');setModal('quick');}}/><Button title="QR ile müşteri tanı" secondary onPress={()=>setModal('qr')}/><Button title="Müsaitim" secondary onPress={()=>save('status',{state:'available'},false)}/><Button title="Mola / Meşgul" secondary onPress={()=>setModal('status')}/><Button title="Mesaim bitti" secondary onPress={()=>save('status',{state:'off'},false)}/></Row><T size={11} color={colors.muted}>Onaylı randevuların sistem tarafından korunur. Meşguliyet, izin veya ek hizmet mevcut randevuyla çakışamaz.</T></>}
 </Card><TaskStatus task={task}/>
 <Row style={{alignItems:'stretch'}}><Metric label="Bugünkü müşterilerin" value={String(stats.today_count||0)}/><Metric label="Bugünkü hizmet hasılatı" value={money(stats.today_revenue)} tone={colors.mint}/><Metric label="Son 7 gün" value={money(stats.week_revenue)}/><Metric label="Son 30 gün" value={money(stats.month_revenue)}/></Row>
 {next&&<Card><Head title="Sıradaki müşterin" subtitle={dateLabel(next.starts_at)}/><Row style={{justifyContent:'space-between'}}><View><T bold size={20}>{next.customer_name}</T><T color={colors.muted}>{rows.services?.find(s=>s.id===next.service_id)?.name} · {money(Number(next.service_price)+Number(next.platform_fee))}</T></View><Button title="Tıraşa başla" disabled={!!live} onPress={()=>save('start',{appointment_id:next.id})}/></Row></Card>}
 <Head title="Günün randevuları" subtitle="Yaklaşan müşteriler ve çalışma takvimin"/>
 {appointments.length?appointments.slice(0,20).map(a=><Card key={a.id} style={{padding:16}}><Row style={{justifyContent:'space-between'}}><View style={{flex:1}}><T bold>{clock(a.starts_at)} · {a.customer_name}</T><T color={colors.muted} size={11}>{dateLabel(a.starts_at)} · {statusLabel(a.source)}</T></View><Badge title={statusLabel(a.status)}/><Button title="Başlat" small disabled={!!live} onPress={()=>save('start',{appointment_id:a.id})}/><Button title="Gecikti" small secondary onPress={()=>save('appointment_change',{appointment_id:a.id,status:'late'},false)}/><Button title="Gelmedi" small secondary onPress={()=>save('appointment_change',{appointment_id:a.id,status:'no_show'},false)}/></Row></Card>):<Empty title="Takvimin sakin" body="Yeni randevular burada görünecek. Çat kapı gelen müşteriyi hızlı müşteri başlat ile kaydedebilirsin."/>}
 <Row style={{alignItems:'stretch'}}><Card style={{flex:1,minWidth:240}}><T bold size={18}>Performansın</T><T color={colors.muted}>Ortalama hizmet süren: {stats.average_minutes||0} dakika</T><T color={colors.muted}>Son 28 günlük ortalamayla gelecek hafta: {money(sum(finished.filter(s=>new Date(s.completed_at).getTime()>now-28*86400000))/4)}</T><T size={11} color={colors.muted}>Geçmiş hizmet hasılatından basit tahmin; kesin kazanç değildir.</T><T>Haftalık hedef: {money(me.weekly_goal)}</T><Bars items={[{name:'Bu hafta',value:sum(week)},{name:'Hedef',value:Number(me.weekly_goal)}]} label={r=>r.name} value={r=>r.value}/></Card><Card style={{flex:1,minWidth:240}}><T bold size={18}>Sana özel kodlar</T>{(rows.referral_codes||[]).filter(c=>c.staff_id===me.id).map(c=><Row key={c.id}><Badge title={c.code}/><T>%{c.percent} · {c.uses} kullanım</T></Row>)}<Button title="İndirim kodu oluştur" secondary onPress={()=>setModal('code')}/><Button title="İzinli müşterileri geri çağır" secondary onPress={()=>save('recall',{days:30},false)}/></Card></Row>
 <Head title="Akıllı müşteri defterin" subtitle="Önceki hizmetler, ziyaretler ve sana ait notlar"/>
 {customers.slice(0,30).map(c=>{const history=finished.filter(s=>s.customer_id===c.id),last=history.sort((a,b)=>new Date(b.completed_at).getTime()-new Date(a.completed_at).getTime())[0];return <Card key={c.id} style={{padding:16}}><Row style={{justifyContent:'space-between'}}><Row><Avatar name={c.name} size={39}/><View><T bold>{c.name}</T><T size={11} color={colors.muted}>{history.length} kayıtlı ziyaret · {last?`Son hizmet: ${dateLabel(last.completed_at)}`:'İlk ziyaret'}</T></View></Row><Button title="Tekrar başlat" small secondary onPress={()=>{setCustomer(c.id);setName(c.name);setService(last?.service_id||services[0]?.id||'');setModal('quick');}}/><Button title="Not ekle" small secondary onPress={()=>{setCustomer(c.id);setNote('');setModal('note');}}/></Row>{(rows.customer_notes||[]).filter(n=>n.customer_id===c.id&&n.staff_id===me.id).slice(0,3).map(n=><T key={n.id} size={12} color={colors.muted}>{n.note}</T>)}</Card>})}
 <Card><T bold>Çalışma programın</T><Row>{schedule.sort((a,b)=>a.weekday-b.weekday).map(s=><Badge key={s.id} title={`${['Paz','Pzt','Sal','Çar','Per','Cum','Cmt'][s.weekday]} ${s.opens.slice(0,5)}–${s.closes.slice(0,5)}`}/>)}</Row><Button title="İzin / özel gün ekle" secondary small onPress={()=>setModal('block')}/></Card>
 <Head title="Dijital sıra" subtitle="Çat kapı müşteriler ve tahmini bekleme"/>
 {(rows.queue||[]).filter(q=>q.staff_id===me.id&&q.state==='waiting').sort((a,b)=>new Date(a.created_at).getTime()-new Date(b.created_at).getTime()).map((q,i)=><Card key={q.id} style={{padding:14}}><Row><T bold>{i+1}. {q.customer_name}</T><T color={colors.muted} size={11}>Yaklaşık {(i+1)*(services.find(v=>v.id===q.service_id)?.duration_minutes||30)} dk</T><Button title="Müşteriyi al" small secondary onPress={()=>task.run(async()=>{await act('start',{staff_id:me.id,service_id:q.service_id,customer_name:q.customer_name,source:'walk_in'});await act('queue_change',{id:q.id,state:'started'});})}/><Button title="Çıkar" small secondary onPress={()=>save('queue_change',{id:q.id,state:'cancelled'},false)}/></Row></Card>)}
 <Sheet open={!!modal} title={({quick:'Hızlı müşteri başlat',finish:'Hizmeti tamamla',extend:'Hizmet süresini uzat',status:'Çalışma durumun',code:'Ustana özel indirim kodu',note:'Müşteri notu',block:'İzin ve mola',qr:'Müşteri QR kodunu oku'} as any)[modal]||'İşlem'} onClose={()=>setModal('')}>
 {modal==='qr'&&<QRScanner onScan={token=>{if(task.busy)return;void task.run(async()=>{const r=await act('qr_lookup',{staff_id:me.id,token});setCustomer(r.customer_id);setName(r.name);setService(services[0]?.id||'');setSource('private');setModal('quick');});}}/>}
 {modal==='quick'&&<Stack><T size={12} color={colors.muted}>Kayıtlı müşteri seçimi veya misafir adı yeterli. Başlangıç saati otomatik kaydedilir.</T><Row>{['walk_in','phone','private'].map(s=><Button key={s} title={statusLabel(s)} secondary={source!==s} small onPress={()=>setSource(s)}/>)}</Row><Input label="Müşteri adı (boşsa Misafir)" value={name} onChangeText={setName}/><Row>{services.map(s=><Button key={s.id} title={`${s.name} · ${money(s.price)}`} secondary={service!==s.id} small onPress={()=>setService(s.id)}/>)}</Row><Button title="Tıraşa başladım" disabled={!service||task.busy} onPress={start}/></Stack>}
 {modal==='finish'&&live&&<Stack><Card><Row style={{justifyContent:'space-between'}}><T>Onaylı hizmet fiyatı</T><T bold>{money(live.service_price)}</T></Row><Row style={{justifyContent:'space-between'}}><T>Platform bedeli</T><T>{money(live.platform_fee)}</T></Row></Card><Input label="Son hizmet fiyatı (TL)" value={price} onChangeText={v=>{setPrice(v);setCollected(String(Number(v)+Number(live.platform_fee)));}} numeric/><Input label="İndirim nedeni (indirim varsa gerekli)" value={reason} onChangeText={setReason}/><Row>{['cash','card','transfer'].map(s=><Button key={s} title={statusLabel(s)} secondary={method!==s} small onPress={()=>setMethod(s)}/>)}</Row><Input label="İşletmenin tahsil ettiği toplam (TL)" value={collected} onChangeText={setCollected} numeric/><T size={12} color={colors.muted}>Sunucu indirim yetkini ve fiyatı doğrular. Komisyon bir kez oluşur; tamamlanan kayıt iz bırakmadan değiştirilemez.</T><Button title="Fiyatı onayla ve tıraşı bitir" disabled={task.busy} onPress={()=>save('finish',{session_id:live.id,price:price.replace(',','.'),collected:collected.replace(',','.'),reason,method})}/></Stack>}
 {['extend','status'].includes(modal)&&<Stack><Input label="Kaç dakika? (1–120)" value={minutes} onChangeText={setMinutes} numeric/><Row>{['15','30','60'].map(n=><Button key={n} title={n+' dk'} small secondary={minutes!==n} onPress={()=>setMinutes(n)}/>)}</Row>{modal==='extend'?<Button title="Süreyi uzat" onPress={()=>save('extend',{session_id:live?.id,minutes:Number(minutes)})}/>:<Row><Button title="Mola verdim" onPress={()=>save('status',{state:'break',minutes:Number(minutes)})}/><Button title="Meşgulüm" onPress={()=>save('status',{state:'busy',minutes:Number(minutes)})}/></Row>}</Stack>}
 {modal==='code'&&<Stack><Input label="Kod" value={code} onChangeText={setCode} placeholder="AHMET15"/><Input label="İndirim yüzdesi" value={pct} onChangeText={setPct} numeric/><Input label="Kullanım sınırı (boşsa süresiz kullanım)" value={maxUses} onChangeText={setMaxUses} numeric/><Input label="Bitiş günü (YYYY-AA-GG, boşsa süresiz)" value={expires} onChangeText={setExpires}/><Button title="Kodu oluştur" onPress={()=>save('referral_create',{code,percent:Number(pct),max_uses:maxUses||undefined,expires_at:expires?istanbul(expires,'23:59'):undefined})}/></Stack>}
 {modal==='note'&&<Stack><T size={12} color={colors.muted}>Yalnızca hizmet tercihiyle ilgili ve müşterinin paylaşımına izin verdiği notları kaydet.</T><Input label="Not" value={note} onChangeText={setNote} multiline/><Button title="Notu kaydet" onPress={()=>save('customer_note',{customer_id:customer,note})}/></Stack>}
 {modal==='block'&&<Stack><Input label="Gün (YYYY-AA-GG)" value={day} onChangeText={setDay}/><Input label="Başlangıç (SS:DD)" value={from} onChangeText={setFrom}/><Input label="Bitiş (SS:DD)" value={to} onChangeText={setTo}/><Input label="İzin / tatil nedeni" value={reason} onChangeText={setReason}/><Button title="Müsaitliği kapat" onPress={()=>save('block',{starts_at:istanbul(day,from),ends_at:istanbul(day,to),reason})}/></Stack>}
 <TaskStatus task={task}/></Sheet></Stack></Fade>;
}
