import React,{createContext,useContext,useEffect,useRef,useState} from 'react';
import {View,Text,TextInput,Pressable,StyleSheet,Modal,ScrollView,ActivityIndicator,useWindowDimensions,Animated,Platform,Image} from 'react-native';
import {LinearGradient} from 'expo-linear-gradient';
import * as Haptics from 'expo-haptics';
import AsyncStorage from '@react-native-async-storage/async-storage';
export const dark={bg:'#080c14',card:'#111925',raised:'#192435',border:'#253348',text:'#f5f8fc',muted:'#9eacc1',blue:'#6ca9ff',mint:'#54e6cf',coral:'#ff8b70',purple:'#bba3ff',danger:'#ff7893'};
export const light={bg:'#f1f4f9',card:'#ffffff',raised:'#e7edf6',border:'#d1dbe9',text:'#16233a',muted:'#5a6b85',blue:'#235fbd',mint:'#127f73',coral:'#b84629',purple:'#6950b5',danger:'#c23150'};
type Colors=typeof dark;const Theme=createContext({colors:dark,light:false,toggle:()=>{}});
export const useTheme=()=>useContext(Theme);
export function ThemeProvider({children}:{children:React.ReactNode}){const [on,setOn]=useState(false);useEffect(()=>{AsyncStorage.getItem('dbstyle-theme').then(v=>setOn(v==='light'));},[]);return <Theme.Provider value={{colors:on?light:dark,light:on,toggle:()=>{setOn(!on);void AsyncStorage.setItem('dbstyle-theme',!on?'light':'dark');}}}>{children}</Theme.Provider>;}
export function T({children,size=14,color,bold=false,style,...props}:{children?:React.ReactNode;size?:number;color?:string;bold?:boolean;style?:any;[k:string]:any}){const {colors}=useTheme();return <Text {...props} style={[{color:color||colors.text,fontSize:size,fontWeight:bold?'700':'400',lineHeight:Math.round(size*1.42)},style]}>{children}</Text>;}
export function Card({children,style}:{children:React.ReactNode;style?:any}){const {colors}=useTheme();return <View style={[{backgroundColor:colors.card,borderColor:colors.border,borderWidth:1,borderRadius:22,padding:20,gap:13},style]}>{children}</View>;}
export function Row({children,style}:{children:React.ReactNode;style?:any}){return <View style={[{flexDirection:'row',alignItems:'center',gap:10,flexWrap:'wrap'},style]}>{children}</View>;}
export function Stack({children,style}:{children:React.ReactNode;style?:any}){return <View style={[{gap:18},style]}>{children}</View>;}
export function Button({title,onPress,secondary=false,small=false,disabled=false,tone,style}:{title:string;onPress:()=>void;secondary?:boolean;small?:boolean;disabled?:boolean;tone?:string;style?:any}){const {colors}=useTheme();return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled} onPress={()=>{if(Platform.OS!=='web')void Haptics.selectionAsync();onPress();}} style={({pressed})=>[{minHeight:small?38:50,paddingHorizontal:small?14:20,paddingVertical:small?9:13,borderRadius:small?12:15,backgroundColor:secondary?colors.raised:(tone||colors.mint),borderWidth:secondary?1:0,borderColor:colors.border,opacity:disabled?.4:pressed?.75:1,alignItems:'center',justifyContent:'center'},style]}><T size={small?12:14} bold color={secondary?colors.text:'#08151e'}>{title}</T></Pressable>;}
export function Input({label,value,onChangeText,placeholder,secure=false,numeric=false,multiline=false,style}:{label:string;value:string;onChangeText:(s:string)=>void;placeholder?:string;secure?:boolean;numeric?:boolean;multiline?:boolean;style?:any}){const {colors}=useTheme();return <View style={[{gap:7},style]}><T size={12} bold color={colors.muted}>{label}</T><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.muted} secureTextEntry={secure} keyboardType={numeric?'decimal-pad':'default'} autoCapitalize="none" multiline={multiline} style={{backgroundColor:colors.raised,color:colors.text,borderWidth:1,borderColor:colors.border,borderRadius:13,paddingHorizontal:15,paddingVertical:13,minHeight:48,fontSize:15,textAlignVertical:multiline?'top':'center'}} /></View>;}
export function Badge({title,tone}:{title:string;tone?:string}){const {colors}=useTheme();return <View style={{backgroundColor:colors.raised,borderRadius:8,paddingVertical:5,paddingHorizontal:9,alignSelf:'flex-start',borderWidth:1,borderColor:(tone||colors.mint)+'45'}}><T size={10} bold color={tone||colors.mint}>{title}</T></View>;}
export function Head({eyebrow,title,subtitle,action}:{eyebrow?:string;title:string;subtitle?:string;action?:React.ReactNode}){const {colors}=useTheme();return <Row style={{justifyContent:'space-between',marginBottom:5}}><View style={{gap:5,flex:1}}>{eyebrow&&<T size={10} color={colors.mint} bold style={{letterSpacing:2}}>{eyebrow.toUpperCase()}</T>}<T size={28} bold>{title}</T>{subtitle&&<T color={colors.muted} size={13}>{subtitle}</T>}</View>{action}</Row>;}
export function Metric({label,value,detail,tone}:{label:string;value:string;detail?:string;tone?:string}){const {colors}=useTheme();return <Card style={{flex:1,minWidth:145,padding:17}}><T size={11} color={colors.muted}>{label}</T><T size={26} color={tone||colors.text} bold>{value}</T>{detail&&<T size={10} color={colors.muted}>{detail}</T>}</Card>;}
export function Empty({title,body,action}:{title:string;body:string;action?:React.ReactNode}){const {colors}=useTheme();return <Card style={{paddingVertical:34,alignItems:'center'}}><View style={{height:52,width:52,borderRadius:18,backgroundColor:colors.raised,alignItems:'center',justifyContent:'center'}}><T size={27} color={colors.blue}>◇</T></View><T size={18} bold style={{textAlign:'center'}}>{title}</T><T color={colors.muted} style={{textAlign:'center',maxWidth:460}}>{body}</T>{action}</Card>;}
export function Logo({small=false}:{small?:boolean}){return <Row style={{gap:10,flexWrap:'nowrap'}}><LinearGradient colors={['#72aaff','#51dfc4']} start={{x:0,y:0}} end={{x:1,y:1}} style={{width:small?35:47,height:small?35:47,borderRadius:14,alignItems:'center',justifyContent:'center',transform:[{rotate:'-6deg'}]}}><Text style={{fontWeight:'900',fontSize:small?16:21,color:'#101a28',letterSpacing:-2}}>DS</Text></LinearGradient><View><T size={small?16:21} bold>DraBorn<T size={small?16:21} color="#64bcfa" bold>Style</T></T><T size={8} color="#9eacc1" style={{letterSpacing:2}}>YOUR DAY. YOUR STYLE.</T></View></Row>;}
export function Avatar({name,url,size=46}:{name:string;url?:string;size?:number}){const {colors}=useTheme();return url?<Image source={{uri:url}} style={{width:size,height:size,borderRadius:size*.33}}/>:<View style={{width:size,height:size,borderRadius:size*.33,backgroundColor:colors.raised,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'}}><T size={size*.33} bold color={colors.blue}>{name?.slice(0,2).toUpperCase()||'DS'}</T></View>;}
export function Sheet({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:React.ReactNode}){const {colors}=useTheme();const {width}=useWindowDimensions();return <Modal visible={open} animationType="fade" transparent onRequestClose={onClose}><View style={{flex:1,backgroundColor:'#000a',justifyContent:'center',padding:width<600?10:30}}><View style={{maxWidth:700,width:'100%',alignSelf:'center',maxHeight:'94%',backgroundColor:colors.bg,borderRadius:24,borderWidth:1,borderColor:colors.border}}><Row style={{padding:20,justifyContent:'space-between',borderBottomWidth:1,borderColor:colors.border}}><T bold size={19} style={{flex:1}}>{title}</T><Button title="Kapat" secondary small onPress={onClose}/></Row><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:20,gap:18}}>{children}</ScrollView></View></View></Modal>;}
export function Fade({children}:{children:React.ReactNode}){const v=useRef(new Animated.Value(0)).current;useEffect(()=>{Animated.timing(v,{toValue:1,duration:400,useNativeDriver:Platform.OS!=='web'}).start();},[]);return <Animated.View style={{opacity:v,transform:[{translateY:v.interpolate({inputRange:[0,1],outputRange:[12,0]})}]}}>{children}</Animated.View>;}
export function ErrorText({text}:{text?:string}){const {colors}=useTheme();return text?<Card style={{padding:13,borderColor:colors.danger+'77'}}><T color={colors.danger} size={12}>{text}</T></Card>:null;}
export function Busy(){return <ActivityIndicator color="#54e6cf" style={{padding:24}}/>;}
export function useTask(){const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const run=async(fn:()=>Promise<any>,success='Kaydedildi.')=>{setBusy(true);setError('');setNotice('');try{const r=await fn();setNotice(success);return r;}catch(e:any){setError(e.message||String(e));return null;}finally{setBusy(false);}};return {busy,error,notice,run};}
export function TaskStatus({task}:{task:ReturnType<typeof useTask>}){const {colors}=useTheme();return <><ErrorText text={task.error}/>{task.notice&&<T color={colors.mint} size={12}>{task.notice}</T>}{task.busy&&<Busy/>}</>;}
export function Bars({items,label,value}:{items:any[];label:(r:any)=>string;value:(r:any)=>number}){const {colors}=useTheme();const max=Math.max(1,...items.map(value));return <Stack style={{gap:12}}>{items.map((r,i)=><View key={i} style={{gap:6}}><Row style={{justifyContent:'space-between'}}><T size={11} color={colors.muted}>{label(r)}</T><T size={11} bold>{value(r).toLocaleString('tr-TR')}</T></Row><View style={{height:7,backgroundColor:colors.raised,borderRadius:5}}><LinearGradient colors={['#609afe','#4de0c7']} start={{x:0,y:0}} end={{x:1,y:0}} style={{height:7,width:`${Math.max(2,value(r)/max*100)}%`,borderRadius:5}}/></View></View>)}{!items.length&&<T color={colors.muted} size={12}>İlk tamamlanan hizmetten sonra grafik oluşacak.</T>}</Stack>;}
