"use strict";
const dkdProjects=[
{dkd_slug:"draborngo",dkd_name:"DraBornGo",dkd_symbol:"GO",dkd_kicker:"AKILLI HİZMET AĞI",dkd_color:"#65dce7",dkd_category:"MOBİL · OPERASYON",dkd_status:"GELİŞTİRİLİYOR",dkd_tagline:"Sahadaki hizmet ve teslimat akışlarını daha hızlı, ölçülebilir ve bağlantılı hale getiren yeni nesil operasyon ağı.",dkd_purpose:"Kullanıcı, saha çalışanı ve işletme arasındaki günlük operasyonu tek dijital deneyimde bir araya getirmek.",dkd_goal:"Ölçeklenebilir bir hizmet ağı oluşturarak şehir içi operasyonları daha erişilebilir ve yönetilebilir hale getirmek.",dkd_features:["Hizmet ağı","Saha operasyonu","Akıllı yönlendirme"],dkd_site:null,dkd_play:null},
{dkd_slug:"draborngames",dkd_name:"DraBornGames",dkd_symbol:"GAMES",dkd_kicker:"OYUN EVRENİ",dkd_color:"#ff877f",dkd_category:"WEB · ANDROID · OYUN",dkd_status:"YAYINDA",dkd_tagline:"Kısa oyunlardan büyük kariyer deneyimlerine uzanan DraBornEagle oyunlarının resmi oyun merkezi.",dkd_purpose:"Farklı oyun fikirlerini tek marka altında birleştiren, web ve mobil odaklı erişilebilir bir oyun platformu oluşturmak.",dkd_goal:"Yeni oyunları düzenli olarak yayınlamak ve oyuncuların tüm DraBornEagle oyunlarına tek merkezden ulaşmasını sağlamak.",dkd_features:["Web oyunları","Android deneyimleri","Ortak oyun vitrini"],dkd_site:"/DraBornGames/",dkd_play:null},
{dkd_slug:"draborngate",dkd_name:"DraBornGate",dkd_symbol:"GATE",dkd_kicker:"DİJİTAL ERİŞİM",dkd_color:"#b39cff",dkd_category:"MOBİL · ERİŞİM",dkd_status:"GELİŞTİRİLİYOR",dkd_tagline:"Fiziksel alanlarla dijital deneyim arasında hızlı ve kontrollü bir bağlantı katmanı.",dkd_purpose:"Giriş, doğrulama ve ziyaretçi akışlarını sade bir mobil deneyimle dijitalleştirmek.",dkd_goal:"Farklı mekân ve kullanım senaryolarına uyarlanabilen hızlı, anlaşılır ve güvenilir bir erişim altyapısı geliştirmek.",dkd_features:["Hızlı doğrulama","Mekân deneyimi","Kontrollü erişim"],dkd_site:"/DraBornGate/",dkd_play:null},
{dkd_slug:"drabornpark",dkd_name:"DraBornPark",dkd_symbol:"PARK",dkd_kicker:"NFC · QR ARAÇ İLETİŞİMİ",dkd_color:"#d7fc5c",dkd_category:"MOBİL · NFC · QR",dkd_status:"GELİŞTİRİLİYOR",dkd_tagline:"Araç sahibine telefon numarasını açıkça paylaşmadan NFC veya QR üzerinden ulaşmayı kolaylaştıran araç iletişim platformu.",dkd_purpose:"Park halindeki araçla ilgili acil veya gerekli iletişimi güvenli ve pratik bir dijital köprü üzerinden kurmak.",dkd_goal:"Fiziksel araç etiketini mobil deneyimle birleştirerek günlük hayatta hızlı çalışan yaygın bir araç iletişim standardı oluşturmak.",dkd_features:["NFC / QR iletişimi","Araç sahibi bağlantısı","Park konumu desteği"],dkd_site:"/DraBornPark/",dkd_play:null},
{dkd_slug:"draborntrips",dkd_name:"DraBornTrips",dkd_symbol:"TRIPS",dkd_kicker:"DENEYİM · REZERVASYON",dkd_color:"#75a8ff",dkd_category:"SEYAHAT · MOBİL",dkd_status:"PLANLANIYOR",dkd_tagline:"Tekne turları ve yerel deneyimleri keşfetmeyi, karşılaştırmayı ve rezervasyona dönüştürmeyi hedefleyen seyahat platformu.",dkd_purpose:"Yerel tur ve aktivite seçeneklerini modern, görsel ve kolay anlaşılır bir keşif deneyiminde toplamak.",dkd_goal:"İlk aşamada Antalya odaklı güçlü bir deneyim kataloğu kurmak ve zamanla daha fazla destinasyona ölçeklenmek.",dkd_features:["Tur keşfi","Rezervasyon akışı","Yerel deneyimler"],dkd_site:null,dkd_play:null},
{dkd_slug:"drabornmarket",dkd_name:"DraBornMarket",dkd_symbol:"MARKET",dkd_kicker:"FİYAT · KAMPANYA · VERİ",dkd_color:"#ffbd66",dkd_category:"ALIŞVERİŞ · VERİ",dkd_status:"GELİŞTİRİLİYOR",dkd_tagline:"Market ürünleri, fiyat geçmişi ve kampanyaları daha anlaşılır hale getirmeyi amaçlayan veri odaklı alışveriş deneyimi.",dkd_purpose:"Farklı market kaynaklarından gelen ürün ve fiyat bilgisini düzenli, karşılaştırılabilir ve kullanıcı dostu bir yapıya dönüştürmek.",dkd_goal:"Kullanıcının neyi, nereden ve ne zaman daha avantajlı alabileceğini hızlıca görebildiği güvenilir bir market veri platformu oluşturmak.",dkd_features:["Fiyat karşılaştırma","Fiyat geçmişi","Kampanya takibi"],dkd_site:null,dkd_play:null},
{dkd_slug:"drabornstyle",dkd_name:"DraBornStyle",dkd_symbol:"STYLE",dkd_kicker:"STİL · KEŞİF",dkd_color:"#ff91c8",dkd_category:"MODA · DENEYİM",dkd_status:"PLANLANIYOR",dkd_tagline:"Kişisel stil keşfini, kombin fikirlerini ve dijital ürün deneyimini tek akışta buluşturmayı hedefleyen stil platformu.",dkd_purpose:"Kullanıcıların kendi tarzlarını daha kolay keşfedebileceği modern ve görsel bir moda deneyimi tasarlamak.",dkd_goal:"Kişiselleştirilebilir stil keşfi ile ürün ve kombin deneyimini sade bir dijital merkezde birleştirmek.",dkd_features:["Stil keşfi","Kombin deneyimi","Kişiselleştirme"],dkd_site:null,dkd_play:null}
];
function dkdEscape(dkdValue){return String(dkdValue).replace(/[&<>"]/g,dkdChar=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[dkdChar]));}
function dkdProjectPath(dkdProject){return `./projects/${dkdProject.dkd_slug}/`;}
function dkdSiteAction(dkdProject){return dkdProject.dkd_site?`<a class="dkd-site-link" href="${dkdEscape(dkdProject.dkd_site)}">WEB SİTESİ ↗</a>`:`<span class="dkd-disabled-link">WEB SAYFASI YAKINDA</span>`;}
function dkdPlayAction(dkdProject,dkdDetail=false){if(dkdProject.dkd_play){return `<a class="${dkdDetail?"dkd-secondary":"dkd-site-link"}" href="${dkdEscape(dkdProject.dkd_play)}" target="_blank" rel="noopener">GOOGLE PLAY ↗</a>`;}return dkdDetail?`<span class="dkd-inactive">GOOGLE PLAY BAĞLANTISI EKLENECEK</span>`:"";}
function dkdRenderHome(){const dkdGrid=document.getElementById("dkd-project-grid");const dkdCount=document.getElementById("dkd-project-count");if(dkdCount)dkdCount.textContent=String(dkdProjects.length).padStart(2,"0");if(!dkdGrid)return;dkdGrid.innerHTML=dkdProjects.map((dkdProject,dkdIndex)=>`<article class="dkd-project-card dkd-reveal" style="--dkd-project:${dkdProject.dkd_color}"><div class="dkd-card-visual"><span class="dkd-card-code">PROJECT / ${String(dkdIndex+1).padStart(2,"0")}</span><div class="dkd-card-symbol">${dkdEscape(dkdProject.dkd_symbol)}<small>${dkdEscape(dkdProject.dkd_kicker)}</small></div></div><div class="dkd-card-body"><div class="dkd-card-meta"><span class="dkd-pill">${dkdEscape(dkdProject.dkd_category)}</span><span>${dkdEscape(dkdProject.dkd_status)}</span></div><h3>${dkdEscape(dkdProject.dkd_name)}</h3><p>${dkdEscape(dkdProject.dkd_tagline)}</p><div class="dkd-card-actions"><a class="dkd-detail-link" href="${dkdProjectPath(dkdProject)}">DETAYLARI GÖR ↗</a>${dkdSiteAction(dkdProject)}${dkdPlayAction(dkdProject)}</div></div></article>`).join("");dkdInitReveal();}
function dkdCurrentSlug(){const dkdParts=location.pathname.split("/").filter(Boolean);const dkdProjectIndex=dkdParts.indexOf("projects");return dkdProjectIndex>=0?dkdParts[dkdProjectIndex+1]||"":"";}
function dkdMockup(dkdProject){return `<div class="dkd-mockup" aria-label="${dkdEscape(dkdProject.dkd_name)} arayüz mockup önizlemesi"><div class="dkd-device"><div class="dkd-device-top"><span>09:41</span><span>● ● ●</span></div><div class="dkd-device-screen"><span class="dkd-mini-brand">${dkdEscape(dkdProject.dkd_name)}</span><div class="dkd-mini-title">${dkdEscape(dkdProject.dkd_kicker)}</div><div class="dkd-mini-block"></div><div class="dkd-mini-block dkd-short"></div><div class="dkd-mini-block"></div></div></div><div class="dkd-floating-card"><small>PROJECT EXPERIENCE</small><b>${dkdEscape(dkdProject.dkd_features[0])}</b></div></div>`;}
function dkdRenderDetail(){const dkdRoot=document.getElementById("dkd-project-detail");if(!dkdRoot)return;const dkdSlug=dkdCurrentSlug();const dkdProject=dkdProjects.find(dkdItem=>dkdItem.dkd_slug===dkdSlug);if(!dkdProject){dkdRoot.innerHTML=`<section class="dkd-detail"><p class="dkd-eyebrow">404 / PROJECT</p><h1>Proje bulunamadı.</h1><a class="dkd-back" href="../../">← HubPlatform'a dön</a></section>`;return;}document.title=`${dkdProject.dkd_name} — DraBornEagle HubPlatform`;const dkdMeta=document.querySelector('meta[name="description"]');if(dkdMeta)dkdMeta.setAttribute("content",dkdProject.dkd_tagline);dkdRoot.innerHTML=`<section class="dkd-detail" style="--dkd-project:${dkdProject.dkd_color}"><div class="dkd-detail-hero"><div class="dkd-detail-copy dkd-reveal"><p class="dkd-eyebrow">DRABORNEAGLE / ${dkdEscape(dkdProject.dkd_category)}</p><h1>${dkdEscape(dkdProject.dkd_name)}<span>.</span></h1><p class="dkd-detail-tagline">${dkdEscape(dkdProject.dkd_tagline)}</p><div class="dkd-status-row"><span>${dkdEscape(dkdProject.dkd_status)}</span><span>${dkdEscape(dkdProject.dkd_kicker)}</span></div><div class="dkd-detail-actions">${dkdProject.dkd_site?`<a class="dkd-primary" href="${dkdEscape(dkdProject.dkd_site)}">RESMİ WEB SAYFASI ↗</a>`:`<span class="dkd-inactive">ÖZEL WEB SAYFASI YAKINDA</span>`}${dkdPlayAction(dkdProject,true)}</div></div><div class="dkd-reveal">${dkdMockup(dkdProject)}</div></div><div class="dkd-detail-sections"><article class="dkd-info-panel dkd-reveal"><span>01 / AMAÇ</span><h2>Neden geliştiriyoruz?</h2><p>${dkdEscape(dkdProject.dkd_purpose)}</p></article><article class="dkd-info-panel dkd-reveal"><span>02 / HEDEF</span><h2>Nereye gidiyor?</h2><p>${dkdEscape(dkdProject.dkd_goal)}</p></article><div class="dkd-feature-strip dkd-reveal">${dkdProject.dkd_features.map((dkdFeature,dkdIndex)=>`<div><b>0${dkdIndex+1}</b><span>${dkdEscape(dkdFeature)}</span></div>`).join("")}</div></div><a class="dkd-back" href="../../">← TÜM PROJELERE DÖN</a></section>`;dkdInitReveal();}
function dkdInitReveal(){const dkdItems=document.querySelectorAll(".dkd-reveal");if(!("IntersectionObserver" in window)){dkdItems.forEach(dkdItem=>dkdItem.classList.add("dkd-visible"));return;}const dkdObserver=new IntersectionObserver(dkdEntries=>{dkdEntries.forEach(dkdEntry=>{if(dkdEntry.isIntersecting){dkdEntry.target.classList.add("dkd-visible");dkdObserver.unobserve(dkdEntry.target);}});},{threshold:.08});dkdItems.forEach(dkdItem=>dkdObserver.observe(dkdItem));}
function dkdBoot(){const dkdPage=document.body.dataset.dkdPage;if(dkdPage==="home")dkdRenderHome();if(dkdPage==="project")dkdRenderDetail();}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",dkdBoot);else dkdBoot();