create function drabornstyle.dashboard(date_from timestamptz default date_trunc('day',now()),date_to timestamptz default now()+interval '1 day') returns jsonb language sql stable security invoker set search_path='' as $$
 select jsonb_build_object(
 'services',(select jsonb_build_object('count',count(*),'revenue',coalesce(sum(service_price),0),'discount',coalesce(sum(discount),0),'collected',coalesce(sum(collected),0),'cash',coalesce(sum(collected) filter(where payment_method='cash'),0),'card',coalesce(sum(collected) filter(where payment_method='card'),0),'average_minutes',coalesce(round(avg(extract(epoch from completed_at-started_at)/60)),0)) from drabornstyle.db_style_service_sessions where completed_at between date_from and date_to),
 'finance',(select jsonb_build_object('accrued',coalesce(sum(accrued),0),'paid',coalesce(sum(paid),0),'balance',coalesce(sum(balance),0)) from drabornstyle.db_style_business_balances),
 'period_commission',(select coalesce(sum(amount),0) from drabornstyle.db_style_commission_ledger where created_at between date_from and date_to),
 'period_collections',(select coalesce(sum(amount),0) from drabornstyle.db_style_payment_requests where status='approved' and reviewed_at between date_from and date_to),
 'staff',(select coalesce(jsonb_agg(to_jsonb(t)),'[]') from (select s.id,s.business_id,s.name,s.weekly_goal,count(se.id) as customers,coalesce(sum(se.service_price),0) as revenue,coalesce(sum(se.platform_fee),0) as fees,coalesce(round(avg(extract(epoch from se.completed_at-se.started_at)/60)),0) as avg_minutes from drabornstyle.db_style_staff s left join drabornstyle.db_style_service_sessions se on se.staff_id=s.id and se.completed_at between date_from and date_to group by s.id) t),
 'businesses',(select coalesce(jsonb_agg(to_jsonb(t)),'[]') from (select b.id,b.name,b.status,ba.accrued,ba.paid,ba.balance,(select count(*) from drabornstyle.db_style_service_sessions se where se.business_id=b.id and se.completed_at between date_from and date_to) as customers,(select coalesce(sum(service_price),0) from drabornstyle.db_style_service_sessions se where se.business_id=b.id and se.completed_at between date_from and date_to) as revenue from drabornstyle.db_style_businesses b left join drabornstyle.db_style_business_balances ba on ba.business_id=b.id where ba.business_id is not null) t),
 'hours',(select coalesce(jsonb_agg(to_jsonb(t)),'[]') from (select extract(hour from started_at at time zone 'Europe/Istanbul') as hour,count(*) as customers from drabornstyle.db_style_service_sessions where completed_at between date_from and date_to group by 1 order by 1) t),
 'popular_services',(select coalesce(jsonb_agg(to_jsonb(t)),'[]') from (select v.name,count(se.id) as customers from drabornstyle.db_style_service_sessions se join drabornstyle.db_style_services v on v.id=se.service_id where se.completed_at between date_from and date_to group by v.name order by count(*) desc limit 8) t),
 'appointments',(select jsonb_build_object('cancelled',count(*) filter(where status='cancelled'),'no_show',count(*) filter(where status='no_show'),'pending',count(*) filter(where status in ('confirmed','late'))) from drabornstyle.db_style_appointments where starts_at between date_from and date_to),
 'weekly',(select coalesce(jsonb_agg(to_jsonb(t)),'[]') from (select (completed_at at time zone 'Europe/Istanbul')::date as date,count(*) as customers,coalesce(sum(service_price),0) as revenue from drabornstyle.db_style_service_sessions where completed_at>now()-interval '28 days' group by 1 order by 1) t),
 'repeat_rate',(select coalesce(round(100.0*count(*) filter(where visits>1)/nullif(count(*),0)),0) from drabornstyle.db_style_customer_loyalty),
 'forecast_week',(select round(coalesce(sum(service_price),0)/4,2) from drabornstyle.db_style_service_sessions where completed_at>now()-interval '28 days')
 ); $$;
revoke all on function drabornstyle.dashboard(timestamptz,timestamptz) from public,anon;
grant execute on function drabornstyle.dashboard(timestamptz,timestamptz) to authenticated;
