-- DraBornStyle v0.1: isolated tenants, decimal TRY, Europe/Istanbul calendars.
create schema if not exists drabornstyle;
create schema if not exists drabornstyle_private;
revoke all on schema drabornstyle_private from public;
grant usage on schema drabornstyle, drabornstyle_private to authenticated;
grant usage on schema drabornstyle to anon;
create extension if not exists btree_gist with schema extensions;

create table drabornstyle.db_style_profiles (
 id uuid primary key references auth.users(id), display_name text not null check(length(display_name) between 2 and 100), phone text, avatar_url text,
 marketing_consent boolean not null default false, legal_version text not null default '2026-10-10', deleted_at timestamptz, created_at timestamptz not null default now());
create table drabornstyle.db_style_admin_users (user_id uuid primary key references auth.users(id), active boolean not null default true, created_at timestamptz not null default now());
create table drabornstyle.db_style_businesses (
 id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id), name text not null check(length(name) between 2 and 120), slug text unique not null,
 description text not null default '', address text not null, city text not null default '', phone text, latitude numeric(10,7) check(latitude between -90 and 90), longitude numeric(10,7) check(longitude between -180 and 180),
 logo_url text, cover_url text, gallery jsonb not null default '[]', status text not null default 'pending' check(status in ('pending','active','suspended','rejected')),
 timezone text not null default 'Europe/Istanbul' check(timezone='Europe/Istanbul'), created_at timestamptz not null default now());
create table drabornstyle.db_style_business_members (business_id uuid references drabornstyle.db_style_businesses(id), user_id uuid references auth.users(id), role text not null check(role in ('owner','manager','staff')), active boolean not null default true, created_at timestamptz not null default now(), primary key(business_id,user_id));
create table drabornstyle.db_style_staff (
 id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), user_id uuid references auth.users(id), name text not null, bio text not null default '', photo_url text, specialties text[] not null default '{}', active boolean not null default true,
 can_discount boolean not null default false, max_discount_pct numeric(5,2) not null default 0 check(max_discount_pct between 0 and 100), weekly_goal numeric(12,2) not null default 0,
 created_at timestamptz not null default now(), unique(id,business_id), unique(business_id,user_id));
create table drabornstyle.db_style_services (
 id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), name text not null,
 duration_minutes integer not null check(duration_minutes between 5 and 480), buffer_minutes integer not null default 0 check(buffer_minutes between 0 and 120), price numeric(12,2) not null check(price>=0), active boolean not null default true,
 created_at timestamptz not null default now(), unique(id,business_id));
create table drabornstyle.db_style_staff_services (staff_id uuid references drabornstyle.db_style_staff(id), service_id uuid references drabornstyle.db_style_services(id), business_id uuid not null references drabornstyle.db_style_businesses(id), primary key(staff_id,service_id), foreign key(staff_id,business_id) references drabornstyle.db_style_staff(id,business_id), foreign key(service_id,business_id) references drabornstyle.db_style_services(id,business_id));
create table drabornstyle.db_style_staff_schedules (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), staff_id uuid not null, weekday integer not null check(weekday between 0 and 6), opens time not null, closes time not null check(closes>opens), created_at timestamptz not null default now(), unique(staff_id,weekday), foreign key(staff_id,business_id) references drabornstyle.db_style_staff(id,business_id));
create table drabornstyle.db_style_staff_availability (staff_id uuid primary key references drabornstyle.db_style_staff(id), business_id uuid not null references drabornstyle.db_style_businesses(id), state text not null default 'available' check(state in ('available','working','break','busy','off')), busy_until timestamptz, updated_at timestamptz not null default now(), foreign key(staff_id,business_id) references drabornstyle.db_style_staff(id,business_id));
create table drabornstyle.db_style_staff_breaks (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), staff_id uuid not null, starts_at timestamptz not null, ends_at timestamptz not null check(ends_at>starts_at), reason text not null default 'Mola', created_at timestamptz not null default now(), foreign key(staff_id,business_id) references drabornstyle.db_style_staff(id,business_id));
create table drabornstyle.db_style_customers (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), staff_id uuid references drabornstyle.db_style_staff(id), user_id uuid references auth.users(id), name text not null, phone text, marketing_consent boolean not null default false, created_at timestamptz not null default now(), unique(id,business_id));
create unique index db_style_customer_user on drabornstyle.db_style_customers(business_id,user_id) where user_id is not null;
create table drabornstyle.db_style_customer_notes (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), customer_id uuid not null references drabornstyle.db_style_customers(id), staff_id uuid not null references drabornstyle.db_style_staff(id), author_id uuid not null references auth.users(id), note text not null check(length(note)<=2000), created_at timestamptz not null default now());
create table drabornstyle.db_style_commission_rules (business_id uuid primary key references drabornstyle.db_style_businesses(id), fixed_fee numeric(12,2) not null default 20 check(fixed_fee>=0), percentage numeric(5,2) not null default 0 check(percentage between 0 and 100), sources text[] not null default '{platform}', discount_affects_commission boolean not null default false, updated_at timestamptz not null default now());
create table drabornstyle.db_style_referral_codes (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), staff_id uuid not null references drabornstyle.db_style_staff(id), code text unique not null, percent numeric(5,2) not null check(percent between 0 and 100), expires_at timestamptz, max_uses integer check(max_uses>0), uses integer not null default 0, customer_user_id uuid references auth.users(id), active boolean not null default true, created_at timestamptz not null default now());
create table drabornstyle.db_style_appointments (
 id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), staff_id uuid not null, service_id uuid not null, customer_id uuid references drabornstyle.db_style_customers(id), customer_user_id uuid references auth.users(id),
 customer_name text not null, source text not null default 'platform' check(source in ('platform','walk_in','phone','private')),
 starts_at timestamptz not null, ends_at timestamptz not null, reserved_until timestamptz not null,
 status text not null default 'confirmed' check(status in ('confirmed','late','in_progress','completed','cancelled','no_show')),
 base_price numeric(12,2) not null check(base_price>=0), service_price numeric(12,2) not null check(service_price>=0), platform_fee numeric(12,2) not null check(platform_fee>=0), referral_id uuid references drabornstyle.db_style_referral_codes(id), recurrence_id uuid,
 created_at timestamptz not null default now(), check(ends_at>starts_at and reserved_until>=ends_at), unique(id,business_id),
 foreign key(staff_id,business_id) references drabornstyle.db_style_staff(id,business_id), foreign key(service_id,business_id) references drabornstyle.db_style_services(id,business_id),
 constraint db_style_no_overlap exclude using gist (staff_id with =, tstzrange(starts_at,reserved_until,'[)') with &&) where(status in ('confirmed','late','in_progress')));
create table drabornstyle.db_style_appointment_events (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), appointment_id uuid not null references drabornstyle.db_style_appointments(id), actor_id uuid references auth.users(id), event text not null, data jsonb not null default '{}', created_at timestamptz not null default now());
create table drabornstyle.db_style_waitlists (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), staff_id uuid not null references drabornstyle.db_style_staff(id), service_id uuid not null references drabornstyle.db_style_services(id), user_id uuid not null references auth.users(id), starts_at timestamptz not null, ends_at timestamptz not null check(ends_at>starts_at), status text not null default 'waiting', created_at timestamptz not null default now());
create table drabornstyle.db_style_availability_requests (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), staff_id uuid not null references drabornstyle.db_style_staff(id), user_id uuid not null references auth.users(id), starts_at timestamptz not null, ends_at timestamptz not null check(ends_at>starts_at), message text not null default '', status text not null default 'pending', created_at timestamptz not null default now());
create table drabornstyle.db_style_service_sessions (
 id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), appointment_id uuid unique not null references drabornstyle.db_style_appointments(id), staff_id uuid not null references drabornstyle.db_style_staff(id), customer_id uuid references drabornstyle.db_style_customers(id), customer_user_id uuid references auth.users(id), service_id uuid not null references drabornstyle.db_style_services(id), source text not null,
 started_at timestamptz not null default now(), estimated_end timestamptz not null, completed_at timestamptz,
 base_price numeric(12,2) not null, service_price numeric(12,2) not null, discount numeric(12,2) not null default 0, discount_reason text, discounted_by uuid references auth.users(id), platform_fee numeric(12,2) not null,
 payment_method text check(payment_method in ('cash','card','transfer')), collected numeric(12,2) not null default 0, created_at timestamptz not null default now(), check(service_price>=0 and platform_fee>=0 and collected>=0));
create unique index db_style_one_live_session on drabornstyle.db_style_service_sessions(staff_id) where completed_at is null;
create table drabornstyle.db_style_discounts (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), session_id uuid not null references drabornstyle.db_style_service_sessions(id), actor_id uuid not null references auth.users(id), old_price numeric(12,2) not null, new_price numeric(12,2) not null, amount numeric(12,2) not null, reason text not null, created_at timestamptz not null default now());
create table drabornstyle.db_style_commission_ledger (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), staff_id uuid not null references drabornstyle.db_style_staff(id), session_id uuid not null unique references drabornstyle.db_style_service_sessions(id), amount numeric(12,2) not null check(amount>=0), paid numeric(12,2) not null default 0 check(paid>=0 and paid<=amount), state text not null default 'accrued', source text not null, created_at timestamptz not null default now());
create table drabornstyle.db_style_commission_adjustments (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), ledger_id uuid not null references drabornstyle.db_style_commission_ledger(id), amount numeric(12,2) not null, reason text not null, actor_id uuid not null references auth.users(id), created_at timestamptz not null default now());
create table drabornstyle.db_style_business_balances (business_id uuid primary key references drabornstyle.db_style_businesses(id), accrued numeric(12,2) not null default 0, paid numeric(12,2) not null default 0, balance numeric(12,2) generated always as(accrued-paid) stored, updated_at timestamptz not null default now(), check(accrued>=paid and paid>=0));
create table drabornstyle.db_style_payment_schedules (business_id uuid primary key references drabornstyle.db_style_businesses(id), period text not null default 'weekly' check(period in ('weekly','monthly')), payment_day integer not null default 1, next_due date not null, check((period='weekly' and payment_day between 1 and 7) or (period='monthly' and payment_day between 1 and 28)));
create table drabornstyle.db_style_payment_requests (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), amount numeric(12,2) not null check(amount>0), method text not null check(method in ('transfer','cash')), paid_at timestamptz not null, status text not null default 'pending' check(status in ('pending','reviewing','approved','rejected')), submitted_by uuid not null references auth.users(id), reviewed_by uuid references auth.users(id), reviewed_at timestamptz, note text, idempotency_key uuid not null unique, created_at timestamptz not null default now());
create table drabornstyle.db_style_payment_allocations (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), request_id uuid not null references drabornstyle.db_style_payment_requests(id), ledger_id uuid not null references drabornstyle.db_style_commission_ledger(id), amount numeric(12,2) not null check(amount>0), created_at timestamptz not null default now(), unique(request_id,ledger_id));
create table drabornstyle.db_style_payment_receipts (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), request_id uuid not null references drabornstyle.db_style_payment_requests(id), storage_path text not null unique, uploaded_by uuid not null references auth.users(id), created_at timestamptz not null default now());
create table drabornstyle.db_style_conversations (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), appointment_id uuid unique not null references drabornstyle.db_style_appointments(id), staff_id uuid not null references drabornstyle.db_style_staff(id), customer_user_id uuid not null references auth.users(id), blocked boolean not null default false, created_at timestamptz not null default now());
create table drabornstyle.db_style_messages (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), conversation_id uuid not null references drabornstyle.db_style_conversations(id), sender_id uuid not null references auth.users(id), body text not null check(length(body) between 1 and 4000), read_at timestamptz, client_id uuid not null unique, created_at timestamptz not null default now());
create table drabornstyle.db_style_conversation_presence (conversation_id uuid references drabornstyle.db_style_conversations(id), user_id uuid references auth.users(id), typing_until timestamptz, updated_at timestamptz not null default now(), primary key(conversation_id,user_id));
create table drabornstyle.db_style_notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), business_id uuid references drabornstyle.db_style_businesses(id), kind text not null, title text not null, body text not null, dedupe_key text not null, data jsonb not null default '{}', read_at timestamptz, created_at timestamptz not null default now(), unique(user_id,dedupe_key));
create table drabornstyle.db_style_notification_preferences (user_id uuid primary key references auth.users(id), appointments boolean not null default true, messages boolean not null default true, marketing boolean not null default false, created_at timestamptz not null default now());
create table drabornstyle.db_style_location_sessions (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), appointment_id uuid unique not null references drabornstyle.db_style_appointments(id), user_id uuid not null references auth.users(id), consent_at timestamptz not null, expires_at timestamptz not null, revoked_at timestamptz, latitude numeric(10,7) check(latitude between -90 and 90), longitude numeric(10,7) check(longitude between -180 and 180), accuracy numeric(8,2), distance_km numeric(8,3), eta_minutes integer, updated_at timestamptz not null default now());
create table drabornstyle.db_style_reviews (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), appointment_id uuid unique not null references drabornstyle.db_style_appointments(id), staff_id uuid not null references drabornstyle.db_style_staff(id), user_id uuid not null references auth.users(id), rating integer not null check(rating between 1 and 5), body text not null default '', created_at timestamptz not null default now());
create table drabornstyle.db_style_customer_loyalty (business_id uuid references drabornstyle.db_style_businesses(id), customer_id uuid references drabornstyle.db_style_customers(id), visits integer not null default 0, last_visit timestamptz, primary key(business_id,customer_id));
create table drabornstyle.db_style_business_settings (business_id uuid primary key references drabornstyle.db_style_businesses(id), loyalty_every integer not null default 0 check(loyalty_every>=0), loyalty_percent numeric(5,2) not null default 0 check(loyalty_percent between 0 and 100), auto_reply text not null default 'Mesai dışında gelen mesajına en kısa sürede yanıt vereceğiz.', created_at timestamptz not null default now());
create table drabornstyle.db_style_queue (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), staff_id uuid not null references drabornstyle.db_style_staff(id), service_id uuid not null references drabornstyle.db_style_services(id), customer_user_id uuid references auth.users(id), customer_name text not null, state text not null default 'waiting' check(state in ('waiting','started','cancelled')), created_at timestamptz not null default now());
create table drabornstyle.db_style_expenses (id uuid primary key default gen_random_uuid(), business_id uuid not null references drabornstyle.db_style_businesses(id), amount numeric(12,2) not null check(amount>0), category text not null, note text, actor_id uuid not null references auth.users(id), created_at timestamptz not null default now());
create table drabornstyle.db_style_support_requests (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), business_id uuid references drabornstyle.db_style_businesses(id), kind text not null, body text not null, status text not null default 'pending', created_at timestamptz not null default now());
create table drabornstyle.db_style_admin_logs (id uuid primary key default gen_random_uuid(), business_id uuid references drabornstyle.db_style_businesses(id), actor_id uuid references auth.users(id), action text not null, target_id uuid, data jsonb not null default '{}', created_at timestamptz not null default now());
create table drabornstyle.db_style_analytics_events (id uuid primary key default gen_random_uuid(), business_id uuid references drabornstyle.db_style_businesses(id), user_id uuid references auth.users(id), event text not null, data jsonb not null default '{}', created_at timestamptz not null default now());

create function drabornstyle_private.is_admin() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from drabornstyle.db_style_admin_users where user_id=auth.uid() and active); $$;
create function drabornstyle_private.manages(b uuid) returns boolean language sql stable security definer set search_path='' as $$ select drabornstyle_private.is_admin() or exists(select 1 from drabornstyle.db_style_business_members where business_id=b and user_id=auth.uid() and role in ('owner','manager') and active); $$;
create function drabornstyle_private.works(s uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from drabornstyle.db_style_staff t join drabornstyle.db_style_businesses b on b.id=t.business_id where t.id=s and t.active and b.status='active' and (t.user_id=auth.uid() or drabornstyle_private.manages(t.business_id))); $$;
create function drabornstyle_private.owns_staff(s uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from drabornstyle.db_style_staff where id=s and user_id=auth.uid() and active); $$;
create function drabornstyle_private.appointment_access(a uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from drabornstyle.db_style_appointments where id=a and (customer_user_id=auth.uid() or drabornstyle_private.owns_staff(staff_id) or drabornstyle_private.manages(business_id))); $$;
create function drabornstyle_private.chat_access(c uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from drabornstyle.db_style_conversations where id=c and (customer_user_id=auth.uid() or drabornstyle_private.owns_staff(staff_id) or drabornstyle_private.manages(business_id))); $$;
create function drabornstyle_private.notify(u uuid,b uuid,k text,t text,msg text,key text,d jsonb default '{}') returns void language sql security definer set search_path='' as $$ insert into drabornstyle.db_style_notifications(user_id,business_id,kind,title,body,dedupe_key,data) select u,b,k,t,msg,key,d where u is not null on conflict(user_id,dedupe_key) do nothing; $$;
create function drabornstyle_private.audit(b uuid,a text,t uuid,d jsonb default '{}') returns void language sql security definer set search_path='' as $$ insert into drabornstyle.db_style_admin_logs(business_id,actor_id,action,target_id,data) values(b,auth.uid(),a,t,d); $$;

-- Every table is RLS protected. Authenticated clients receive SELECT only.
do $$ declare t record; begin
 for t in select tablename from pg_tables where schemaname='drabornstyle' loop
 execute format('alter table drabornstyle.%I enable row level security',t.tablename);
 execute format('grant select on drabornstyle.%I to authenticated',t.tablename);
 end loop;
end $$;
create policy own_profile on drabornstyle.db_style_profiles for select to authenticated using(id=(select auth.uid()) or drabornstyle_private.is_admin());
create policy own_admin on drabornstyle.db_style_admin_users for select to authenticated using(user_id=(select auth.uid()));
create policy business_read on drabornstyle.db_style_businesses for select to authenticated using(status='active' or drabornstyle_private.manages(id) or owner_id=(select auth.uid()));
create policy member_read on drabornstyle.db_style_business_members for select to authenticated using(user_id=(select auth.uid()) or drabornstyle_private.manages(business_id));
create policy staff_read on drabornstyle.db_style_staff for select to authenticated using(user_id=(select auth.uid()) or drabornstyle_private.manages(business_id));
create policy appointment_read on drabornstyle.db_style_appointments for select to authenticated using(customer_user_id=(select auth.uid()) or drabornstyle_private.owns_staff(staff_id) or drabornstyle_private.manages(business_id));
create policy event_read on drabornstyle.db_style_appointment_events for select to authenticated using(drabornstyle_private.appointment_access(appointment_id));
create policy session_read on drabornstyle.db_style_service_sessions for select to authenticated using(customer_user_id=(select auth.uid()) or drabornstyle_private.owns_staff(staff_id) or drabornstyle_private.manages(business_id));
create policy customer_read on drabornstyle.db_style_customers for select to authenticated using(user_id=(select auth.uid()) or drabornstyle_private.owns_staff(staff_id) or drabornstyle_private.manages(business_id));
create policy note_read on drabornstyle.db_style_customer_notes for select to authenticated using(drabornstyle_private.owns_staff(staff_id) or drabornstyle_private.manages(business_id));
create policy conversation_read on drabornstyle.db_style_conversations for select to authenticated using(drabornstyle_private.chat_access(id));
create policy message_read on drabornstyle.db_style_messages for select to authenticated using(drabornstyle_private.chat_access(conversation_id));
create policy presence_read on drabornstyle.db_style_conversation_presence for select to authenticated using(drabornstyle_private.chat_access(conversation_id));
create policy location_read on drabornstyle.db_style_location_sessions for select to authenticated using(user_id=(select auth.uid()) or (revoked_at is null and expires_at>now() and drabornstyle_private.appointment_access(appointment_id) and exists(select 1 from drabornstyle.db_style_appointments a where a.id=appointment_id and a.status in ('confirmed','late','in_progress'))));
create policy notification_read on drabornstyle.db_style_notifications for select to authenticated using(user_id=(select auth.uid()));
create policy preference_read on drabornstyle.db_style_notification_preferences for select to authenticated using(user_id=(select auth.uid()));
create policy support_read on drabornstyle.db_style_support_requests for select to authenticated using(user_id=(select auth.uid()) or drabornstyle_private.is_admin());
create policy reviews_read on drabornstyle.db_style_reviews for select to authenticated using(true);
create policy queue_read on drabornstyle.db_style_queue for select to authenticated using(customer_user_id=(select auth.uid()) or drabornstyle_private.owns_staff(staff_id) or drabornstyle_private.manages(business_id));
do $$ declare t text; begin
 foreach t in array array['db_style_staff_schedules','db_style_staff_availability','db_style_staff_breaks','db_style_services','db_style_staff_services','db_style_business_settings'] loop
 execute format('create policy directory_read on drabornstyle.%I for select to authenticated using(exists(select 1 from drabornstyle.db_style_businesses b where b.id=business_id and b.status=''active'') or drabornstyle_private.manages(business_id))',t);
 end loop;
 foreach t in array array['db_style_waitlists','db_style_availability_requests'] loop
 execute format('create policy request_read on drabornstyle.%I for select to authenticated using(user_id=(select auth.uid()) or drabornstyle_private.owns_staff(staff_id) or drabornstyle_private.manages(business_id))',t);
 end loop;
 foreach t in array array['db_style_referral_codes','db_style_commission_ledger'] loop
 execute format('create policy staff_finance_read on drabornstyle.%I for select to authenticated using(drabornstyle_private.owns_staff(staff_id) or drabornstyle_private.manages(business_id))',t);
 end loop;
 foreach t in array array['db_style_commission_rules','db_style_commission_adjustments','db_style_business_balances','db_style_payment_schedules','db_style_payment_requests','db_style_payment_allocations','db_style_payment_receipts','db_style_expenses','db_style_admin_logs','db_style_analytics_events'] loop
 execute format('create policy manager_read on drabornstyle.%I for select to authenticated using(drabornstyle_private.manages(business_id))',t);
 end loop;
end $$;
create policy discount_read on drabornstyle.db_style_discounts for select to authenticated using(actor_id=(select auth.uid()) or drabornstyle_private.manages(business_id));
create policy loyalty_read on drabornstyle.db_style_customer_loyalty for select to authenticated using(drabornstyle_private.manages(business_id) or exists(select 1 from drabornstyle.db_style_customers c where c.id=customer_id and (c.user_id=(select auth.uid()) or drabornstyle_private.owns_staff(c.staff_id))));

-- Indexed tenant and FK access, with read-only snapshots for audit records.
do $$ declare c record; begin
 for c in select table_name,column_name from information_schema.columns where table_schema='drabornstyle' and column_name in ('business_id','staff_id','user_id','customer_user_id','appointment_id','conversation_id','customer_id','service_id','session_id','request_id','ledger_id','actor_id','owner_id','sender_id','submitted_by','reviewed_by','discounted_by','author_id','uploaded_by','referral_id') loop
 execute format('create index if not exists %I on drabornstyle.%I(%I)',left(c.table_name||'_'||c.column_name||'_idx',63),c.table_name,c.column_name);
 end loop;
end $$;
create index db_style_sessions_time on drabornstyle.db_style_service_sessions(business_id,completed_at desc);
create index db_style_appointments_time on drabornstyle.db_style_appointments(staff_id,starts_at);
create index db_style_messages_time on drabornstyle.db_style_messages(conversation_id,created_at);
create index db_style_notifications_time on drabornstyle.db_style_notifications(user_id,created_at desc);

insert into drabornstyle.db_style_admin_users(user_id) select id from auth.users where lower(email)='draborneagle@gmail.com' on conflict do nothing;
-- Auth is shared: never reset an existing user's password or edit another project's profile.
revoke all on all functions in schema drabornstyle_private from public, anon, authenticated;
grant execute on function drabornstyle_private.is_admin(),drabornstyle_private.manages(uuid),drabornstyle_private.owns_staff(uuid),drabornstyle_private.works(uuid),drabornstyle_private.appointment_access(uuid),drabornstyle_private.chat_access(uuid) to authenticated;
