-- Audited system announcements; never generated by the client directly.
do $migration$
declare def text; needle text := $anchor$ when 'profile' then$anchor$;
begin
 select pg_get_functiondef('drabornstyle_private.api(text,jsonb)'::regprocedure) into def;
 if position(needle in def)=0 then raise exception 'Expected API implementation missing'; end if;
 execute replace(def,needle,$feature$ when 'announcement' then
  if not drabornstyle_private.is_admin() then raise exception 'Admin yetkisi gerekli.' using errcode='42501'; end if;
  if length(coalesce(data->>'title','')) not between 3 and 120 or length(coalesce(data->>'body','')) not between 3 and 2000 or data->>'audience' not in ('all','staff','business') then raise exception 'Başlık, duyuru metni ve hedef kitle gerekli.'; end if;
  key:=(data->>'key')::uuid;
  if key is null then raise exception 'İşlem anahtarı gerekli.'; end if;
  for r in select p.id from drabornstyle.db_style_profiles p where p.deleted_at is null and (data->>'audience'='all' or (data->>'audience'='staff' and exists(select 1 from drabornstyle.db_style_staff st where st.user_id=p.id and st.active)) or (data->>'audience'='business' and exists(select 1 from drabornstyle.db_style_business_members m where m.user_id=p.id and m.active and m.role in ('owner','manager')))) loop
   perform drabornstyle_private.notify(r.id,null,'announcement',data->>'title',data->>'body','announcement:'||key);
  end loop;
  perform drabornstyle_private.audit(null,action,key,jsonb_build_object('title',data->>'title','audience',data->>'audience'));
 when 'profile' then$feature$);
end $migration$;
notify pgrst,'reload schema';
