-- Run in a single transaction. All fixture data and role changes are rolled back.
begin;
set local statement_timeout='60s';
create temp table db_style_test_results(name text,passed boolean);
grant select,insert on db_style_test_results to authenticated;
do $$
declare u uuid; other_u uuid; b uuid; b2 uuid; s uuid; s2 uuid; v uuid; a uuid; se uuid; pr uuid; t timestamptz; j jsonb; key uuid; val numeric; hit boolean;
begin
 select user_id into u from drabornstyle.db_style_admin_users where active limit 1;
 if u is null then raise exception 'Test için mevcut bir Style admin hesabı gerekli.'; end if;
 select id into other_u from auth.users where id<>u limit 1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 b:=(drabornstyle_private.api('business_create','{"name":"QA Rollback Studio","address":"Test adresi","city":"Test"}')->>'id')::uuid;
 perform drabornstyle_private.api('business_status',jsonb_build_object('business_id',b,'status','active'));
 s:=(drabornstyle_private.api('staff_save',jsonb_build_object('business_id',b,'name','QA Usta','max_discount_pct',20,'can_discount',true))->>'id')::uuid;
 v:=(drabornstyle_private.api('service_save',jsonb_build_object('business_id',b,'name','Saç','price',350,'duration',30,'buffer',0))->>'id')::uuid;
 perform drabornstyle_private.api('schedule_save',jsonb_build_object('staff_id',s,'weekday',extract(dow from now() at time zone 'Europe/Istanbul'),'opens','00:00','closes','23:59'));
 update drabornstyle.db_style_staff set user_id=u where id=s;
 t:=now()+interval '1 minute';
 perform drabornstyle_private.api('referral_create',jsonb_build_object('staff_id',s,'code','QA'||substr(replace(b::text,'-',''),1,16),'percent',15));
 j:=drabornstyle_private.api('quote',jsonb_build_object('staff_id',s,'service_id',v,'code','QA'||substr(replace(b::text,'-',''),1,16)));
 insert into db_style_test_results values('350 TL, %15 indirim ve 20 TL bedel = 317.50',(j->>'total')::numeric=317.50);
 a:=(drabornstyle_private.api('book',jsonb_build_object('staff_id',s,'service_id',v,'starts_at',t,'code','QA'||substr(replace(b::text,'-',''),1,16),'expected_total',317.50))->>'id')::uuid;
 hit:=false;begin perform drabornstyle_private.api('book',jsonb_build_object('staff_id',s,'service_id',v,'starts_at',t));exception when exclusion_violation then hit:=true;end;
 insert into db_style_test_results values('Aynı zaman aralığına ikinci rezervasyon reddedilir',hit);
 hit:=false;begin perform drabornstyle_private.api('status',jsonb_build_object('staff_id',s,'state','busy','minutes',60));exception when others then hit:=true;end;
 insert into db_style_test_results values('Meşguliyet onaylı randevuyu bozmaz',hit);
 se:=(drabornstyle_private.api('start',jsonb_build_object('appointment_id',a))->>'id')::uuid;
 insert into db_style_test_results values('Başlangıç anlık çalışma durumunu günceller',(select state='working' from drabornstyle.db_style_staff_availability where staff_id=s));
 j:=drabornstyle_private.api('finish',jsonb_build_object('session_id',se,'price',297.50,'method','cash'));
 perform drabornstyle_private.api('finish',jsonb_build_object('session_id',se,'price',1,'method','cash'));
 insert into db_style_test_results values('Tek hizmet tek komisyon ve tekrar tamamlama güvenliği',(select count(*)=1 and sum(amount)=20 from drabornstyle.db_style_commission_ledger where session_id=se));
 insert into db_style_test_results values('Kalıcı ustaya özel müşteri kodu',(select count(*)=1 from drabornstyle.db_style_customer_referrals where user_id=u and staff_id=s));
 key:=gen_random_uuid();pr:=(drabornstyle_private.api('payment_submit',jsonb_build_object('business_id',b,'amount',10,'method','transfer','paid_at',now(),'key',key))->>'id')::uuid;
 insert into db_style_test_results values('Ödeme bildirimi borcu azaltmaz',(select balance=20 from drabornstyle.db_style_business_balances where business_id=b));
 perform drabornstyle_private.api('payment_review',jsonb_build_object('id',pr,'status','approved'));
 perform drabornstyle_private.api('payment_review',jsonb_build_object('id',pr,'status','approved'));
 insert into db_style_test_results values('Kısmi ödeme onayı ve yinelenen onay = 10 TL bakiye',(select balance=10 and paid=10 from drabornstyle.db_style_business_balances where business_id=b));
 pr:=(drabornstyle_private.api('payment_submit',jsonb_build_object('business_id',b,'amount',5,'method','cash','paid_at',now(),'key',gen_random_uuid()))->>'id')::uuid;
 perform drabornstyle_private.api('payment_review',jsonb_build_object('id',pr,'status','rejected'));
 insert into db_style_test_results values('Reddedilen ödeme borçtan düşülmez',(select balance=10 from drabornstyle.db_style_business_balances where business_id=b));
 se:=(drabornstyle_private.api('start',jsonb_build_object('staff_id',s,'service_id',v,'source','walk_in','customer_name','Misafir'))->>'id')::uuid;
 perform drabornstyle_private.api('finish',jsonb_build_object('session_id',se,'price',350));
 insert into db_style_test_results values('Varsayılan çat kapı komisyonu sıfır',(select amount=0 from drabornstyle.db_style_commission_ledger where session_id=se));
 perform drabornstyle_private.api('commission_rule',jsonb_build_object('business_id',b,'fee',25,'sources',jsonb_build_array('platform','walk_in')));
 se:=(drabornstyle_private.api('start',jsonb_build_object('staff_id',s,'service_id',v,'source','walk_in','customer_name','Misafir 2'))->>'id')::uuid;
 perform drabornstyle_private.api('finish',jsonb_build_object('session_id',se,'price',300,'reason','Özel indirim'));
 insert into db_style_test_results values('İşletmeye özel 25 TL komisyon ve anlaşmalı çat kapı',(select amount=25 from drabornstyle.db_style_commission_ledger where session_id=se));
 a:=(drabornstyle_private.api('book',jsonb_build_object('staff_id',s,'service_id',v,'starts_at',now()+interval '1 minute'))->>'id')::uuid;
 hit:=false;begin perform drabornstyle_private.api('location_update',jsonb_build_object('appointment_id',a,'latitude',40,'longitude',30));exception when others then hit:=true;end;
 insert into db_style_test_results values('İzin olmadan konum kaydı reddedilir',hit);
 perform drabornstyle_private.api('location_consent',jsonb_build_object('appointment_id',a));
 perform drabornstyle_private.api('location_update',jsonb_build_object('appointment_id',a,'latitude',40,'longitude',30,'accuracy',15));
 perform drabornstyle_private.api('location_revoke',jsonb_build_object('appointment_id',a));
 insert into db_style_test_results values('İzin geri çekilince konum temizlenir',(select latitude is null and revoked_at is not null from drabornstyle.db_style_location_sessions where appointment_id=a));
 perform drabornstyle_private.notify(u,b,'test','Test','Test','qa-dedupe:'||b);perform drabornstyle_private.notify(u,b,'test','Test','Test','qa-dedupe:'||b);
 insert into db_style_test_results values('Bildirimler yinelenmez',(select count(*)=1 from drabornstyle.db_style_notifications where user_id=u and dedupe_key='qa-dedupe:'||b));
 b2:=(drabornstyle_private.api('business_create','{"name":"QA Other Tenant","address":"Test adresi"}')->>'id')::uuid;
 s2:=(drabornstyle_private.api('staff_save',jsonb_build_object('business_id',b2,'name','Başka usta'))->>'id')::uuid;
 if other_u is not null then update drabornstyle.db_style_businesses set owner_id=other_u where id=b2;end if;
 update drabornstyle.db_style_admin_users set active=false where user_id=u;
 delete from drabornstyle.db_style_business_members where business_id in(b,b2) and user_id=u;
 perform set_config('role','authenticated',true);
 insert into db_style_test_results values('Usta başka ustanın özel bilgilerini okuyamaz',(select count(*)=0 from drabornstyle.db_style_staff where id=s2));
 insert into db_style_test_results values('Başka işletmenin finans kaydı okunamaz',(select count(*)=0 from drabornstyle.db_style_business_balances where business_id=b2));
 hit:=false;begin perform drabornstyle.api('commission_rule',jsonb_build_object('business_id',b,'fee',1));exception when insufficient_privilege then hit:=true;end;
 insert into db_style_test_results values('Usta platform ücretini değiştiremez',hit);
 hit:=false;begin update drabornstyle.db_style_service_sessions set service_price=1 where id=se;exception when insufficient_privilege then hit:=true;end;
 insert into db_style_test_results values('İstemci finans kayıtlarına doğrudan yazamaz',hit);
 perform set_config('role','postgres',true);
end $$;
select jsonb_agg(jsonb_build_object('test',name,'passed',passed)) as results from db_style_test_results;
rollback;
