-- Extra workflow regressions. Never persists fixtures or changes shared Auth accounts.
begin;
set local statement_timeout='60s';
create temp table db_style_workflow_results(name text,passed boolean);
grant select,insert on db_style_workflow_results to authenticated;
do $$
declare u uuid; b uuid; s uuid; v uuid; se uuid; ledger uuid; payment uuid; a uuid; t timestamptz; j jsonb; hit boolean; i integer;
begin
 select user_id into u from drabornstyle.db_style_admin_users where active limit 1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 b:=(drabornstyle_private.api('business_create','{"name":"QA Workflow Rollback","address":"Test adresi"}')->>'id')::uuid;
 perform drabornstyle_private.api('business_status',jsonb_build_object('business_id',b,'status','active'));
 s:=(drabornstyle_private.api('staff_save',jsonb_build_object('business_id',b,'name','QA Usta','weekly_goal',5000,'specialties',jsonb_build_array('Saç','Sakal')))->>'id')::uuid;
 update drabornstyle.db_style_staff set user_id=u where id=s;
 v:=(drabornstyle_private.api('service_save',jsonb_build_object('business_id',b,'name','Saç','price',350,'duration',30))->>'id')::uuid;
 insert into db_style_workflow_results values('Usta hedefi ve uzmanlıkları kaydedilir',(select weekly_goal=5000 and specialties=array['Saç','Sakal'] from drabornstyle.db_style_staff where id=s));
 for i in 0..6 loop perform drabornstyle_private.api('schedule_save',jsonb_build_object('staff_id',s,'weekday',i,'opens','00:00','closes','23:59'));end loop;
 perform drabornstyle_private.api('commission_rule',jsonb_build_object('business_id',b,'fee',20,'sources',jsonb_build_array('platform','walk_in')));
 se:=(drabornstyle_private.api('start',jsonb_build_object('staff_id',s,'service_id',v,'source','walk_in'))->>'id')::uuid;
 perform drabornstyle_private.api('finish',jsonb_build_object('session_id',se,'price',350));
 select id into ledger from drabornstyle.db_style_commission_ledger where session_id=se;
 payment:=(drabornstyle_private.api('payment_submit',jsonb_build_object('business_id',b,'amount',10,'method','cash','paid_at',now(),'key',gen_random_uuid()))->>'id')::uuid;
 perform drabornstyle_private.api('payment_review',jsonb_build_object('id',payment,'status','approved'));
 perform drabornstyle_private.api('commission_adjust',jsonb_build_object('ledger_id',ledger,'amount',-10,'reason','QA düzeltmesi'));
 insert into db_style_workflow_results values('Gerekçeli düzeltme tahakkuk ve borcu günceller',(select balance=0 and accrued=10 and paid=10 from drabornstyle.db_style_business_balances where business_id=b) and (select state='paid' from drabornstyle.db_style_commission_ledger where id=ledger) and (select count(*)=1 from drabornstyle.db_style_commission_adjustments where ledger_id=ledger));
 hit:=false;begin perform drabornstyle_private.api('commission_adjust',jsonb_build_object('ledger_id',ledger,'amount',-1,'reason','Tahsilat altı test'));exception when others then hit:=true;end;
 insert into db_style_workflow_results values('Düzeltme tahsil edilmiş tutarın altına inemez',hit);
 t:=((now() at time zone 'Europe/Istanbul')::date+1+time '12:00') at time zone 'Europe/Istanbul';
 a:=(drabornstyle_private.api('book',jsonb_build_object('staff_id',s,'service_id',v,'starts_at',t+interval '7 days'))->>'id')::uuid;
 hit:=false;begin perform drabornstyle_private.api('repeat_book',jsonb_build_object('staff_id',s,'service_id',v,'starts_at',t,'count',2));exception when exclusion_violation then hit:=true;end;
 insert into db_style_workflow_results values('Tekrarlanan randevu çakışırsa seri bütünüyle geri alınır',hit and not exists(select 1 from drabornstyle.db_style_appointments where staff_id=s and starts_at=t));
 perform drabornstyle_private.api('appointment_change',jsonb_build_object('appointment_id',a,'status','cancelled'));
 j:=drabornstyle_private.api('repeat_book',jsonb_build_object('staff_id',s,'service_id',v,'starts_at',t,'count',2));
 insert into db_style_workflow_results values('Müsait haftalık seri iki randevu oluşturur',jsonb_array_length(j)=2);
 j:=drabornstyle_private.api('qr_create');j:=drabornstyle_private.api('qr_lookup',jsonb_build_object('staff_id',s,'token',j->>'token'));
 insert into db_style_workflow_results values('Süreli QR yetkili ustaya müşteri kaydı verir',j->>'customer_id' is not null);
 update drabornstyle.db_style_profiles set marketing_consent=true where id=u;
 delete from drabornstyle.db_style_notification_preferences where user_id=u;
 perform drabornstyle_private.api('settings',jsonb_build_object('business_id',b,'recall_after_days',30));
 insert into drabornstyle.db_style_customer_loyalty(business_id,customer_id,visits,last_visit) values(b,(j->>'customer_id')::uuid,1,now()-interval '31 days') on conflict(business_id,customer_id) do update set last_visit=excluded.last_visit;
 perform drabornstyle_private.tick();perform drabornstyle_private.tick();
 insert into db_style_workflow_results values('Otomatik geri çağırma izinle ve tek bildirimle çalışır',(select count(*)=1 from drabornstyle.db_style_notifications where business_id=b and user_id=u and kind='recall'));
 delete from drabornstyle.db_style_notifications where business_id=b and user_id=u and kind='recall';
 update drabornstyle.db_style_profiles set marketing_consent=false where id=u;
 perform drabornstyle_private.tick();
 insert into db_style_workflow_results values('Kampanya izni yoksa geri çağırma gönderilmez',not exists(select 1 from drabornstyle.db_style_notifications where business_id=b and user_id=u and kind='recall'));
 update drabornstyle.db_style_admin_users set active=false where user_id=u;
 update drabornstyle.db_style_business_members set role='staff' where business_id=b and user_id=u;
 perform set_config('role','authenticated',true);
 insert into db_style_workflow_results values('Aktif üyeliği olan usta kendi yetkisine erişir',drabornstyle_private.owns_staff(s));
 perform set_config('role','postgres',true);
 update drabornstyle.db_style_business_members set active=false where business_id=b and user_id=u;
 perform set_config('role','authenticated',true);
 hit:=false;begin perform drabornstyle.api('status',jsonb_build_object('staff_id',s,'state','available'));exception when insufficient_privilege then hit:=true;end;
 insert into db_style_workflow_results values('Kapatılan üyelik ustanın işlem yetkisini kaldırır',hit and not drabornstyle_private.owns_staff(s));
 perform set_config('role','postgres',true);
end $$;
select jsonb_agg(jsonb_build_object('test',name,'passed',passed)) as results from db_style_workflow_results;
rollback;
