(function(){
'use strict';
const dkdUrl='https://ztxlcfcwuwerxrhwfmte.supabase.co';
const dkdKey='sb_publishable_GSd5xFBwG9pioOY8N6MRQw_C2n7RLYa';
const dkdClient=window.supabase.createClient(dkdUrl,dkdKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'dkd_anyela_auth_session'}});
let dkdPayments=[];let dkdUsers=[];let dkdExtras=[];let dkdSelectedUserId='';let dkdSelectedUserEmail='';
const dkdById=dkdId=>document.getElementById(dkdId);
const dkdMoney=dkdValue=>new Intl.NumberFormat('tr-TR').format(Number(dkdValue||0))+' TL';
const dkdDate=dkdValue=>dkdValue?new Date(dkdValue).toLocaleString('tr-TR'):'-';
const dkdSafe=dkdValue=>String(dkdValue||'').replace(/[&<>"']/g,dkdChar=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[dkdChar]));
function dkdNote(dkdMessage,dkdBad){const dkdNode=dkdById('dkd_note');if(dkdNode){dkdNode.textContent=dkdMessage;dkdNode.style.color=dkdBad?'#ffb4ea':'#9efffb';}}
function dkdBadge(dkdStatus){const dkdNames={pending:'Bekleyen',approved:'Onaylandı',rejected:'Reddedildi'};return '<span class="dkd_badge dkd_'+dkdSafe(dkdStatus)+'">'+dkdSafe(dkdNames[dkdStatus]||dkdStatus)+'</span>';}
function dkdExtraKindText(dkdKind){const dkdNames={chat_minutes:'Sohbet Dakikası',voice_messages:'Sesli Mesaj',video_messages:'Video Mesaj',photo_count:'Görsel',vip_note:'VIP Not',custom_bonus:'Özel Bonus'};return dkdNames[dkdKind]||dkdKind;}
function dkdIsAdminUser(dkdUser){const dkdRole=String(dkdUser.dkd_role||'').toLowerCase();const dkdEmail=String(dkdUser.dkd_email||'').toLowerCase();return dkdRole==='admin'||dkdRole==='owner'||dkdEmail.includes('admin@')||dkdEmail.includes('anyelaadmin')||dkdEmail.includes('draborneagle');}
function dkdVisibleUsers(){return dkdUsers.filter(dkdUser=>!dkdIsAdminUser(dkdUser)).sort((dkdFirst,dkdSecond)=>String(dkdFirst.dkd_email||'').localeCompare(String(dkdSecond.dkd_email||''),'tr'));}
function dkdRightsFromRow(dkdRow){const dkdPayload=dkdRow.dkd_offer_payload||{};const dkdText=(String(dkdRow.dkd_package_key||'')+' '+String(dkdRow.dkd_package_title||'')).toLowerCase();let dkdMinutes=Number(dkdPayload.dkd_chat_minutes||dkdPayload.dkd_duration_minutes||0);let dkdPhoto=Number(dkdPayload.dkd_photo_count||0);let dkdVoice=Number(dkdPayload.dkd_voice_messages||0);let dkdVideo=Number(dkdPayload.dkd_video_messages||0);if(!dkdMinutes){dkdMinutes=dkdText.includes('aylık')||dkdText.includes('abonelik')||dkdText.includes('monthly')?240:(dkdText.includes('full')?720:(dkdText.includes('vip')?120:(dkdText.includes('ses')||dkdText.includes('voice')?20:(dkdText.includes('mini')?15:30))));}if(!dkdPhoto){dkdPhoto=dkdText.includes('aylık')||dkdText.includes('abonelik')||dkdText.includes('monthly')?3:((dkdText.includes('full')||dkdText.includes('vip'))?5:0);}if(!dkdVoice){dkdVoice=dkdText.includes('aylık')||dkdText.includes('abonelik')||dkdText.includes('monthly')?3:((dkdText.includes('full')||dkdText.includes('ses')||dkdText.includes('voice'))?3:0);}if(!dkdVideo){dkdVideo=dkdText.includes('aylık')||dkdText.includes('abonelik')||dkdText.includes('monthly')||dkdText.includes('full')?1:0;}return{dkdMinutes,dkdPhoto,dkdVoice,dkdVideo};}
function dkdReceiptButton(dkdRow){if(!dkdRow.dkd_receipt_path){return '<span class="dkd_mini">Dekont yok</span>';}return '<button class="dkd_btn dkd_soft" data-receipt="'+dkdSafe(dkdRow.dkd_id)+'">Dekontu Aç</button>';}
function dkdPrettyRow(dkdRow){const dkdRights=dkdRightsFromRow(dkdRow);const dkdPayload=JSON.stringify(dkdRow.dkd_offer_payload||{},null,2);return ['ÖDEME DETAYI','Takip No: '+dkdRow.dkd_id,'Kullanıcı: '+(dkdRow.dkd_email||'-'),'Paket: '+(dkdRow.dkd_package_title||'-'),'Paket Key: '+(dkdRow.dkd_package_key||'-'),'Ödeme Tipi: '+(dkdRow.dkd_payment_kind||'-'),'Tutar: '+dkdMoney(dkdRow.dkd_amount_tl),'Durum: '+(dkdRow.dkd_status||'-'),'Dekont Dosyası: '+(dkdRow.dkd_receipt_file_name||'-'),'Dekont Tipi: '+(dkdRow.dkd_receipt_mime_type||'-'),'Dekont Boyutu: '+String(Math.round(Number(dkdRow.dkd_receipt_size_bytes||0)/1024))+' KB','Haklar: '+dkdRights.dkdMinutes+' dk, '+dkdRights.dkdPhoto+' fotoğraf, '+dkdRights.dkdVoice+' ses, '+dkdRights.dkdVideo+' video','Admin Notu: '+(dkdRow.dkd_admin_note||'-'),'Onay Tarihi: '+dkdDate(dkdRow.dkd_approved_at),'Red Tarihi: '+dkdDate(dkdRow.dkd_rejected_at),'Kayıt Tarihi: '+dkdDate(dkdRow.dkd_created_at),'','Özel Teklif/Payload:',dkdPayload].join('\n');}
async function dkdCheckAdmin(){const dkdSession=await dkdClient.auth.getSession();if(!dkdSession.data.session){if(dkdById('dkd_login_box')){dkdById('dkd_login_box').style.display='flex';}dkdNote('Admin hesabınla giriş yapmalısın.',true);return false;}const dkdAdminResult=await dkdClient.rpc('dkd_anyela_is_admin');if(dkdAdminResult.error||!dkdAdminResult.data){if(dkdById('dkd_login_box')){dkdById('dkd_login_box').style.display='none';}dkdNote('Bu hesap admin değil. Supabase profil rolünü admin yapmalısın.',true);return false;}if(dkdById('dkd_login_box')){dkdById('dkd_login_box').style.display='none';}dkdNote('Admin yetkisi doğrulandı. Canlı veriler yüklendi.',false);return true;}
async function dkdLoadData(){const dkdOk=await dkdCheckAdmin();if(!dkdOk){return;}const dkdPay=await dkdClient.from('dkd_anyela_admin_payment_summary').select('*').order('dkd_created_at',{ascending:false});const dkdUserResult=await dkdClient.from('dkd_anyela_profiles').select('*').order('dkd_created_at',{ascending:false});const dkdExtraResult=await dkdClient.from('dkd_anyela_admin_user_extra_summary').select('*').order('dkd_created_at',{ascending:false});if(dkdPay.error){dkdNote('Ödemeler alınamadı: '+dkdPay.error.message,true);return;}if(dkdUserResult.error){dkdNote('Kullanıcılar alınamadı: '+dkdUserResult.error.message,true);return;}if(dkdExtraResult.error){dkdNote('Ek haklar alınamadı: '+dkdExtraResult.error.message,true);return;}dkdPayments=dkdPay.data||[];dkdUsers=dkdUserResult.data||[];dkdExtras=dkdExtraResult.data||[];dkdRender();}
function dkdFilteredRows(){const dkdQuery=dkdById('dkd_search').value.toLowerCase().trim();const dkdStatus=dkdById('dkd_status').value;const dkdKind=dkdById('dkd_kind').value;return dkdPayments.filter(dkdRow=>{const dkdHay=[dkdRow.dkd_id,dkdRow.dkd_email,dkdRow.dkd_package_title,dkdRow.dkd_status,dkdRow.dkd_package_key,dkdRow.dkd_receipt_file_name,JSON.stringify(dkdRow.dkd_offer_payload||{})].join(' ').toLowerCase();return(!dkdQuery||dkdHay.includes(dkdQuery))&&(dkdStatus==='all'||dkdRow.dkd_status===dkdStatus)&&(dkdKind==='all'||dkdRow.dkd_payment_kind===dkdKind);});}
async function dkdOpenReceiptByRow(dkdRow){if(!dkdRow||!dkdRow.dkd_receipt_path){alert('Dekont yolu yok.');return;}if(String(dkdRow.dkd_receipt_path).startsWith('data:')){const dkdWindow=window.open('','_blank');if(dkdWindow){dkdWindow.document.write('<iframe src="'+dkdRow.dkd_receipt_path+'" style="border:0;width:100vw;height:100vh"></iframe>');}return;}const dkdResult=await dkdClient.storage.from(dkdRow.dkd_receipt_bucket||'dkd-anyela-receipts').createSignedUrl(dkdRow.dkd_receipt_path,600);if(dkdResult.error){alert('Dekont açılamadı: '+dkdResult.error.message);return;}window.open(dkdResult.data.signedUrl,'_blank');}
async function dkdMarkPayment(dkdId,dkdStatus){const dkdAdminNote=prompt(dkdStatus==='approved'?'Onay notu':'Red notu','Admin panel');const dkdResult=await dkdClient.rpc('dkd_anyela_mark_payment',{dkd_payment_id:dkdId,dkd_next_status:dkdStatus,dkd_note:dkdAdminNote||''});if(dkdResult.error){alert('İşlem başarısız: '+dkdResult.error.message);return;}alert(dkdStatus==='approved'?'Ödeme onaylandı. Kullanıcının paketi ve hakları mevcut haklarının üstüne eklenerek Sohbet Odası’nda aktif görünecek.':'Ödeme reddedildi.');await dkdLoadData();}
async function dkdDeletePayment(dkdId){const dkdRow=dkdPayments.find(dkdPayment=>dkdPayment.dkd_id===dkdId);const dkdOk=confirm('Bu ödeme/dekont talebi veritabanından silinsin mi?\n\n'+(dkdRow?String(dkdRow.dkd_package_title||'')+' • '+String(dkdRow.dkd_email||''):''));if(!dkdOk){return;}const dkdResult=await dkdClient.rpc('dkd_anyela_admin_delete_payment',{dkd_payment_id:dkdId});if(dkdResult.error){alert('Silinemedi: '+dkdResult.error.message);return;}dkdNote('Ödeme/dekont talebi silindi.',false);await dkdLoadData();}
async function dkdAddUserExtra(){if(!dkdSelectedUserId){alert('Önce kullanıcı listesinden kullanıcı seç.');return;}const dkdKind=dkdById('dkd_extra_kind').value;const dkdAmount=Number(dkdById('dkd_extra_amount').value||0);const dkdTitle=dkdById('dkd_extra_title').value.trim()||'Admin bonusu';const dkdExtraNote=dkdById('dkd_extra_note').value.trim();const dkdResult=await dkdClient.rpc('dkd_anyela_admin_add_user_extra',{dkd_target_user_id:dkdSelectedUserId,dkd_extra_kind_value:dkdKind,dkd_extra_amount_value:dkdAmount,dkd_extra_title_value:dkdTitle,dkd_extra_note_value:dkdExtraNote});if(dkdResult.error){alert('Ek hak eklenemedi: '+dkdResult.error.message);return;}dkdNote(dkdSelectedUserEmail+' kullanıcısına ek hak eklendi. Sohbet Odası hak paneline yansıyacak.',false);await dkdLoadData();}
function dkdSelectUser(dkdId){const dkdUser=dkdUsers.find(dkdItem=>dkdItem.dkd_id===dkdId);dkdSelectedUserId=dkdId;dkdSelectedUserEmail=dkdUser&&dkdUser.dkd_email?dkdUser.dkd_email:'Seçili kullanıcı';dkdById('dkd_selected_user_box').textContent=dkdSelectedUserEmail+' seçildi. Ek dakika, sesli mesaj, video mesaj, görsel veya özel bonus ekleyebilirsin.';dkdRenderUsers();dkdRenderExtras();}
function dkdShowDetail(dkdId){const dkdRow=dkdPayments.find(dkdPayment=>dkdPayment.dkd_id===dkdId);dkdById('dkd_detail_box').textContent=dkdRow?dkdPrettyRow(dkdRow):'Kayıt bulunamadı.';}
function dkdRenderExtras(){const dkdRows=dkdSelectedUserId?dkdExtras.filter(dkdExtra=>dkdExtra.dkd_user_id===dkdSelectedUserId):dkdExtras.slice(0,20);dkdById('dkd_extras_body').innerHTML=dkdRows.map(dkdExtra=>'<div class="dkd_user"><strong>'+dkdSafe(dkdExtraKindText(dkdExtra.dkd_extra_kind))+' +'+String(dkdExtra.dkd_extra_amount)+'</strong><small>'+dkdSafe(dkdExtra.dkd_email||'-')+' • '+dkdSafe(dkdExtra.dkd_extra_title||'-')+' • '+dkdSafe(dkdDate(dkdExtra.dkd_created_at))+'</small><small>'+dkdSafe(dkdExtra.dkd_extra_note||'')+'</small></div>').join('')||'Ek hak kaydı yok.';}
function dkdRenderUsers(){const dkdUserList=dkdVisibleUsers();dkdById('dkd_users_body').innerHTML=dkdUserList.map((dkdUser,dkdIndex)=>'<button type="button" class="dkd_user dkd_user_selectable '+(dkdUser.dkd_id===dkdSelectedUserId?'dkd_user_selected':'')+'" data-user="'+dkdSafe(dkdUser.dkd_id)+'"><strong>'+String(dkdIndex+1)+'. '+dkdSafe(dkdUser.dkd_email||'-')+'</strong><small>'+dkdSafe(dkdUser.dkd_role||'member')+' • '+dkdSafe(dkdDate(dkdUser.dkd_created_at))+'</small></button>').join('')||'Kullanıcı yok.';document.querySelectorAll('[data-user]').forEach(dkdButton=>dkdButton.onclick=()=>dkdSelectUser(dkdButton.getAttribute('data-user')));}
function dkdPaymentRow(dkdRow){const dkdRights=dkdRightsFromRow(dkdRow);return '<tr><td>'+dkdSafe(dkdDate(dkdRow.dkd_created_at))+'<br><span class="dkd_mini">'+dkdSafe(dkdRow.dkd_id)+'</span></td><td><b>'+dkdSafe(dkdRow.dkd_email||'-')+'</b><br><span class="dkd_mini">'+dkdSafe(dkdRow.dkd_display_name||'-')+' / '+dkdSafe(dkdRow.dkd_role||'-')+'</span></td><td><b>'+dkdSafe(dkdRow.dkd_package_title||'-')+'</b><br><span class="dkd_mini">'+dkdSafe(dkdRow.dkd_payment_kind||'-')+' / '+dkdSafe(dkdRow.dkd_package_key||'-')+'</span><br><span class="dkd_mini">Hak: '+dkdRights.dkdMinutes+' dk • '+dkdRights.dkdPhoto+' foto • '+dkdRights.dkdVoice+' ses • '+dkdRights.dkdVideo+' video</span></td><td>'+dkdSafe(dkdMoney(dkdRow.dkd_amount_tl))+'</td><td>'+dkdBadge(dkdRow.dkd_status)+'</td><td>'+dkdReceiptButton(dkdRow)+'</td><td><button class="dkd_btn" data-detail="'+dkdSafe(dkdRow.dkd_id)+'">Detay</button> <button class="dkd_btn" data-approve="'+dkdSafe(dkdRow.dkd_id)+'">Onayla</button> <button class="dkd_btn dkd_danger" data-reject="'+dkdSafe(dkdRow.dkd_id)+'">Reddet</button> <button class="dkd_btn dkd_danger" data-delete="'+dkdSafe(dkdRow.dkd_id)+'">Sil</button></td></tr>';}
function dkdRender(){const dkdRows=dkdFilteredRows();const dkdUserList=dkdVisibleUsers();dkdById('dkd_stat_total').textContent=dkdPayments.length;dkdById('dkd_stat_pending').textContent=dkdPayments.filter(dkdPayment=>dkdPayment.dkd_status==='pending').length;dkdById('dkd_stat_approved').textContent=dkdMoney(dkdPayments.filter(dkdPayment=>dkdPayment.dkd_status==='approved').reduce((dkdSum,dkdPayment)=>dkdSum+Number(dkdPayment.dkd_amount_tl||0),0));dkdById('dkd_stat_users').textContent=dkdUserList.length;dkdById('dkd_payments_body').innerHTML=dkdRows.map(dkdPaymentRow).join('')||'<tr><td colspan="7">Ödeme kaydı yok.</td></tr>';dkdRenderUsers();document.querySelectorAll('[data-receipt]').forEach(dkdButton=>dkdButton.onclick=()=>{const dkdRow=dkdPayments.find(dkdPayment=>dkdPayment.dkd_id===dkdButton.getAttribute('data-receipt'));dkdOpenReceiptByRow(dkdRow);});document.querySelectorAll('[data-detail]').forEach(dkdButton=>dkdButton.onclick=()=>dkdShowDetail(dkdButton.getAttribute('data-detail')));document.querySelectorAll('[data-approve]').forEach(dkdButton=>dkdButton.onclick=()=>dkdMarkPayment(dkdButton.getAttribute('data-approve'),'approved'));document.querySelectorAll('[data-reject]').forEach(dkdButton=>dkdButton.onclick=()=>dkdMarkPayment(dkdButton.getAttribute('data-reject'),'rejected'));document.querySelectorAll('[data-delete]').forEach(dkdButton=>dkdButton.onclick=()=>dkdDeletePayment(dkdButton.getAttribute('data-delete')));dkdRenderExtras();}
function dkdBindEvents(){dkdById('dkd_admin_login').onclick=async()=>{const dkdEmail=dkdById('dkd_admin_email').value.trim();const dkdPassword=dkdById('dkd_admin_password').value;const dkdResult=await dkdClient.auth.signInWithPassword({email:dkdEmail,password:dkdPassword});if(dkdResult.error){dkdNote('Giriş başarısız: '+dkdResult.error.message,true);return;}await dkdLoadData();};dkdById('dkd_logout').onclick=async()=>{await dkdClient.auth.signOut();location.reload();};dkdById('dkd_refresh').onclick=dkdLoadData;dkdById('dkd_search').oninput=dkdRender;dkdById('dkd_status').onchange=dkdRender;dkdById('dkd_kind').onchange=dkdRender;dkdById('dkd_add_extra').onclick=dkdAddUserExtra;}
const dkdStyle=document.createElement('style');dkdStyle.textContent='.dkd_user_selectable{width:100%;text-align:left;border:1px solid rgba(255,255,255,.13);cursor:pointer}.dkd_user_selected{border-color:#18f7ff!important;box-shadow:0 0 20px rgba(24,247,255,.24)!important;background:linear-gradient(135deg,rgba(24,247,255,.14),rgba(255,43,214,.14))!important}';document.head.appendChild(dkdStyle);
dkdBindEvents();dkdLoadData();
})();
