(function(){
'use strict';
const dkdUrl='https://ztxlcfcwuwerxrhwfmte.supabase.co';
const dkdKey='sb_publishable_GSd5xFBwG9pioOY8N6MRQw_C2n7RLYa';
const dkdClient=window.supabase.createClient(dkdUrl,dkdKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'dkd_anyela_auth_session'}});
let dkdPayments=[];
let dkdUsers=[];
let dkdExtras=[];
let dkdLiveMessages=[];
let dkdSelectedUserId='';
let dkdSelectedUserEmail='';
let dkdLiveChannel=null;
const dkdById=(dkd_id)=>document.getElementById(dkd_id);
const dkdMoney=(dkd_value)=>new Intl.NumberFormat('tr-TR').format(Number(dkd_value||0))+' TL';
const dkdDate=(dkd_value)=>dkd_value?new Date(dkd_value).toLocaleString('tr-TR'):'-';
const dkdEscape=(dkd_value)=>String(dkd_value||'').replace(/[&<>\"']/g,(dkd_char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[dkd_char]));
function dkdNote(dkd_message,dkd_bad){const dkd_box=dkdById('dkd_note');dkd_box.textContent=dkd_message;dkd_box.style.color=dkd_bad?'#ffb4ea':'#9efffb'}
function dkdBadge(dkd_status){const dkd_names={pending:'Bekleyen',approved:'Onaylandı',rejected:'Reddedildi'};return '<span class="dkd_badge dkd_'+dkd_status+'">'+(dkd_names[dkd_status]||dkd_status)+'</span>'}
function dkdExtraKindText(dkd_kind){const dkd_names={chat_minutes:'Sohbet Dakikası',voice_messages:'Sesli Mesaj',video_messages:'Video Mesaj',photo_count:'Görsel',vip_note:'VIP Not',custom_bonus:'Özel Bonus'};return dkd_names[dkd_kind]||dkd_kind}
async function dkdCheckAdmin(){const dkd_session_result=await dkdClient.auth.getSession();const dkd_session=dkd_session_result.data&&dkd_session_result.data.session;if(!dkd_session){dkdById('dkd_login_box').style.display='flex';dkdNote('Admin hesabınla giriş yapmalısın.',true);return false}const dkd_admin_result=await dkdClient.rpc('dkd_anyela_is_admin');if(dkd_admin_result.error||!dkd_admin_result.data){dkdById('dkd_login_box').style.display='none';dkdNote('Bu hesap admin değil. Supabase profil rolünü admin yapmalısın.',true);return false}dkdById('dkd_login_box').style.display='none';dkdNote('Admin yetkisi doğrulandı. Canlı veriler yüklendi.',false);return true}
async function dkdLoadData(){const dkd_is_admin=await dkdCheckAdmin();if(!dkd_is_admin){return}const dkd_payments_result=await dkdClient.from('dkd_anyela_admin_payment_summary').select('*').order('dkd_created_at',{ascending:false});const dkd_users_result=await dkdClient.from('dkd_anyela_profiles').select('*').order('dkd_created_at',{ascending:false});const dkd_extras_result=await dkdClient.from('dkd_anyela_admin_user_extra_summary').select('*').order('dkd_created_at',{ascending:false});if(dkd_payments_result.error){dkdNote('Ödemeler alınamadı: '+dkd_payments_result.error.message,true);return}if(dkd_users_result.error){dkdNote('Kullanıcılar alınamadı: '+dkd_users_result.error.message,true);return}if(dkd_extras_result.error){dkdNote('Ek haklar alınamadı: '+dkd_extras_result.error.message,true);return}dkdPayments=dkd_payments_result.data||[];dkdUsers=dkd_users_result.data||[];dkdExtras=dkd_extras_result.data||[];dkdRender()}
function dkdFilteredRows(){const dkd_query=dkdById('dkd_search').value.toLowerCase().trim();const dkd_status=dkdById('dkd_status').value;const dkd_kind=dkdById('dkd_kind').value;return dkdPayments.filter((dkd_row)=>{const dkd_hay=[dkd_row.dkd_id,dkd_row.dkd_email,dkd_row.dkd_package_title,dkd_row.dkd_status,dkd_row.dkd_package_key].join(' ').toLowerCase();return(!dkd_query||dkd_hay.includes(dkd_query))&&(dkd_status==='all'||dkd_row.dkd_status===dkd_status)&&(dkd_kind==='all'||dkd_row.dkd_payment_kind===dkd_kind)})}
async function dkdOpenReceipt(dkd_path){if(!dkd_path){alert('Dekont yolu yok.');return}const dkd_result=await dkdClient.storage.from('dkd-anyela-receipts').createSignedUrl(dkd_path,600);if(dkd_result.error){alert('Dekont açılamadı: '+dkd_result.error.message);return}window.open(dkd_result.data.signedUrl,'_blank')}
async function dkdMarkPayment(dkd_id,dkd_status){const dkd_note=prompt(dkd_status==='approved'?'Onay notu':'Red notu','Admin panel');const dkd_result=await dkdClient.rpc('dkd_anyela_mark_payment',{dkd_payment_id:dkd_id,dkd_next_status:dkd_status,dkd_note:dkd_note||''});if(dkd_result.error){alert('İşlem başarısız: '+dkd_result.error.message);return}await dkdLoadData()}
async function dkdAddUserExtra(){if(!dkdSelectedUserId){alert('Önce kullanıcı listesinden kullanıcı seç.');return}const dkd_kind=dkdById('dkd_extra_kind').value;const dkd_amount=Number(dkdById('dkd_extra_amount').value||0);const dkd_title=dkdById('dkd_extra_title').value.trim()||'Admin bonusu';const dkd_note=dkdById('dkd_extra_note').value.trim();const dkd_result=await dkdClient.rpc('dkd_anyela_admin_add_user_extra',{dkd_target_user_id:dkdSelectedUserId,dkd_extra_kind_value:dkd_kind,dkd_extra_amount_value:dkd_amount,dkd_extra_title_value:dkd_title,dkd_extra_note_value:dkd_note});if(dkd_result.error){alert('Ek hak eklenemedi: '+dkd_result.error.message);return}dkdNote(dkdSelectedUserEmail+' kullanıcısına ek hak eklendi.',false);await dkdLoadData()}
async function dkdSelectUser(dkd_user_id){const dkd_user=dkdUsers.find((dkd_item)=>dkd_item.dkd_id===dkd_user_id);dkdSelectedUserId=dkd_user_id;dkdSelectedUserEmail=dkd_user&&dkd_user.dkd_email?dkd_user.dkd_email:'Seçili kullanıcı';dkdById('dkd_selected_user_box').textContent=dkdSelectedUserEmail+' seçildi. Ek dakika, sesli mesaj, video mesaj, görsel veya özel bonus ekleyebilirsin.';dkdById('dkd_live_chat_user_box').textContent=dkdSelectedUserEmail+' ile Canlı Sohbet açık.';dkdRenderExtras();await dkdLoadLiveChat();dkdStartLiveChatRealtime()}
function dkdShowDetail(dkd_id){const dkd_row=dkdPayments.find((dkd_item)=>dkd_item.dkd_id===dkd_id);dkdById('dkd_detail_box').textContent=dkd_row?JSON.stringify(dkd_row,null,2):'Kayıt bulunamadı.'}
function dkdRenderExtras(){const dkd_rows=dkdSelectedUserId?dkdExtras.filter((dkd_item)=>dkd_item.dkd_user_id===dkdSelectedUserId):dkdExtras.slice(0,20);dkdById('dkd_extras_body').innerHTML=dkd_rows.map((dkd_extra)=>'<div class="dkd_user"><strong>'+dkdExtraKindText(dkd_extra.dkd_extra_kind)+' +'+String(dkd_extra.dkd_extra_amount)+'</strong><small>'+String(dkd_extra.dkd_email||'-')+' • '+String(dkd_extra.dkd_extra_title||'-')+' • '+dkdDate(dkd_extra.dkd_created_at)+'</small><small>'+String(dkd_extra.dkd_extra_note||'')+'</small></div>').join('')||'Ek hak kaydı yok.'}
function dkdRenderLiveChat(){const dkd_body=dkdById('dkd_live_chat_body');if(!dkd_body){return}if(!dkdSelectedUserId){dkd_body.textContent='Canlı mesaj kaydı bekleniyor...';return}if(!dkdLiveMessages.length){dkd_body.innerHTML='<div class="dkd_live_empty">Henüz mesaj yok. İlk admin mesajını buradan gönderebilirsin.</div>';return}dkd_body.innerHTML=dkdLiveMessages.map((dkd_message)=>{const dkd_is_admin=dkd_message.dkd_sender_role==='admin'||dkd_message.dkd_sender_role==='anyela';const dkd_class=dkd_is_admin?'dkd_live_msg_admin':'dkd_live_msg_user';const dkd_name=dkd_is_admin?'Anyela Admin':(dkd_message.dkd_sender_name||dkdSelectedUserEmail||'Üye');return '<div class="dkd_live_msg '+dkd_class+'"><strong>'+dkdEscape(dkd_name)+'</strong><span>'+dkdEscape(dkd_message.dkd_message_body)+'</span><small>'+dkdEscape(dkdDate(dkd_message.dkd_created_at))+'</small></div>'}).join('');dkd_body.scrollTop=dkd_body.scrollHeight}
async function dkdLoadLiveChat(){if(!dkdSelectedUserId){dkdRenderLiveChat();return}const dkd_result=await dkdClient.from('dkd_anyela_chat_messages').select('dkd_id,dkd_user_id,dkd_sender_role,dkd_sender_name,dkd_message_body,dkd_created_at').eq('dkd_user_id',dkdSelectedUserId).order('dkd_created_at',{ascending:true}).limit(100);if(dkd_result.error){dkdById('dkd_live_chat_body').innerHTML='<div class="dkd_live_empty">Canlı sohbet alınamadı: '+dkdEscape(dkd_result.error.message)+'</div>';return}dkdLiveMessages=dkd_result.data||[];dkdRenderLiveChat()}
function dkdStartLiveChatRealtime(){if(dkdLiveChannel){dkdClient.removeChannel(dkdLiveChannel);dkdLiveChannel=null}if(!dkdSelectedUserId){return}dkdLiveChannel=dkdClient.channel('dkd_anyela_admin_live_chat_'+dkdSelectedUserId).on('postgres_changes',{event:'INSERT',schema:'public',table:'dkd_anyela_chat_messages',filter:'dkd_user_id=eq.'+dkdSelectedUserId},(dkd_payload)=>{const dkd_new_message=dkd_payload&&dkd_payload.new?dkd_payload.new:null;if(!dkd_new_message){return}if(dkdLiveMessages.some((dkd_message)=>dkd_message.dkd_id===dkd_new_message.dkd_id)){return}dkdLiveMessages.push(dkd_new_message);dkdRenderLiveChat()}).subscribe()}
async function dkdSendLiveChat(){if(!dkdSelectedUserId){alert('Önce kullanıcı seç.');return}const dkd_input=dkdById('dkd_live_chat_message');const dkd_text=dkd_input&&dkd_input.value?dkd_input.value.trim():'';if(!dkd_text){return}const dkd_button=dkdById('dkd_send_live_chat');dkd_button.disabled=true;const dkd_result=await dkdClient.rpc('dkd_anyela_admin_insert_chat_message',{dkd_target_user_id:dkdSelectedUserId,dkd_message_text:dkd_text});dkd_button.disabled=false;if(dkd_result.error){alert('Mesaj gönderilemedi: '+dkd_result.error.message);return}dkd_input.value='';await dkdLoadLiveChat()}
function dkdRender(){const dkd_rows=dkdFilteredRows();dkdById('dkd_stat_total').textContent=dkdPayments.length;dkdById('dkd_stat_pending').textContent=dkdPayments.filter((dkd_item)=>dkd_item.dkd_status==='pending').length;dkdById('dkd_stat_approved').textContent=dkdMoney(dkdPayments.filter((dkd_item)=>dkd_item.dkd_status==='approved').reduce((dkd_sum,dkd_item)=>dkd_sum+Number(dkd_item.dkd_amount_tl||0),0));dkdById('dkd_stat_users').textContent=dkdUsers.length;dkdById('dkd_payments_body').innerHTML=dkd_rows.map((dkd_row)=>{const dkd_offer=dkd_row.dkd_offer_payload&&Object.keys(dkd_row.dkd_offer_payload).length?'<br><span class="dkd_mini">Teklif: '+JSON.stringify(dkd_row.dkd_offer_payload)+'</span>':'';return '<tr><td>'+dkdDate(dkd_row.dkd_created_at)+'<br><span class="dkd_mini">'+dkd_row.dkd_id+'</span></td><td><b>'+String(dkd_row.dkd_email||'-')+'</b><br><span class="dkd_mini">'+String(dkd_row.dkd_display_name||'-')+' / '+String(dkd_row.dkd_role||'-')+'</span></td><td><b>'+String(dkd_row.dkd_package_title||'-')+'</b><br><span class="dkd_mini">'+String(dkd_row.dkd_payment_kind||'-')+' / '+String(dkd_row.dkd_package_key||'-')+'</span>'+dkd_offer+'</td><td>'+dkdMoney(dkd_row.dkd_amount_tl)+'</td><td>'+dkdBadge(dkd_row.dkd_status)+'</td><td><button class="dkd_btn dkd_soft" data-receipt="'+String(dkd_row.dkd_receipt_path||'')+'">Dekont</button></td><td><button class="dkd_btn" data-detail="'+dkd_row.dkd_id+'">Detay</button> <button class="dkd_btn" data-approve="'+dkd_row.dkd_id+'">Onayla</button> <button class="dkd_btn dkd_danger" data-reject="'+dkd_row.dkd_id+'">Reddet</button></td></tr>'}).join('')||'<tr><td colspan="7">Ödeme kaydı yok.</td></tr>';dkdById('dkd_users_body').innerHTML=dkdUsers.map((dkd_user)=>'<div class="dkd_user" data-user="'+dkd_user.dkd_id+'"><strong>'+String(dkd_user.dkd_email||'-')+'</strong><small>'+String(dkd_user.dkd_role||'-')+' • '+dkdDate(dkd_user.dkd_created_at)+'</small></div>').join('')||'Kullanıcı yok.';document.querySelectorAll('[data-user]').forEach((dkd_button)=>{dkd_button.onclick=()=>dkdSelectUser(dkd_button.getAttribute('data-user'))});document.querySelectorAll('[data-receipt]').forEach((dkd_button)=>{dkd_button.onclick=()=>dkdOpenReceipt(dkd_button.getAttribute('data-receipt'))});document.querySelectorAll('[data-detail]').forEach((dkd_button)=>{dkd_button.onclick=()=>dkdShowDetail(dkd_button.getAttribute('data-detail'))});document.querySelectorAll('[data-approve]').forEach((dkd_button)=>{dkd_button.onclick=()=>dkdMarkPayment(dkd_button.getAttribute('data-approve'),'approved')});document.querySelectorAll('[data-reject]').forEach((dkd_button)=>{dkd_button.onclick=()=>dkdMarkPayment(dkd_button.getAttribute('data-reject'),'rejected')});dkdRenderExtras();dkdRenderLiveChat()}
dkdById('dkd_admin_login').onclick=async()=>{const dkd_email=dkdById('dkd_admin_email').value.trim();const dkd_password=dkdById('dkd_admin_password').value;const dkd_result=await dkdClient.auth.signInWithPassword({email:dkd_email,password:dkd_password});if(dkd_result.error){dkdNote('Giriş başarısız: '+dkd_result.error.message,true);return}await dkdLoadData()};
dkdById('dkd_logout').onclick=async()=>{await dkdClient.auth.signOut();location.reload()};
dkdById('dkd_refresh').onclick=dkdLoadData;dkdById('dkd_search').oninput=dkdRender;dkdById('dkd_status').onchange=dkdRender;dkdById('dkd_kind').onchange=dkdRender;dkdById('dkd_add_extra').onclick=dkdAddUserExtra;dkdById('dkd_send_live_chat').onclick=dkdSendLiveChat;dkdById('dkd_live_chat_message').addEventListener('keydown',(dkd_event)=>{if(dkd_event.key==='Enter'&&!dkd_event.shiftKey){dkd_event.preventDefault();dkdSendLiveChat()}});window.addEventListener('beforeunload',()=>{if(dkdLiveChannel){dkdClient.removeChannel(dkdLiveChannel)}});dkdLoadData();
})();