(function(){
'use strict';
const dkdUrl='https://ztxlcfcwuwerxrhwfmte.supabase.co';
const dkdKey='sb_publishable_GSd5xFBwG9pioOY8N6MRQw_C2n7RLYa';
const dkdClient=window.supabase.createClient(dkdUrl,dkdKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'dkd_anyela_auth_session'}});
let dkdPayments=[];let dkdUsers=[];let dkdExtras=[];let dkdLiveMessages=[];let dkdSelectedUserId='';let dkdSelectedUserEmail='';let dkdLiveChannel=null;
const dkdById=id=>document.getElementById(id);const dkdMoney=v=>new Intl.NumberFormat('tr-TR').format(Number(v||0))+' TL';const dkdDate=v=>v?new Date(v).toLocaleString('tr-TR'):'-';const dkdEscape=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function dkdNote(m,b){const n=dkdById('dkd_note');if(n){n.textContent=m;n.style.color=b?'#ffb4ea':'#9efffb'}}function dkdBadge(s){const names={pending:'Bekleyen',approved:'Onaylandı',rejected:'Reddedildi'};return '<span class="dkd_badge dkd_'+s+'">'+(names[s]||s)+'</span>'}function dkdExtraKindText(k){const names={chat_minutes:'Sohbet Dakikası',voice_messages:'Sesli Mesaj',video_messages:'Video Mesaj',photo_count:'Görsel',vip_note:'VIP Not',custom_bonus:'Özel Bonus'};return names[k]||k}
function dkdRightsFromRow(row){const p=row.dkd_offer_payload||{};const text=(String(row.dkd_package_key||'')+' '+String(row.dkd_package_title||'')).toLowerCase();let minutes=Number(p.dkd_chat_minutes||p.dkd_duration_minutes||0);let photo=Number(p.dkd_photo_count||0);let voice=Number(p.dkd_voice_messages||0);let video=Number(p.dkd_video_messages||0);if(!minutes){minutes=text.includes('full')?1440:(text.includes('vip')?720:(text.includes('ses')||text.includes('voice')?20:(text.includes('mini')?15:30)))}if(!photo){photo=(text.includes('full')||text.includes('vip'))?5:0}if(!voice){voice=(text.includes('full')||text.includes('ses')||text.includes('voice'))?3:0}if(!video){video=text.includes('full')?1:0}return{minutes,photo,voice,video}}
function dkdReceiptButton(row){if(!row.dkd_receipt_path){return '<span class="dkd_mini">Dekont yok</span>'}return '<button class="dkd_btn dkd_soft" data-receipt="'+String(row.dkd_id)+'">Dekontu Aç</button>'}
function dkdPrettyRow(row){const rights=dkdRightsFromRow(row);const payload=JSON.stringify(row.dkd_offer_payload||{},null,2);return ['ÖDEME DETAYI','Takip No: '+row.dkd_id,'Kullanıcı: '+(row.dkd_email||'-'),'Paket: '+(row.dkd_package_title||'-'),'Paket Key: '+(row.dkd_package_key||'-'),'Ödeme Tipi: '+(row.dkd_payment_kind||'-'),'Tutar: '+dkdMoney(row.dkd_amount_tl),'Durum: '+(row.dkd_status||'-'),'Dekont Dosyası: '+(row.dkd_receipt_file_name||'-'),'Dekont Tipi: '+(row.dkd_receipt_mime_type||'-'),'Dekont Boyutu: '+String(Math.round(Number(row.dkd_receipt_size_bytes||0)/1024))+' KB','Haklar: '+rights.minutes+' dk, '+rights.photo+' fotoğraf, '+rights.voice+' ses, '+rights.video+' video','Admin Notu: '+(row.dkd_admin_note||'-'),'Onay Tarihi: '+dkdDate(row.dkd_approved_at),'Red Tarihi: '+dkdDate(row.dkd_rejected_at),'Kayıt Tarihi: '+dkdDate(row.dkd_created_at),'','Özel Teklif/Payload:',payload].join('\n')}
async function dkdCheckAdmin(){const s=await dkdClient.auth.getSession();if(!s.data.session){dkdById('dkd_login_box').style.display='flex';dkdNote('Admin hesabınla giriş yapmalısın.',true);return false}const a=await dkdClient.rpc('dkd_anyela_is_admin');if(a.error||!a.data){dkdById('dkd_login_box').style.display='none';dkdNote('Bu hesap admin değil. Supabase profil rolünü admin yapmalısın.',true);return false}dkdById('dkd_login_box').style.display='none';dkdNote('Admin yetkisi doğrulandı. Canlı veriler yüklendi.',false);return true}
async function dkdLoadData(){const ok=await dkdCheckAdmin();if(!ok){return}const pay=await dkdClient.from('dkd_anyela_admin_payment_summary').select('*').order('dkd_created_at',{ascending:false});const users=await dkdClient.from('dkd_anyela_profiles').select('*').order('dkd_created_at',{ascending:false});const extras=await dkdClient.from('dkd_anyela_admin_user_extra_summary').select('*').order('dkd_created_at',{ascending:false});if(pay.error){dkdNote('Ödemeler alınamadı: '+pay.error.message,true);return}if(users.error){dkdNote('Kullanıcılar alınamadı: '+users.error.message,true);return}if(extras.error){dkdNote('Ek haklar alınamadı: '+extras.error.message,true);return}dkdPayments=pay.data||[];dkdUsers=users.data||[];dkdExtras=extras.data||[];dkdRender()}
function dkdFilteredRows(){const q=dkdById('dkd_search').value.toLowerCase().trim();const st=dkdById('dkd_status').value;const kind=dkdById('dkd_kind').value;return dkdPayments.filter(r=>{const hay=[r.dkd_id,r.dkd_email,r.dkd_package_title,r.dkd_status,r.dkd_package_key,r.dkd_receipt_file_name,JSON.stringify(r.dkd_offer_payload||{})].join(' ').toLowerCase();return(!q||hay.includes(q))&&(st==='all'||r.dkd_status===st)&&(kind==='all'||r.dkd_payment_kind===kind)})}
async function dkdOpenReceiptByRow(row){if(!row||!row.dkd_receipt_path){alert('Dekont yolu yok.');return}if(String(row.dkd_receipt_path).startsWith('data:')){const win=window.open('','_blank');if(win){win.document.write('<iframe src="'+row.dkd_receipt_path+'" style="border:0;width:100vw;height:100vh"></iframe>')}return}const result=await dkdClient.storage.from(row.dkd_receipt_bucket||'dkd-anyela-receipts').createSignedUrl(row.dkd_receipt_path,600);if(result.error){alert('Dekont açılamadı: '+result.error.message);return}window.open(result.data.signedUrl,'_blank')}
async function dkdMarkPayment(id,status){const note=prompt(status==='approved'?'Onay notu':'Red notu','Admin panel');const result=await dkdClient.rpc('dkd_anyela_mark_payment',{dkd_payment_id:id,dkd_next_status:status,dkd_note:note||''});if(result.error){alert('İşlem başarısız: '+result.error.message);return}alert(status==='approved'?'Ödeme onaylandı. Kullanıcının paketi ve hakları Sohbet Odası’nda aktif görünecek.':'Ödeme reddedildi.');await dkdLoadData()}
async function dkdAddUserExtra(){if(!dkdSelectedUserId){alert('Önce kullanıcı listesinden kullanıcı seç.');return}const kind=dkdById('dkd_extra_kind').value;const amount=Number(dkdById('dkd_extra_amount').value||0);const title=dkdById('dkd_extra_title').value.trim()||'Admin bonusu';const note=dkdById('dkd_extra_note').value.trim();const result=await dkdClient.rpc('dkd_anyela_admin_add_user_extra',{dkd_target_user_id:dkdSelectedUserId,dkd_extra_kind_value:kind,dkd_extra_amount_value:amount,dkd_extra_title_value:title,dkd_extra_note_value:note});if(result.error){alert('Ek hak eklenemedi: '+result.error.message);return}dkdNote(dkdSelectedUserEmail+' kullanıcısına ek hak eklendi.',false);await dkdLoadData()}
async function dkdSelectUser(id){const user=dkdUsers.find(x=>x.dkd_id===id);dkdSelectedUserId=id;dkdSelectedUserEmail=user&&user.dkd_email?user.dkd_email:'Seçili kullanıcı';dkdById('dkd_selected_user_box').textContent=dkdSelectedUserEmail+' seçildi. Ek dakika, sesli mesaj, video mesaj, görsel veya özel bonus ekleyebilirsin.';dkdById('dkd_live_chat_user_box').textContent=dkdSelectedUserEmail+' ile Canlı Sohbet açık.';dkdRenderExtras();await dkdLoadLiveChat();dkdStartLiveChatRealtime()}
function dkdShowDetail(id){const row=dkdPayments.find(x=>x.dkd_id===id);dkdById('dkd_detail_box').textContent=row?dkdPrettyRow(row):'Kayıt bulunamadı.'}
function dkdRenderExtras(){const rows=dkdSelectedUserId?dkdExtras.filter(x=>x.dkd_user_id===dkdSelectedUserId):dkdExtras.slice(0,20);dkdById('dkd_extras_body').innerHTML=rows.map(x=>'<div class="dkd_user"><strong>'+dkdExtraKindText(x.dkd_extra_kind)+' +'+String(x.dkd_extra_amount)+'</strong><small>'+String(x.dkd_email||'-')+' • '+String(x.dkd_extra_title||'-')+' • '+dkdDate(x.dkd_created_at)+'</small><small>'+String(x.dkd_extra_note||'')+'</small></div>').join('')||'Ek hak kaydı yok.'}
function dkdRenderLiveChat(){const body=dkdById('dkd_live_chat_body');if(!body){return}if(!dkdSelectedUserId){body.textContent='Canlı mesaj kaydı bekleniyor...';return}if(!dkdLiveMessages.length){body.innerHTML='<div class="dkd_live_empty">Henüz mesaj yok. İlk admin mesajını buradan gönderebilirsin.</div>';return}body.innerHTML=dkdLiveMessages.map(m=>{const admin=m.dkd_sender_role==='admin'||m.dkd_sender_role==='anyela';const cls=admin?'dkd_live_msg_admin':'dkd_live_msg_user';const name=admin?'Anyela Admin':(m.dkd_sender_name||dkdSelectedUserEmail||'Üye');return '<div class="dkd_live_msg '+cls+'"><strong>'+dkdEscape(name)+'</strong><span>'+dkdEscape(m.dkd_message_body)+'</span><small>'+dkdEscape(dkdDate(m.dkd_created_at))+'</small></div>'}).join('');body.scrollTop=body.scrollHeight}
async function dkdLoadLiveChat(){if(!dkdSelectedUserId){dkdRenderLiveChat();return}const r=await dkdClient.from('dkd_anyela_chat_messages').select('dkd_id,dkd_user_id,dkd_sender_role,dkd_sender_name,dkd_message_body,dkd_created_at').eq('dkd_user_id',dkdSelectedUserId).order('dkd_created_at',{ascending:true}).limit(100);if(r.error){dkdById('dkd_live_chat_body').innerHTML='<div class="dkd_live_empty">Canlı sohbet alınamadı: '+dkdEscape(r.error.message)+'</div>';return}dkdLiveMessages=r.data||[];dkdRenderLiveChat()}
function dkdStartLiveChatRealtime(){if(dkdLiveChannel){dkdClient.removeChannel(dkdLiveChannel);dkdLiveChannel=null}if(!dkdSelectedUserId){return}dkdLiveChannel=dkdClient.channel('dkd_anyela_admin_live_chat_'+dkdSelectedUserId).on('postgres_changes',{event:'INSERT',schema:'public',table:'dkd_anyela_chat_messages',filter:'dkd_user_id=eq.'+dkdSelectedUserId},p=>{const m=p&&p.new?p.new:null;if(!m||dkdLiveMessages.some(x=>x.dkd_id===m.dkd_id)){return}dkdLiveMessages.push(m);dkdRenderLiveChat()}).subscribe()}
async function dkdSendLiveChat(){if(!dkdSelectedUserId){alert('Önce kullanıcı seç.');return}const input=dkdById('dkd_live_chat_message');const text=input&&input.value?input.value.trim():'';if(!text){return}const btn=dkdById('dkd_send_live_chat');btn.disabled=true;const result=await dkdClient.rpc('dkd_anyela_admin_insert_chat_message',{dkd_target_user_id:dkdSelectedUserId,dkd_message_text:text});btn.disabled=false;if(result.error){alert('Mesaj gönderilemedi: '+result.error.message);return}input.value='';await dkdLoadLiveChat()}
function dkdPaymentRow(row){const rights=dkdRightsFromRow(row);return '<tr><td>'+dkdDate(row.dkd_created_at)+'<br><span class="dkd_mini">'+row.dkd_id+'</span></td><td><b>'+String(row.dkd_email||'-')+'</b><br><span class="dkd_mini">'+String(row.dkd_display_name||'-')+' / '+String(row.dkd_role||'-')+'</span></td><td><b>'+String(row.dkd_package_title||'-')+'</b><br><span class="dkd_mini">'+String(row.dkd_payment_kind||'-')+' / '+String(row.dkd_package_key||'-')+'</span><br><span class="dkd_mini">Hak: '+rights.minutes+' dk • '+rights.photo+' foto • '+rights.voice+' ses • '+rights.video+' video</span></td><td>'+dkdMoney(row.dkd_amount_tl)+'</td><td>'+dkdBadge(row.dkd_status)+'</td><td>'+dkdReceiptButton(row)+'</td><td><button class="dkd_btn" data-detail="'+row.dkd_id+'">Detay</button> <button class="dkd_btn" data-approve="'+row.dkd_id+'">Onayla</button> <button class="dkd_btn dkd_danger" data-reject="'+row.dkd_id+'">Reddet</button></td></tr>'}
function dkdRender(){const rows=dkdFilteredRows();dkdById('dkd_stat_total').textContent=dkdPayments.length;dkdById('dkd_stat_pending').textContent=dkdPayments.filter(x=>x.dkd_status==='pending').length;dkdById('dkd_stat_approved').textContent=dkdMoney(dkdPayments.filter(x=>x.dkd_status==='approved').reduce((s,x)=>s+Number(x.dkd_amount_tl||0),0));dkdById('dkd_stat_users').textContent=dkdUsers.length;dkdById('dkd_payments_body').innerHTML=rows.map(dkdPaymentRow).join('')||'<tr><td colspan="7">Ödeme kaydı yok.</td></tr>';dkdById('dkd_users_body').innerHTML=dkdUsers.map(u=>'<div class="dkd_user" data-user="'+u.dkd_id+'"><strong>'+String(u.dkd_email||'-')+'</strong><small>'+String(u.dkd_role||'-')+' • '+dkdDate(u.dkd_created_at)+'</small></div>').join('')||'Kullanıcı yok.';document.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>dkdSelectUser(b.getAttribute('data-user')));document.querySelectorAll('[data-receipt]').forEach(b=>b.onclick=()=>{const row=dkdPayments.find(x=>x.dkd_id===b.getAttribute('data-receipt'));dkdOpenReceiptByRow(row)});document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>dkdShowDetail(b.getAttribute('data-detail')));document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>dkdMarkPayment(b.getAttribute('data-approve'),'approved'));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>dkdMarkPayment(b.getAttribute('data-reject'),'rejected'));dkdRenderExtras();dkdRenderLiveChat()}
dkdById('dkd_admin_login').onclick=async()=>{const email=dkdById('dkd_admin_email').value.trim();const password=dkdById('dkd_admin_password').value;const r=await dkdClient.auth.signInWithPassword({email,password});if(r.error){dkdNote('Giriş başarısız: '+r.error.message,true);return}await dkdLoadData()};dkdById('dkd_logout').onclick=async()=>{await dkdClient.auth.signOut();location.reload()};dkdById('dkd_refresh').onclick=dkdLoadData;dkdById('dkd_search').oninput=dkdRender;dkdById('dkd_status').onchange=dkdRender;dkdById('dkd_kind').onchange=dkdRender;dkdById('dkd_add_extra').onclick=dkdAddUserExtra;dkdById('dkd_send_live_chat').onclick=dkdSendLiveChat;dkdById('dkd_live_chat_message').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();dkdSendLiveChat()}});dkdLoadData();
})();
