(function(){
'use strict';
const dkdUrl='https://ztxlcfcwuwerxrhwfmte.supabase.co';
const dkdKey='sb_publishable_GSd5xFBwG9pioOY8N6MRQw_C2n7RLYa';
let dkdClient=null;
function dkdGetClient(){if(dkdClient){return dkdClient;}if(!window.supabase||!window.supabase.createClient){return null;}dkdClient=window.supabase.createClient(dkdUrl,dkdKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'dkd_anyela_auth_session'}});return dkdClient;}
function dkdAddStyle(){if(document.getElementById('dkd_admin_extra_delete_style')){return;}const s=document.createElement('style');s.id='dkd_admin_extra_delete_style';s.textContent='.dkd_extra_delete_button{margin-top:8px;border:0;border-radius:14px;padding:8px 11px;background:#ff3b8a;color:#fff;font-weight:900;cursor:pointer}.dkd_extra_delete_hint{display:block;margin-top:5px;color:#8efff7;font-size:11px;font-weight:800}';document.head.appendChild(s);}
function dkdExtraIdFromCard(card){const smallText=Array.from(card.querySelectorAll('small')).map(x=>x.textContent||'').join(' ');const match=smallText.match(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i);return match?match[0]:'';}
async function dkdFindExtraId(card){let id=dkdExtraIdFromCard(card);if(id){return id;}const client=dkdGetClient();if(!client){return '';}const title=(card.querySelector('strong')||{}).textContent||'';const result=await client.from('dkd_anyela_admin_user_extra_summary').select('dkd_id,dkd_extra_kind,dkd_extra_amount,dkd_email,dkd_extra_title,dkd_created_at').order('dkd_created_at',{ascending:false}).limit(100);if(result.error){return '';}const text=(card.textContent||'').toLowerCase();const row=(result.data||[]).find(function(item){return text.includes(String(item.dkd_email||'').toLowerCase())&&text.includes(String(item.dkd_extra_title||'').toLowerCase())&&title.toLowerCase().includes(String(item.dkd_extra_amount||''));});return row?row.dkd_id:'';}
async function dkdDeleteExtra(card){const id=await dkdFindExtraId(card);if(!id){alert('Ek hak ID bulunamadı. Lütfen Admin panelini yenileyip tekrar dene.');return;}const ok=confirm('Bu kullanıcı ek hakkı veritabanından silinsin mi?');if(!ok){return;}const client=dkdGetClient();if(!client){alert('Supabase bağlantısı hazır değil.');return;}const result=await client.rpc('dkd_anyela_admin_delete_user_extra',{dkd_extra_id:id});if(result.error){alert('Ek hak silinemedi: '+result.error.message);return;}alert('Ek hak silindi.');const refresh=document.getElementById('dkd_refresh');if(refresh){refresh.click();}else{location.reload();}}
function dkdPatchExtras(){const body=document.getElementById('dkd_extras_body');if(!body){return;}body.querySelectorAll('.dkd_user').forEach(function(card){if(card.querySelector('[data-dkd-extra-delete]')){return;}const btn=document.createElement('button');btn.type='button';btn.className='dkd_extra_delete_button';btn.textContent='Sil';btn.setAttribute('data-dkd-extra-delete','1');card.appendChild(btn);});}
function dkdBind(){document.addEventListener('click',function(event){const btn=event.target&&event.target.closest?event.target.closest('[data-dkd-extra-delete]'):null;if(!btn){return;}event.preventDefault();const card=btn.closest('.dkd_user');if(card){dkdDeleteExtra(card);}});const body=document.getElementById('dkd_extras_body');if(body){new MutationObserver(dkdPatchExtras).observe(body,{childList:true,subtree:true});}dkdPatchExtras();}
function dkdInit(){dkdAddStyle();dkdGetClient();dkdBind();}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',dkdInit);}else{dkdInit();}
})();
