(function(){
'use strict';
const dkdUrl='https://ztxlcfcwuwerxrhwfmte.supabase.co';
const dkdKey='sb_publishable_GSd5xFBwG9pioOY8N6MRQw_C2n7RLYa';
let dkdClient=null;
function dkdGetClient(){if(dkdClient){return dkdClient;}if(!window.supabase||!window.supabase.createClient){return null;}dkdClient=window.supabase.createClient(dkdUrl,dkdKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'dkd_anyela_auth_session'}});return dkdClient;}
function dkdAddStyle(){if(document.getElementById('dkd_admin_payment_hotfix_style')){return;}const s=document.createElement('style');s.id='dkd_admin_payment_hotfix_style';s.textContent='.dkd_admin_hidden_live{display:none!important}.dkd_admin_delete_payment{margin-left:6px}.dkd_admin_rights_line{display:block;margin-top:4px;color:#8efff7;font-size:11px;font-weight:800}';document.head.appendChild(s);}
function dkdRights(rowText){const lower=String(rowText||'').toLowerCase();if(lower.includes('aylık')||lower.includes('abonelik')||lower.includes('monthly')){return 'Hak: günlük 240 dk • 3 foto • 3 ses • 1 video';}if(lower.includes('full')){return 'Hak: 720 dk • 5 foto • 3 ses • 1 video';}if(lower.includes('vip')){return 'Hak: 120 dk • 5 foto • 0 ses • 0 video';}if(lower.includes('ses')||lower.includes('voice')){return 'Hak: 20 dk • 0 foto • 3 ses • 0 video';}if(lower.includes('mini')){return 'Hak: 15 dk • 0 foto • 0 ses • 0 video';}return '';
}
function dkdPatchRows(){const body=document.getElementById('dkd_payments_body');if(!body){return;}body.querySelectorAll('tr').forEach(function(row){const detailButton=row.querySelector('[data-detail]');if(!detailButton){return;}const id=detailButton.getAttribute('data-detail');if(!id){return;}const rights=dkdRights(row.textContent);const packageCell=row.children&&row.children[2]?row.children[2]:null;if(rights&&packageCell&&!packageCell.querySelector('.dkd_admin_rights_line')){const line=document.createElement('span');line.className='dkd_admin_rights_line';line.textContent=rights;packageCell.appendChild(line);}const actionCell=row.children&&row.children[6]?row.children[6]:null;if(actionCell&&!actionCell.querySelector('[data-dkd-admin-delete-payment]')){const btn=document.createElement('button');btn.className='dkd_btn dkd_danger dkd_admin_delete_payment';btn.type='button';btn.textContent='Sil';btn.setAttribute('data-dkd-admin-delete-payment',id);actionCell.appendChild(btn);}}
)}
async function dkdDeletePayment(id){const ok=confirm('Bu ödeme/dekont talebi veritabanından silinsin mi?');if(!ok){return;}const client=dkdGetClient();if(!client){alert('Supabase bağlantısı hazır değil.');return;}const result=await client.rpc('dkd_anyela_admin_delete_payment',{dkd_payment_id:id});if(result.error){alert('Silinemedi: '+result.error.message);return;}alert('Ödeme/dekont talebi silindi.');const refresh=document.getElementById('dkd_refresh');if(refresh){refresh.click();}else{location.reload();}}
function dkdBind(){document.addEventListener('click',function(e){const btn=e.target&&e.target.closest?e.target.closest('[data-dkd-admin-delete-payment]'):null;if(!btn){return;}e.preventDefault();dkdDeletePayment(btn.getAttribute('data-dkd-admin-delete-payment'));});const body=document.getElementById('dkd_payments_body');if(body){new MutationObserver(dkdPatchRows).observe(body,{childList:true,subtree:true});}dkdPatchRows();}
function dkdInit(){dkdAddStyle();dkdGetClient();dkdBind();}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',dkdInit);}else{dkdInit();}
})();
