import 'dotenv/config';
import express from 'express';
import { createClient } from '@supabase/supabase-js';

const dkdPort = Number(process.env.DKD_ADMIN_PORT || 8787);
const dkdAdminPanelKey = process.env.DKD_ADMIN_PANEL_KEY || '';
const dkdSupabaseUrl = process.env.DKD_SUPABASE_URL || '';
const dkdSupabaseServiceRoleKey = process.env.DKD_SUPABASE_SERVICE_ROLE_KEY || '';

if (!dkdSupabaseUrl || !dkdSupabaseServiceRoleKey) {
  console.error('Missing DKD_SUPABASE_URL or DKD_SUPABASE_SERVICE_ROLE_KEY');
  process.exit(1);
}

if (!dkdAdminPanelKey || dkdAdminPanelKey === 'local-admin-key-change-me') console.warn('Warning: DKD_ADMIN_PANEL_KEY should be changed before real use.');
const dkdSupabase = createClient(dkdSupabaseUrl, dkdSupabaseServiceRoleKey, { auth: { persistSession: false, autoRefreshToken: false } });
const dkdApp = express();
dkdApp.use(express.json({ limit: '256kb' }));
dkdApp.use(express.urlencoded({ extended: true }));
dkdApp.use(express.static(new URL('../public', import.meta.url).pathname));
function dkdRequireAdmin(req, res, next) { const dkdGivenKey = req.headers['x-dkd-admin-key'] || req.query.dkd_key || (req.headers.cookie || '').split(';').map((c) => c.trim()).find((c) => c.startsWith('dkd_admin_key='))?.split('=')[1]; if (!dkdAdminPanelKey || dkdGivenKey !== dkdAdminPanelKey) return res.status(401).json({ dkd_error: 'unauthorized' }); next(); }
function dkdSafeError(dkdError) { if (dkdError instanceof Error) return dkdError.message; try { return JSON.stringify(dkdError); } catch { return String(dkdError); } }

dkdApp.get('/api/dkd-health', dkdRequireAdmin, async (req, res) => { const { data, error } = await dkdSupabase.from('dkd_deal_system_settings').select('dkd_setting_key, dkd_setting_value').in('dkd_setting_key', ['dkd_deal_worker_runtime_mode','dkd_deal_termux_telegram_live_test','dkd_deal_hot_deals_version','dkd_deal_affiliate_links_version','dkd_deal_source_admin_version','dkd_deal_manual_telegram_draft_version']).order('dkd_setting_key'); if (error) return res.status(500).json({ dkd_error: dkdSafeError(error) }); res.json({ dkd_ok: true, dkd_settings: data || [] }); });
dkdApp.get('/api/dkd-sources', dkdRequireAdmin, async (req, res) => { const { data, error } = await dkdSupabase.from('dkd_deal_sources').select('dkd_id, dkd_source_key, dkd_source_name, dkd_country_code, dkd_source_type, dkd_parser_mode, dkd_allowed_by_terms, dkd_needs_manual_review, dkd_is_active, dkd_priority, dkd_crawl_interval_minutes, dkd_updated_at').eq('dkd_country_code','TR').order('dkd_priority', { ascending: true }).order('dkd_source_key'); if (error) return res.status(500).json({ dkd_error: dkdSafeError(error) }); res.json({ dkd_ok: true, dkd_rows: data || [] }); });
dkdApp.post('/api/dkd-sources/:dkdSourceId', dkdRequireAdmin, async (req, res) => { const dkdSourceId = String(req.params.dkdSourceId || '').trim(); const dkdPriority = Number(req.body.dkd_priority || 10); const dkdCrawlInterval = Number(req.body.dkd_crawl_interval_minutes || 1440); if (!dkdSourceId) return res.status(400).json({ dkd_error: 'missing_source_id' }); const { data, error } = await dkdSupabase.from('dkd_deal_sources').update({ dkd_is_active: Boolean(req.body.dkd_is_active), dkd_allowed_by_terms: Boolean(req.body.dkd_allowed_by_terms), dkd_needs_manual_review: Boolean(req.body.dkd_needs_manual_review), dkd_priority: Number.isFinite(dkdPriority) ? dkdPriority : 10, dkd_crawl_interval_minutes: Number.isFinite(dkdCrawlInterval) ? dkdCrawlInterval : 1440, dkd_updated_at: new Date().toISOString() }).eq('dkd_id', dkdSourceId).select('dkd_id').single(); if (error) return res.status(500).json({ dkd_error: dkdSafeError(error) }); res.json({ dkd_ok: true, dkd_result: data }); });
dkdApp.post('/api/dkd-watch-links', dkdRequireAdmin, async (req, res) => { const dkdUrl = String(req.body.dkd_url || '').trim(); const dkdPriority = Number(req.body.dkd_priority || 10); if (!dkdUrl) return res.status(400).json({ dkd_error: 'missing_url' }); const { data, error } = await dkdSupabase.rpc('dkd_deal_add_watch_link_v0_7_2', { dkd_url: dkdUrl, dkd_priority: dkdPriority, dkd_note: 'Added from DraBornDeal admin panel.' }); if (error) return res.status(500).json({ dkd_error: dkdSafeError(error) }); res.json({ dkd_ok: true, dkd_result: data }); });
dkdApp.get('/api/dkd-watch-links', dkdRequireAdmin, async (req, res) => { const { data, error } = await dkdSupabase.from('dkd_deal_watch_link_queue_v0_7_2').select('*').limit(30); if (error) return res.status(500).json({ dkd_error: dkdSafeError(error) }); res.json({ dkd_ok: true, dkd_rows: data || [] }); });
dkdApp.get('/api/dkd-products', dkdRequireAdmin, async (req, res) => { const { data, error } = await dkdSupabase.from('dkd_deal_products').select('dkd_id, dkd_product_name, dkd_brand_name, dkd_product_url, dkd_image_url, dkd_currency_code, dkd_current_price, dkd_original_price, dkd_discount_percent, dkd_stock_status, dkd_rating, dkd_review_count, dkd_deal_score, dkd_trend_score, dkd_created_at, dkd_updated_at').order('dkd_updated_at', { ascending: false }).limit(30); if (error) return res.status(500).json({ dkd_error: dkdSafeError(error) }); res.json({ dkd_ok: true, dkd_rows: data || [] }); });
dkdApp.post('/api/dkd-products/:dkdProductId/manual-telegram-draft', dkdRequireAdmin, async (req, res) => { const dkdProductId = String(req.params.dkdProductId || '').trim(); if (!dkdProductId) return res.status(400).json({ dkd_error: 'missing_product_id' }); const { data, error } = await dkdSupabase.rpc('dkd_deal_create_manual_telegram_draft_v0_11', { dkd_product_id_input: dkdProductId, dkd_channel_key_input: 'draborndeal_tr_main' }); if (error) return res.status(500).json({ dkd_error: dkdSafeError(error) }); res.json({ dkd_ok: true, dkd_result: data }); });
dkdApp.get('/api/dkd-hot-feed', dkdRequireAdmin, async (req, res) => { const { data, error } = await dkdSupabase.from('dkd_deal_hot_ranked_products_v0_5').select('*').order('dkd_hot_score', { ascending: false }).limit(30); if (error) return res.status(500).json({ dkd_error: dkdSafeError(error) }); res.json({ dkd_ok: true, dkd_rows: data || [] }); });
dkdApp.get('/api/dkd-social-posts', dkdRequireAdmin, async (req, res) => { const { data, error } = await dkdSupabase.from('dkd_deal_social_post_queue_v0_6').select('*').limit(30); if (error) return res.status(500).json({ dkd_error: dkdSafeError(error) }); res.json({ dkd_ok: true, dkd_rows: data || [] }); });
dkdApp.get('/api/dkd-affiliate-rules', dkdRequireAdmin, async (req, res) => { const { data, error } = await dkdSupabase.from('dkd_deal_affiliate_rules_v0_9').select('*').limit(50); if (error) return res.status(500).json({ dkd_error: dkdSafeError(error) }); res.json({ dkd_ok: true, dkd_rows: data || [] }); });
dkdApp.post('/api/dkd-affiliate-rules/:dkdRuleId', dkdRequireAdmin, async (req, res) => { const dkdRuleId = String(req.params.dkdRuleId || '').trim(); const dkdMode = String(req.body.dkd_affiliate_mode || 'append_query'); if (!dkdRuleId) return res.status(400).json({ dkd_error: 'missing_rule_id' }); if (!['append_query','template','none'].includes(dkdMode)) return res.status(400).json({ dkd_error: 'invalid_affiliate_mode' }); const { data, error } = await dkdSupabase.from('dkd_deal_affiliate_rules').update({ dkd_is_active: Boolean(req.body.dkd_is_active), dkd_affiliate_mode: dkdMode, dkd_param_key: String(req.body.dkd_param_key || '').trim() || null, dkd_param_value: String(req.body.dkd_param_value || '').trim() || null, dkd_template_url: String(req.body.dkd_template_url || '').trim() || null, dkd_notes: 'Updated from DraBornDeal admin panel v0.9.', dkd_updated_at: new Date().toISOString() }).eq('dkd_id', dkdRuleId).select('dkd_id').single(); if (error) return res.status(500).json({ dkd_error: dkdSafeError(error) }); res.json({ dkd_ok: true, dkd_result: data }); });
dkdApp.post('/api/dkd-generate-drafts', dkdRequireAdmin, async (req, res) => { const dkdLimit = Number(req.body.dkd_limit || 10); const { data, error } = await dkdSupabase.rpc('dkd_deal_generate_telegram_drafts_v0_6', { dkd_country_filter: 'TR', dkd_limit: dkdLimit }); if (error) return res.status(500).json({ dkd_error: dkdSafeError(error) }); res.json({ dkd_ok: true, dkd_result: data }); });
dkdApp.listen(dkdPort, '0.0.0.0', () => console.log(JSON.stringify({ dkd_message: 'dkd_admin_started', dkd_port: dkdPort })));
