const dkdState={news:[],category:'Tümü',query:''};
const dkdEls={grid:document.querySelector('#dkdNewsGrid'),empty:document.querySelector('#dkdEmpty'),filters:document.querySelector('#dkdFilters'),search:document.querySelector('#dkdSearch'),lead:document.querySelector('#dkdLeadStory'),count:document.querySelector('#dkdNewsCount'),sources:document.querySelector('#dkdSourceCount'),updateAgo:document.querySelector('#dkdUpdateAgo'),resultCount:document.querySelector('#dkdResultCount'),dialog:document.querySelector('#dkdArticleDialog'),dialogBody:document.querySelector('#dkdDialogBody'),dialogClose:document.querySelector('#dkdDialogClose')};
const dkdDecode=(dkdValue='')=>{const dkdDecoder=document.createElement('textarea');dkdDecoder.innerHTML=String(dkdValue);return dkdDecoder.value.replace(/\s+The post .+? appeared first on .+?\.?$/i,'').replace(/\s+Read more\s*$/i,'').replace(/\s+/g,' ').trim();};
const dkdEscape=(dkdValue='')=>dkdDecode(dkdValue).replace(/[&<>'"]/g,dkdChar=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[dkdChar]));
const dkdAgo=(dkdDate)=>{const dkdSeconds=Math.max(0,(Date.now()-new Date(dkdDate).getTime())/1000);if(dkdSeconds<60)return 'şimdi';if(dkdSeconds<3600)return `${Math.floor(dkdSeconds/60)} dk`;if(dkdSeconds<86400)return `${Math.floor(dkdSeconds/3600)} sa`;return `${Math.floor(dkdSeconds/86400)} gün`;};
const dkdArticleUrl=(dkdItem)=>`?id=${encodeURIComponent(dkdItem.id)}`;
function dkdCleanItem(dkdItem){return {...dkdItem,title:dkdDecode(dkdItem.title),summary:dkdDecode(dkdItem.summary),whyItMatters:dkdDecode(dkdItem.whyItMatters),bullets:(dkdItem.bullets||[]).map(dkdDecode),tags:(dkdItem.tags||[]).map(dkdDecode)};}
function dkdFiltered(){return dkdState.news.filter(dkdItem=>{const dkdCategoryOk=dkdState.category==='Tümü'||dkdItem.category===dkdState.category;const dkdHaystack=`${dkdItem.title} ${dkdItem.summary} ${(dkdItem.tags||[]).join(' ')}`.toLocaleLowerCase('tr');return dkdCategoryOk&&dkdHaystack.includes(dkdState.query.toLocaleLowerCase('tr'));});}
function dkdRenderLead(){const dkdItem=dkdState.news[0];if(!dkdItem)return;dkdEls.lead.classList.remove('dkd-skeleton');dkdEls.lead.dataset.id=dkdItem.id;dkdEls.lead.innerHTML=`<div class="dkd-lead-glow"></div><span class="dkd-chip">${dkdEscape(dkdItem.category||'RADAR')} • ÖNE ÇIKAN</span><h2>${dkdEscape(dkdItem.title)}</h2><p>${dkdEscape(dkdItem.summary)}</p><div class="dkd-lead-meta"><span>${dkdEscape(dkdItem.source)}</span><span>•</span><span>${dkdAgo(dkdItem.publishedAt)} önce</span><span>•</span><span>Radar ${dkdItem.score||0}/100</span></div>`;}
function dkdRender(){const dkdItems=dkdFiltered();dkdEls.resultCount.textContent=`${dkdItems.length} içerik`;dkdEls.empty.hidden=dkdItems.length>0;dkdEls.grid.innerHTML=dkdItems.map(dkdItem=>`<article class="dkd-card" data-id="${dkdEscape(dkdItem.id)}" tabindex="0"><div class="dkd-card-top"><span class="dkd-category">${dkdEscape(dkdItem.icon||'⚡')} ${dkdEscape(dkdItem.category)}</span><span class="dkd-time">${dkdAgo(dkdItem.publishedAt)} önce</span></div><h3>${dkdEscape(dkdItem.title)}</h3><p>${dkdEscape(dkdItem.summary)}</p><div class="dkd-card-bottom"><span class="dkd-source">${dkdEscape(dkdItem.source)}</span><span class="dkd-score">RADAR ${dkdItem.score||0}</span></div></article>`).join('');}
function dkdOpenArticle(dkdItem,{dkdPush=true}={}){if(!dkdItem)return;const dkdBullets=(dkdItem.bullets||[]).map(dkdBullet=>`<div class="dkd-bullet">✦ ${dkdEscape(dkdBullet)}</div>`).join('');const dkdTags=(dkdItem.tags||[]).map(dkdTag=>`<span>#${dkdEscape(dkdTag.replace(/^#/,''))}</span>`).join('');dkdEls.dialogBody.innerHTML=`<article class="dkd-dialog-content"><span class="dkd-category">${dkdEscape(dkdItem.icon||'⚡')} ${dkdEscape(dkdItem.category)} • ${dkdEscape(dkdItem.source)}</span><h2>${dkdEscape(dkdItem.title)}</h2><p class="dkd-summary">${dkdEscape(dkdItem.summary)}</p><div class="dkd-bullets">${dkdBullets}</div>${dkdItem.whyItMatters?`<div class="dkd-why"><b>💡 Neden önemli?</b><p>${dkdEscape(dkdItem.whyItMatters)}</p></div>`:''}<a class="dkd-source-btn" href="${dkdEscape(dkdItem.url)}" target="_blank" rel="noopener noreferrer">Orijinal kaynağı aç ↗</a><div class="dkd-tags">${dkdTags}</div></article>`;if(!dkdEls.dialog.open)dkdEls.dialog.showModal();if(dkdPush)history.pushState({},'',dkdArticleUrl(dkdItem));}
function dkdCloseArticle(){if(dkdEls.dialog.open)dkdEls.dialog.close();if(new URL(location.href).searchParams.has('id'))history.pushState({},'',location.pathname);}
async function dkdLoad(){try{const dkdResponse=await fetch(`./data/news.json?v=${Date.now()}`,{cache:'no-store'});if(!dkdResponse.ok)throw new Error('news.json okunamadı');const dkdPayload=await dkdResponse.json();const dkdItems=Array.isArray(dkdPayload.items)?dkdPayload.items:[];dkdState.news=dkdItems.map(dkdCleanItem);dkdEls.count.textContent=dkdState.news.length;dkdEls.sources.textContent=new Set(dkdState.news.map(dkdItem=>dkdItem.source)).size;dkdEls.updateAgo.textContent=dkdPayload.generatedAt?`${dkdAgo(dkdPayload.generatedAt)} önce`:'—';dkdRenderLead();dkdRender();const dkdRequestedId=new URL(location.href).searchParams.get('id');if(dkdRequestedId)dkdOpenArticle(dkdState.news.find(dkdItem=>dkdItem.id===dkdRequestedId),{dkdPush:false});}catch(dkdError){console.error('[DraBornNews]',dkdError);dkdEls.empty.hidden=false;}}
dkdEls.filters.addEventListener('click',dkdEvent=>{const dkdButton=dkdEvent.target.closest('button[data-category]');if(!dkdButton)return;dkdState.category=dkdButton.dataset.category;[...dkdEls.filters.querySelectorAll('button')].forEach(dkdEl=>dkdEl.classList.toggle('active',dkdEl===dkdButton));dkdRender();});
dkdEls.search.addEventListener('input',dkdEvent=>{dkdState.query=dkdEvent.target.value.trim();dkdRender();});
document.addEventListener('click',dkdEvent=>{const dkdCard=dkdEvent.target.closest('[data-id]');if(!dkdCard)return;dkdOpenArticle(dkdState.news.find(dkdItem=>dkdItem.id===dkdCard.dataset.id));});
document.addEventListener('keydown',dkdEvent=>{if(dkdEvent.key!=='Enter')return;const dkdCard=dkdEvent.target.closest('.dkd-card[data-id]');if(dkdCard)dkdOpenArticle(dkdState.news.find(dkdItem=>dkdItem.id===dkdCard.dataset.id));});
dkdEls.dialogClose.addEventListener('click',dkdCloseArticle);dkdEls.dialog.addEventListener('click',dkdEvent=>{if(dkdEvent.target===dkdEls.dialog)dkdCloseArticle();});window.addEventListener('popstate',()=>{const dkdId=new URL(location.href).searchParams.get('id');if(!dkdId){if(dkdEls.dialog.open)dkdEls.dialog.close();return;}dkdOpenArticle(dkdState.news.find(dkdItem=>dkdItem.id===dkdId),{dkdPush:false});});
dkdLoad();
